ServerEvents.recipes(event => {
    // Citrine -> SiO2
    event.recipes.gtceu.centrifuge('kubejs:centrifuge_citrine')
        .itemInputs('1x gtceu:citrine_dust')
        .itemOutputs('1x gtceu:silicon_dioxide_dust')
        .EUt(32)
        .duration(200)

    // Tarapacaite -> potassium chromate
    event.recipes.gtceu.centrifuge('kubejs:centrifuge_tarapacaite')
        .itemInputs('1x gtceu:tarapacaite_dust')
        .itemOutputs('1x gtceu:potassium_chromate_dust')
        .EUt(32)
        .duration(200)

    // Labyrinthite decomp
    event.recipes.gtceu.centrifuge('kubejs:centrifuge_labyrinthite')
        .itemInputs('187x gtceu:labyrinthite_dust')
        .EUt(256)
        .duration(400)
        .outputFluids("gtceu:oxygen 58000", "gtceu:hydrogen 9000", "gtceu:chlorine 3000", "minecraft:water 9000")
        .itemOutputs("12x gtceu:calcium_dust", "3x gtceu:iron_dust", "6x gtceu:zirconium_dust", "1x gtceu:rutile_dust", "51x gtceu:silicon_dioxide_dust")
        .chancedOutput("35x gtceu:sodium_dust", 3333, 0)
        .chancedOutput("35x gtceu:potassium_dust", 3333, 0)
        .chancedOutput("35x gtceu:strontium_dust", 3333, 0)
        .chancedItemOutputLogic(ChanceLogic.XOR)

    // Anatase and Brookite -> TiCL4
    event.recipes.gtceu.chemical_reactor('titanium_tetrachloride_anatase')
        .itemInputs('2x gtceu:carbon_dust', '1x gtceu:anatase_dust')
        .inputFluids('gtceu:chlorine 4000')
        .outputFluids('gtceu:carbon_monoxide 2000', 'gtceu:titanium_tetrachloride 1000')
        .EUt(480)
        .duration(400)
    event.recipes.gtceu.chemical_reactor('titanium_tetrachloride_brookite')
        .itemInputs('2x gtceu:carbon_dust', '1x gtceu:brookite_dust')
        .inputFluids('gtceu:chlorine 4000')
        .outputFluids('gtceu:carbon_monoxide 2000', 'gtceu:titanium_tetrachloride 1000')
        .EUt(480)
        .duration(400)

    // Tungstic ores
    event.recipes.gtceu.chemical_bath('tungstic_acid_from_russelite')
        .itemInputs('6x gtceu:russellite_dust') 
        .inputFluids('gtceu:hydrochloric_acid 2000') 
        .itemOutputs('6x gtceu:tungstic_acid_dust', '4x gtceu:bismite_dust', '4x gtceu:bismuth_chloride_dust') 
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(210)
    event.recipes.gtceu.chemical_bath('tungstic_acid_from_tungstite')
        .itemInputs('4x gtceu:tungstite_dust') 
        .inputFluids('gtceu:hydrochloric_acid 1000') 
        .itemOutputs('4x gtceu:tungstic_acid_dust')
        .outputFluids('gtceu:diluted_hydrochloric_acid 1000')
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(210)
    event.recipes.gtceu.chemical_bath('tungstic_acid_from_ferberite')
        .itemInputs("6x gtceu:ferberite_dust")
        .inputFluids("gtceu:hydrochloric_acid 2000")
        .itemOutputs("7x gtceu:tungstic_acid_dust", "3x gtceu:iron_ii_chloride_dust")
        .duration(210)
        .EUt(GTValues.VHA[GTValues.EV])
    event.recipes.gtceu.chemical_bath('tungstic_acid_from_hubnerite')
        .itemInputs("6x gtceu:hubnerite_dust")
        .inputFluids("gtceu:hydrochloric_acid 2000")
        .itemOutputs("7x gtceu:tungstic_acid_dust", "3x gtceu:manganese_ii_chloride_dust")
        .duration(210)
        .EUt(GTValues.VHA[GTValues.EV])
})