ServerEvents.recipes(event => {
    // Citrine -> SiO2
    event.recipes.gtceu.centrifuge('kubejs:centrifuge_citrine')
        .itemInputs('1x gtceu:citrine_dust')
        .itemOutputs('1x gtceu:silicon_dioxide_dust')
        .EUt(32)
        .duration(200)

    // Tarapacaite -> potassium chromate
    event.recipes.gtceu.centrifuge('kubejs:centrifuge_tarapacaite')
        .itemInputs('1x gtceu:tarapacaite_dust')
        .itemOutputs('1x gtceu:potassium_chromate_dust')
        .EUt(32)
        .duration(200)

    // Labyrinthite decomp
    event.recipes.gtceu.centrifuge('kubejs:centrifuge_labyrinthite')
        .itemInputs('187x gtceu:labyrinthite_dust')
        .EUt(256)
        .duration(400)
        .outputFluids("gtceu:oxygen 58000", "gtceu:hydrogen 9000", "gtceu:chlorine 3000", "minecraft:water 9000")
        .itemOutputs("12x gtceu:calcium_dust", "3x gtceu:iron_dust", "6x gtceu:zirconium_dust", "1x gtceu:rutile_dust", "51x gtceu:silicon_dioxide_dust")
        .chancedOutput("35x gtceu:sodium_dust", 3333, 0)
        .chancedOutput("35x gtceu:potassium_dust", 3333, 0)
        .chancedOutput("35x gtceu:strontium_dust", 3333, 0)
        .chancedItemOutputLogic(ChanceLogic.XOR)

    // Anatase and Brookite -> TiCL4
    event.recipes.gtceu.chemical_reactor('titanium_tetrachloride_anatase')
        .itemInputs('2x gtceu:carbon_dust', '1x gtceu:anatase_dust')
        .inputFluids('gtceu:chlorine 4000')
        .outputFluids('gtceu:carbon_monoxide 2000', 'gtceu:titanium_tetrachloride 1000')
        .EUt(480)
        .duration(400)
    event.recipes.gtceu.chemical_reactor('titanium_tetrachloride_brookite')
        .itemInputs('2x gtceu:carbon_dust', '1x gtceu:brookite_dust')
        .inputFluids('gtceu:chlorine 4000')
        .outputFluids('gtceu:carbon_monoxide 2000', 'gtceu:titanium_tetrachloride 1000')
        .EUt(480)
        .duration(400)

    // Tungstic ores
    event.recipes.gtceu.chemical_bath('tungstic_acid_from_russelite')
        .itemInputs('6x gtceu:russellite_dust') 
        .inputFluids('gtceu:hydrochloric_acid 2000') 
        .itemOutputs('6x gtceu:tungstic_acid_dust', '4x gtceu:bismite_dust', '4x gtceu:bismuth_chloride_dust') 
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(210)
    event.recipes.gtceu.chemical_bath('tungstic_acid_from_tungstite')
        .itemInputs('4x gtceu:tungstite_dust') 
        .inputFluids('gtceu:hydrochloric_acid 1000') 
        .itemOutputs('4x gtceu:tungstic_acid_dust')
        .outputFluids('gtceu:diluted_hydrochloric_acid 1000')
        .EUt(GTValues.VHA[GTValues.EV])
        .duration(210)
    event.recipes.gtceu.chemical_bath('tungstic_acid_from_ferberite')
        .itemInputs("6x gtceu:ferberite_dust")
        .inputFluids("gtceu:hydrochloric_acid 2000")
        .itemOutputs("7x gtceu:tungstic_acid_dust", "3x gtceu:iron_ii_chloride_dust")
        .duration(210)
        .EUt(GTValues.VHA[GTValues.EV])
    event.recipes.gtceu.chemical_bath('tungstic_acid_from_hubnerite')
        .itemInputs("6x gtceu:hubnerite_dust")
        .inputFluids("gtceu:hydrochloric_acid 2000")
        .itemOutputs("7x gtceu:tungstic_acid_dust", "3x gtceu:manganese_ii_chloride_dust")
        .duration(210)
        .EUt(GTValues.VHA[GTValues.EV])

    // Stones that dont have a decomp yet
    // Tuff
    event.recipes.gtceu.macerator("macerate_tuff")
        .itemInputs("1x minecraft:tuff")
        .itemOutputs("3x gtceu:dark_ash_dust")
        .chancedOutput("gtceu:stone_dust", 2500, 0)
        .chancedOutput("gtceu:obsidian_dust", 1000, 0)
        .duration(200)
        .EUt(GTValues.VHA[GTValues.MV])
    // Asurine
    event.recipes.gtceu.macerator("macerate_asurine")
        .itemInputs("1x create:asurine")
        .chancedOutput("gtceu:azurite_dust", 6000, 0)
        .chancedOutput("gtceu:zinc_sulfide_dust", 2500, 0)
        .chancedOutput("gtceu:cavansite_dust", 1000, 0)
        .chancedOutput("gtceu:potassium_cyanide_dust", 250, 0)
        .duration(200)
        .EUt(GTValues.VHA[GTValues.EV])
    // Limestone
    event.recipes.gtceu.macerator("macerate_limestone")
        .itemInputs("1x create:limestone")
        .chancedOutput("gtceu:calcite_dust", 4500, 0)
        .chancedOutput("gtceu:aragonite_dust", 4000, 0)
        .chancedOutput("gtceu:magnesite_dust", 1500, 0)
        .chancedOutput("gtceu:strontianite_dust", 500, 0)
        .duration(200)
        .EUt(GTValues.VHA[GTValues.HV])
    // Scorchia
    event.recipes.gtceu.macerator("macerate_scorchia")
        .itemInputs("1x create:scorchia")
        .chancedOutput("gtceu:blackstone_dust", 6000, 0)
        .chancedOutput("gtceu:sulfur_dust", 5000, 0)
        .chancedOutput("gtceu:barium_sulfide_dust", 1000, 0)
        .chancedOutput("gtceu:stibnite_dust", 750, 0)
        .duration(200)
        .EUt(GTValues.VHA[GTValues.EV])
    // Ochrum
    event.recipes.gtceu.macerator("macerate_ochrum")
        .itemInputs("1x create:ochrum")
        .chancedOutput("gtceu:fullers_earth_dust", 5000, 0)
        .chancedOutput("gtceu:gold_dust", 4000, 0)
        .chancedOutput("gtceu:lead_chromate_dust", 1500, 0)
        .chancedOutput("gtceu:pitchblende_dust", 500, 0)
        .duration(200)
        .EUt(GTValues.VHA[GTValues.EV])
    // Scoria
    event.recipes.gtceu.macerator("macerate_scoria")
        .itemInputs("1x create:scoria")
        .chancedOutput("gtceu:pyrochlore_dust", 4500, 0)
        .chancedOutput("gtceu:sulfur_dust", 4000, 0)
        .chancedOutput("gtceu:basaltic_mineral_sand_dust", 1500, 0)
        .chancedOutput("gtceu:zinc_sulfate_dust", 500, 0)
        .duration(200)
        .EUt(GTValues.VHA[GTValues.EV])
    // Crimsite
    event.recipes.gtceu.macerator("macerate_crimsite")
        .itemInputs("1x create:crimsite")
        .chancedOutput("gtceu:garnet_sand_dust", 4000, 0)
        .chancedOutput("gtceu:almandine_dust", 3500, 0)
        .chancedOutput("gtceu:zircon_dust", 2000, 0)
        .chancedOutput("gtceu:villiaumite_dust", 1000, 0)
        .duration(200)
        .EUt(GTValues.VHA[GTValues.EV])
    // Dripstone
    event.recipes.gtceu.macerator("macerate_dripstone")
        .itemInputs("1x minecraft:dripstone_block")
        .chancedOutput("gtceu:calcite_dust", 8000, 0)
        .chancedOutput("gtceu:calcium_hydroxide_dust", 2000, 0)
        .chancedOutput("gtceu:potassium_hydroxide_dust", 1000, 0)
        .chancedOutput("gtceu:aragonite_dust", 1000, 0)
        .duration(200)
        .EUt(GTValues.VHA[GTValues.MV])
    // Veridium
    event.recipes.gtceu.macerator("macerate_veridium")
        .itemInputs("1x create:veridium")
        .chancedOutput("gtceu:malachite_dust", 4500, 0)
        .chancedOutput("gtceu:bismite_dust", 2500, 0)
        .chancedOutput("gtceu:euclase_dust", 1500, 0)
        .chancedOutput("gtceu:beryllium_oxide_dust", 1000, 0)
        .duration(200)
        .EUt(GTValues.VHA[GTValues.EV])
    // Travertine
    event.recipes.gtceu.macerator("macerate_travertine")
        .itemInputs("1x natures_spirit:travertine")
        .chancedOutput("gtceu:aragonite_dust", 6000, 0)
        .chancedOutput("gtceu:hematite_dust", 3000, 0)
        .chancedOutput("gtceu:tricalcium_phosphate_dust", 2000, 0)
        .chancedOutput("gtceu:rare_earth_dust", 500, 0)
        .duration(200)
        .EUt(GTValues.VHA[GTValues.EV])
    // Chert
    event.recipes.gtceu.macerator("macerate_chert")
        .itemInputs("1x natures_spirit:chert")
        .chancedOutput("gtceu:flint_dust", 7000, 0)
        .chancedOutput("gtceu:goethite_dust", 2000, 0)
        .chancedOutput("gtceu:ferrosilite_dust", 2000, 0)
        .chancedOutput("gtceu:opal_dust", 500, 0)
        .duration(200)
        .EUt(GTValues.VHA[GTValues.EV])

})