ClientEvents.lang('en_us', event => {
    event.renameItem("rusticdelight:bell_pepper_seed_bag", "Paprika Seed Bag")
    event.renameItem("rusticdelight:bell_pepper_green_crate", "Green Bell Pepper Crate")
    event.renameItem("rusticdelight:bell_pepper_red_crate", "Red Bell Pepper Crate")
    event.renameItem("rusticdelight:bell_pepper_yellow_crate", "Yellow Bell Pepper Crate")
    event.renameItem("rusticdelight:wild_bell_peppers", "Wild Bell Peppers")
    event.renameItem("rusticdelight:bell_pepper_green", "Green Bell Pepper")
    event.renameItem("rusticdelight:bell_pepper_red", "Red Bell Pepper")
    event.renameItem("rusticdelight:bell_pepper_yellow", "Yellow Bell Pepper")
    event.renameItem("rusticdelight:bell_pepper_seeds", "Paprika Seeds")
    event.renameItem("rusticdelight:roasted_bell_pepper_green", "Roasted Green Bell Pepper")
    event.renameItem("rusticdelight:roasted_bell_pepper_red", "Roasted Red Bell Pepper")
    event.renameItem("rusticdelight:roasted_bell_pepper_yellow", "Roasted Yellow Bell Pepper")
    event.renameItem("rusticdelight:stuffed_bell_pepper_green", "Stuffed Green Bell Pepper")
    event.renameItem("rusticdelight:stuffed_bell_pepper_red", "Stuffed Red Bell Pepper")
    event.renameItem("rusticdelight:stuffed_bell_pepper_yellow", "Stuffed Yellow Bell Pepper")
    event.renameItem("rusticdelight:bell_pepper_roll_green", "Green Bell Pepper Roll")
    event.renameItem("rusticdelight:bell_pepper_roll_red", "Red Bell Pepper Roll")
    event.renameItem("rusticdelight:bell_pepper_roll_yellow", "Yellow Bell Pepper Roll")
    event.renameItem("rusticdelight:bell_pepper_soup", "Bell Pepper Soup")
    event.renameItem("rusticdelight:bell_pepper_pasta", "Bell Pepper Pasta")

    event.renameBlock("rusticdelight:bell_pepper_seed_bag", "Paprika Seed Bag")
    event.renameBlock("rusticdelight:bell_pepper_green_crate", "Green Bell Pepper Crate")
    event.renameBlock("rusticdelight:bell_pepper_red_crate", "Red Bell Pepper Crate")
    event.renameBlock("rusticdelight:bell_pepper_yellow_crate", "Yellow Bell Pepper Crate")
    event.renameBlock("rusticdelight:wild_bell_peppers", "Wild Bell Peppers")
})