ClientEvents.lang('en_us', event => {
    event.renameItem("rusticdelight:bell_pepper_seed_bag", "Paprika Seed Bag")
    event.renameItem("rusticdelight:bell_pepper_green_crate", "Green Paprika Crate")
    event.renameItem("rusticdelight:bell_pepper_red_crate", "Red Paprika Crate")
    event.renameItem("rusticdelight:bell_pepper_yellow_crate", "Yellow Paprika Crate")
    event.renameItem("rusticdelight:wild_bell_peppers", "Wild Paprika")
    event.renameItem("rusticdelight:bell_pepper_green", "Green Paprika")
    event.renameItem("rusticdelight:bell_pepper_red", "Red Paprika")
    event.renameItem("rusticdelight:bell_pepper_yellow", "Yellow Paprika")
    event.renameItem("rusticdelight:bell_pepper_seeds", "Paprika Seeds")
    event.renameItem("rusticdelight:roasted_bell_pepper_green", "Roasted Green Paprika")
    event.renameItem("rusticdelight:roasted_bell_pepper_red", "Roasted Red Paprika")
    event.renameItem("rusticdelight:roasted_bell_pepper_yellow", "Roasted Yellow Paprika")
    event.renameItem("rusticdelight:stuffed_bell_pepper_green", "Stuffed Green Paprika")
    event.renameItem("rusticdelight:stuffed_bell_pepper_red", "Stuffed Red Paprika")
    event.renameItem("rusticdelight:stuffed_bell_pepper_yellow", "Stuffed Yellow Paprika")
    event.renameItem("rusticdelight:bell_pepper_roll_green", "Green Paprika Roll")
    event.renameItem("rusticdelight:bell_pepper_roll_red", "Red Paprika Roll")
    event.renameItem("rusticdelight:bell_pepper_roll_yellow", "Yellow Paprika Roll")
    event.renameItem("rusticdelight:bell_pepper_soup", "Paprika Soup")
    event.renameItem("rusticdelight:bell_pepper_pasta", "Paprika Pasta")

    event.renameBlock("rusticdelight:bell_pepper_seed_bag", "Paprika Seed Bag")
    event.renameBlock("rusticdelight:bell_pepper_green_crate", "Green Paprika Crate")
    event.renameBlock("rusticdelight:bell_pepper_red_crate", "Red Paprika Crate")
    event.renameBlock("rusticdelight:bell_pepper_yellow_crate", "Yellow Paprika Crate")
    event.renameBlock("rusticdelight:wild_bell_peppers", "Wild Paprika")

    event.renameItem("ae2:silicon", "Rough Certic Silicon")
    event.renameItem("ae2:quartz_glass", "Fused Quartz")
    event.renameItem("ae2:quartz_vibrant_glass", "Vibrant Fused Quartz")
})