
[origins]

	[origins."origins:shulk"]
		"origins:strong_arms" = true
		"origins:no_shield" = true
		"origins:more_exhaustion" = true
		"origins:strong_arms_break_speed" = true
		"origins:natural_armor" = true
		enabled = true
		"origins:shulker_inventory" = true

	[origins."origins:merling"]
		"origins:air_from_potions" = true
		"origins:swim_speed" = true
		"origins:water_vision" = true
		"origins:like_water" = true
		"origins:aqua_affinity" = true
		"origins:water_breathing" = true
		"origins:conduit_power_on_land" = true
		enabled = true
		"origins:aquatic" = true

	[origins."origins:arachnid"]
		"origins:carnivore" = true
		"origins:fragile" = true
		"origins:arthropod" = true
		"origins:master_of_webs" = true
		enabled = true
		"origins:climbing" = true

	[origins."origins:phantom"]
		"origins:phasing" = true
		"origins:fragile" = true
		"origins:phantomize" = true
		"origins:translucent" = true
		"origins:invisibility" = true
		"origins:hunger_over_time" = true
		enabled = true
		"origins:burn_in_daylight" = true
		"origins:phantomize_overlay" = true

	[origins."origins:enderian"]
		"origins:water_vulnerability" = true
		"origins:throw_ender_pearl" = true
		"origins:pumpkin_hate" = true
		"origins:ender_particles" = true
		"origins:damage_from_potions" = true
		enabled = true
		"origins:extra_reach" = true

	[origins."origins:blazeborn"]
		"origins:water_vulnerability" = true
		"origins:flame_particles" = true
		"origins:burning_wrath" = true
		"origins:hotblooded" = true
		"origins:fire_immunity" = true
		"origins:damage_from_snowballs" = true
		"origins:nether_spawn" = true
		"origins:damage_from_potions" = true
		enabled = true

	[origins."origins:feline"]
		"origins:cat_vision" = true
		"origins:velvet_paws" = true
		"origins:fall_immunity" = true
		"origins:weak_arms" = true
		"origins:nine_lives" = true
		enabled = true
		"origins:sprint_jump" = true
		"origins:scare_creepers" = true

	[origins."origins:elytrian"]
		"origins:more_kinetic_damage" = true
		"origins:elytra" = true
		"origins:claustrophobia" = true
		"origins:aerial_combatant" = true
		"origins:light_armor" = true
		"origins:launch_into_air" = true
		enabled = true

	[origins."origins:human"]
		enabled = true

	[origins."origins:avian"]
		"origins:fresh_air" = true
		"origins:vegetarian" = true
		"origins:lay_eggs" = true
		"origins:slow_falling" = true
		"origins:tailwind" = true
		"origins:like_air" = true
		enabled = true

	[origins."dodo:dodo"]
		enabled = true
		"origins:slow_falling" = true
		"dodo:fragile" = true
		"dodo:small_stance" = true
		"dodo:feathers" = true
		"dodo:harvest" = true
		"dodo:hurtsound" = true
		"dodo:bird_diet" = true
		"dodo:air_speed" = true
		"dodo:fall_exhaust" = true
		"dodo:weak_melee" = true
		"dodo:launch_up" = true
		"dodo:wet_feathers" = true

	[origins."berserk:berserk"]
		enabled = true
		"berserk:melee_speed" = true
		"berserk:double_jump" = true
		"berserk:meat_eater" = true
		"berserk:vampire" = true
		"berserk:glass_cannon" = true
		"berserk:dash" = true
		"berserk:survive_death" = true

	[origins."centaur:centaur"]
		enabled = true
		"centaur:robust" = true
		"centaur:imposing" = true
		"centaur:rideable" = true
		"centaur:equine_diet" = true
		"centaur:large_stance" = true
		"centaur:melee_inaptitude" = true
		"centaur:saddle_bags" = true
		"centaur:weapon_specialty" = true
		"centaur:no_flight" = true
		"centaur:horse_kick" = true
		"centaur:armor_recipe" = true
		"centaur:kick_sense" = true
		"centaur:bag_slow" = true

	[origins."origins:origin_layers/origin"]
		enabled = true

	[origins."origins:dodo/powers/feathers"]
		enabled = true

	[origins."origins:dodo/powers/fall_exhaust"]
		enabled = true

	[origins."origins:frei/powers/teleport"]
		enabled = true

	[origins."origins:centaur/powers/equine_diet"]
		enabled = true

	[origins."origins:dodo/powers/harvest"]
		enabled = true

	[origins."origins:centaur/tags/items/vanilla_edible_foods"]
		enabled = true

	[origins."origins:centaur/tags/items/equine_diet_foods"]
		enabled = true

	[origins."origins:berserk/tags/items/extra_meat"]
		enabled = true

	[origins."origins:berserk/tags/items/all_shields"]
		enabled = true

	[origins."origins:centaur/powers/saddle_bags"]
		enabled = true

	[origins."origins:centaur/powers/imposing"]
		enabled = true

	[origins."origins:centaur/tags/items/all_shields"]
		enabled = true

	[origins."origins:berserk/predicates/chance"]
		enabled = true

	[origins."origins:frei/powers/drain_hp"]
		enabled = true

	[origins."origins:berserk/powers/vampire"]
		enabled = true

	[origins."origins:centaur/origins/centaur"]
		enabled = true
		"centaur:robust" = true
		"centaur:imposing" = true
		"centaur:rideable" = true
		"centaur:equine_diet" = true
		"centaur:large_stance" = true
		"centaur:melee_inaptitude" = true
		"centaur:saddle_bags" = true
		"centaur:weapon_specialty" = true
		"centaur:no_flight" = true
		"centaur:horse_kick" = true
		"centaur:armor_recipe" = true
		"centaur:bag_slow" = true

	[origins."origins:centaur/powers/weapon_specialty"]
		enabled = true

	[origins."origins:dodo/loot_tables/crop_loot"]
		enabled = true

	[origins."origins:berserk/powers/glass_cannon"]
		enabled = true

	[origins."origins:centaur/powers/archery_specialist"]
		enabled = true

	[origins."origins:frei/powers/toggle"]
		enabled = true

	[origins."origins:centaur/powers/melee_inaptitude"]
		enabled = true

	[origins."origins:dodo/powers/hurtsound"]
		enabled = true

	[origins."origins:centaur/powers/rideable"]
		enabled = true

	[origins."origins:centaur/powers/large_stance"]
		enabled = true

	[origins."origins:berserk/powers/melee_speed"]
		enabled = true

	[origins."origins:frei/origins/frei"]
		enabled = true
		"frei:teleport" = true
		"frei:drain_hp" = true
		"frei:phase" = true
		"frei:toggle" = true
		"frei:fragile" = true
		"frei:weapons" = true
		"frei:tall" = true

	[origins."origins:frei/powers/phase"]
		enabled = true

	[origins."origins:centaur/powers/horse_kick"]
		enabled = true

	[origins."origins:dodo/powers/fragile"]
		enabled = true

	[origins."origins:berserk/powers/meat_eater"]
		enabled = true

	[origins."origins:dodo/powers/small_stance"]
		enabled = true

	[origins."origins:dodo/origins/dodo"]
		enabled = true
		"origins:slow_falling" = true
		"dodo:fragile" = true
		"dodo:small_stance" = true
		"dodo:feathers" = true
		"dodo:harvest" = true
		"dodo:hurtsound" = true
		"dodo:bird_diet" = true
		"dodo:air_speed" = true
		"dodo:fall_exhaust" = true
		"dodo:weak_melee" = true
		"dodo:launch_up" = true
		"dodo:wet_feathers" = true

	[origins."origins:centaur/tags/items/ed_bad_bales"]
		enabled = true

	[origins."origins:centaur/powers/armor_recipe"]
		enabled = true

	[origins."origins:dodo/tags/items/seed_food"]
		enabled = true

	[origins."origins:dodo/powers/wet_feathers"]
		enabled = true

	[origins."origins:centaur/tags/items/reach_1_weapons"]
		enabled = true

	[origins."origins:berserk/powers/survive_death"]
		enabled = true

	[origins."origins:centaur/powers/bag_slow"]
		enabled = true

	[origins."origins:dodo/powers/air_speed"]
		enabled = true

	[origins."origins:berserk/powers/double_jump"]
		enabled = true

	[origins."origins:centaur/tags/items/ed_grains"]
		enabled = true

	[origins."origins:centaur/tags/items/ed_bad_grains"]
		enabled = true

	[origins."origins:dodo/powers/launch_up"]
		enabled = true

	[origins."origins:berserk/powers/dash"]
		enabled = true

	[origins."origins:centaur/powers/no_flight"]
		enabled = true

	[origins."origins:centaur/tags/items/reach_2_weapons"]
		enabled = true

	[origins."origins:frei/powers/fragile"]
		enabled = true

	[origins."origins:frei/powers/weapons"]
		enabled = true

	[origins."origins:centaur/tags/items/ed_bales"]
		enabled = true

	[origins."origins:berserk/origins/berserk"]
		enabled = true
		"berserk:melee_speed" = true
		"berserk:double_jump" = true
		"berserk:meat_eater" = true
		"berserk:vampire" = true
		"berserk:glass_cannon" = true
		"berserk:dash" = true
		"berserk:survive_death" = true

	[origins."origins:dodo/powers/bird_diet"]
		enabled = true

	[origins."origins:dodo/powers/weak_melee"]
		enabled = true

	[origins."origins:frei/powers/tall"]
		enabled = true

	[origins."origins:centaur/powers/robust"]
		enabled = true

