
[siege_machines]
	fireDamageMultiplier = 3.0
	explosionDamageMultiplier = 2.0
	arrowDamageMultiplier = 0.5
	allowFriendlyFire = false
	deploymentSicknessCooldown = 300
	preventPickupCooldown = 300

	[siege_machines.mortar]
		#Range: > 0
		durability = 80
		#Range: > 0
		reloadTime = 200
		#Range: 0.0 ~ 2.147483647E9
		projectileSpeed = 2.5
		#Range: 0.0 ~ 2.147483647E9
		inaccuracy = 0.20000000298023224
		#Range: 0.0 ~ 1.0
		knockbackResistance = 0.5

	[siege_machines.culverin]
		#Range: > 0
		durability = 150
		#Range: > 0
		reloadTime = 260
		#Range: 0.0 ~ 2.147483647E9
		projectileSpeed = 3.5
		#Range: 0.0 ~ 2.147483647E9
		inaccuracy = 0.029999999329447746
		#Range: 0.0 ~ 1.0
		knockbackResistance = 0.6000000238418579

	[siege_machines.trebuchet]
		#Range: > 0
		durability = 350
		#Range: > 0
		reloadTime = 400
		#Range: 0.0 ~ 2.147483647E9
		projectileSpeed = 2.799999952316284
		#Range: 0.0 ~ 2.147483647E9
		inaccuracy = 0.20000000298023224
		#Range: 0.0 ~ 1.0
		knockbackResistance = 1.0

	[siege_machines.catapult]
		#Range: > 0
		durability = 150
		#Range: > 0
		reloadTime = 200
		#Range: 0.0 ~ 2.147483647E9
		projectileSpeed = 2.0
		#Range: 0.0 ~ 2.147483647E9
		inaccuracy = 0.20000000298023224
		#Range: 0.0 ~ 1.0
		knockbackResistance = 0.800000011920929

	[siege_machines.ballista]
		#Range: > 0
		durability = 70
		#Range: > 0
		reloadTime = 120
		#Range: 0.0 ~ 2.147483647E9
		projectileSpeed = 4.5
		#Range: 0.0 ~ 2.147483647E9
		inaccuracy = 0.03999999910593033
		#Range: 0.0 ~ 1.0
		knockbackResistance = 0.4000000059604645

	[siege_machines.battering_ram]
		#Range: > 0
		durability = 500
		#Range: > 0
		reloadTime = 100
		#Range: 0.0 ~ 2.147483647E9
		projectileSpeed = 0.0
		#Range: 0.0 ~ 2.147483647E9
		inaccuracy = 0.5
		#Range: 0.0 ~ 1.0
		knockbackResistance = 1.0

	[siege_machines.siege_ladder]
		#Range: > 0
		durability = 400
		#Range: > 0
		reloadTime = 0
		#Range: 0.0 ~ 2.147483647E9
		projectileSpeed = 0.0
		#Range: 0.0 ~ 2.147483647E9
		inaccuracy = 0.0
		#Range: 0.0 ~ 1.0
		knockbackResistance = 1.0

[missiles]

	[missiles.cannonball]
		#Range: 0.0 ~ 1.7976931348623157E308
		mass = 15.0
		#Range: 0.0 ~ 1.7976931348623157E308
		explosionRadius = 3.0
		#Range: 0.0 ~ 1.0
		armorPiercing = 1.0
		#Range: 0.0 ~ 1.7976931348623157E308
		knockback = 1.5
		#Range: 0.0 ~ 3.4028234663852886E38
		explosionDamageMultiplier = 1.5
		explosive = true
		fired = false

	[missiles.stone]
		#Range: 0.0 ~ 1.7976931348623157E308
		mass = 50.0
		#Range: 0.0 ~ 1.7976931348623157E308
		explosionRadius = 2.5
		#Range: 0.0 ~ 1.0
		armorPiercing = 1.0
		#Range: 0.0 ~ 1.7976931348623157E308
		knockback = 1.5
		#Range: 0.0 ~ 3.4028234663852886E38
		explosionDamageMultiplier = 1.8
		explosive = true
		fired = false

	[missiles.giant_stone]
		#Range: 0.0 ~ 1.7976931348623157E308
		mass = 70.0
		#Range: 0.0 ~ 1.7976931348623157E308
		explosionRadius = 5.0
		#Range: 0.0 ~ 1.0
		armorPiercing = 1.0
		#Range: 0.0 ~ 1.7976931348623157E308
		knockback = 3.0
		#Range: 0.0 ~ 3.4028234663852886E38
		explosionDamageMultiplier = 3.0
		explosive = true
		fired = false

