ServerEvents.recipes(event => {
    // Controller
    event.shaped("gtceu:industrial_fishery", [
        "AAA",
        "BCB",
        "DBD"
    ],{
        A: "gtceu:hv_hermetic_casing",
        B: "gtceu:double_blue_steel_plate",
        C: "gtceu:hv_fisher",
        D: "#gtceu:circuits/ev"
    })

    // Fish catching (w/ different baits - string, fishing line, worm)
    // Atlantic
    event.recipes.gtceu.industrial_fishery("atlantic_fish_string_meat")
        .chancedInput("6x minecraft:string", 9500, 0)
        .itemInputs("4x gtceu:meat_dust")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(1)
        .itemOutputsRanged("aquaculture:atlantic_cod", 0, 6)
        .itemOutputsRanged("aquaculture:atlantic_halibut", 0, 6)
        .itemOutputsRanged("aquaculture:atlantic_herring", 0, 6)
        .itemOutputsRanged("minecraft:salmon", 0, 6)
        .itemOutputsRanged("aquaculture:pollock", 0, 6)
        .itemOutputsRanged("aquaculture:tuna", 0, 6)
    event.recipes.gtceu.industrial_fishery("atlantic_fish_string_worm")
        .chancedInput("6x minecraft:string", 9500, 0)
        .itemInputs("4x aquaculture:worm")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(1)
        .itemOutputsRanged("aquaculture:atlantic_cod", 3, 9)
        .itemOutputsRanged("aquaculture:atlantic_halibut", 3, 9)
        .itemOutputsRanged("aquaculture:atlantic_herring", 3, 9)
        .itemOutputsRanged("minecraft:salmon", 3, 9)
        .itemOutputsRanged("aquaculture:pollock", 3, 9)
        .itemOutputsRanged("aquaculture:tuna", 3, 9)

    event.recipes.gtceu.industrial_fishery("atlantic_fish_line_meat")
        .chancedInput("6x aquaculture:fishing_line", 3500, 0)
        .itemInputs("4x gtceu:meat_dust")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(1)
        .itemOutputsRanged("aquaculture:atlantic_cod", 0, 6)
        .itemOutputsRanged("aquaculture:atlantic_halibut", 0, 6)
        .itemOutputsRanged("aquaculture:atlantic_herring", 0, 6)
        .itemOutputsRanged("minecraft:salmon", 0, 6)
        .itemOutputsRanged("aquaculture:pollock", 0, 6)
        .itemOutputsRanged("aquaculture:tuna", 0, 6)
    event.recipes.gtceu.industrial_fishery("atlantic_fish_line_worm")
        .chancedInput("6x aquaculture:fishing_line", 3500, 0)
        .itemInputs("4x aquaculture:worm")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(1)
        .itemOutputsRanged("aquaculture:atlantic_cod", 3, 9)
        .itemOutputsRanged("aquaculture:atlantic_halibut", 3, 9)
        .itemOutputsRanged("aquaculture:atlantic_herring", 3, 9)
        .itemOutputsRanged("minecraft:salmon", 3, 9)
        .itemOutputsRanged("aquaculture:pollock", 3, 9)
        .itemOutputsRanged("aquaculture:tuna", 3, 9)

    // Tropical
    event.recipes.gtceu.industrial_fishery("tropical_fish_string_meat")
        .chancedInput("6x minecraft:string", 9500, 0)
        .itemInputs("4x gtceu:meat_dust")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(2)
        .itemOutputsRanged("aquaculture:arapaima", 0, 6)
        .itemOutputsRanged("aquaculture:piranha", 0, 6)
        .itemOutputsRanged("minecraft:tropical_fish", 0, 6)
        .itemOutputsRanged("minecraft:pufferfish", 0, 6)
        .itemOutputsRanged("aquaculture:catfish", 0, 6)
        .itemOutputsRanged("aquaculture:tambaqui", 0, 6)
    event.recipes.gtceu.industrial_fishery("tropical_fish_string_worm")
        .chancedInput("6x minecraft:string", 9500, 0)
        .itemInputs("4x aquaculture:worm")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(2)
        .itemOutputsRanged("aquaculture:arapaima", 3, 9)
        .itemOutputsRanged("aquaculture:piranha", 3, 9)
        .itemOutputsRanged("minecraft:tropical_fish", 3, 9)
        .itemOutputsRanged("minecraft:pufferfish", 3, 9)
        .itemOutputsRanged("aquaculture:catfish", 3, 9)
        .itemOutputsRanged("aquaculture:tambaqui", 3, 9)

    event.recipes.gtceu.industrial_fishery("tropical_fish_line_meat")
        .chancedInput("6x aquaculture:fishing_line", 3500, 0)
        .itemInputs("4x gtceu:meat_dust")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(2)
        .itemOutputsRanged("aquaculture:arapaima", 0, 6)
        .itemOutputsRanged("aquaculture:piranha", 0, 6)
        .itemOutputsRanged("minecraft:tropical_fish", 0, 6)
        .itemOutputsRanged("minecraft:pufferfish", 0, 6)
        .itemOutputsRanged("aquaculture:catfish", 0, 6)
        .itemOutputsRanged("aquaculture:tambaqui", 0, 6)
    event.recipes.gtceu.industrial_fishery("tropical_fish_line_worm")
        .chancedInput("6x aquaculture:fishing_line", 3500, 0)
        .itemInputs("4x aquaculture:worm")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(2)
        .itemOutputsRanged("aquaculture:arapaima", 3, 9)
        .itemOutputsRanged("aquaculture:piranha", 3, 9)
        .itemOutputsRanged("minecraft:tropical_fish", 3, 9)
        .itemOutputsRanged("minecraft:pufferfish", 3, 9)
        .itemOutputsRanged("aquaculture:catfish", 3, 9)
        .itemOutputsRanged("aquaculture:tambaqui", 3, 9)

    // Pacific
    event.recipes.gtceu.industrial_fishery("pacific_fish_string_meat")
        .chancedInput("6x minecraft:string", 9500, 0)
        .itemInputs("4x gtceu:meat_dust")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(3)
        .itemOutputsRanged("aquaculture:pacific_halibut", 0, 6)
        .itemOutputsRanged("minecraft:cod", 0, 6)
        .itemOutputsRanged("aquaculture:pink_salmon", 0, 6)
        .itemOutputsRanged("aquaculture:rainbow_trout", 0, 6)
        .itemOutputsRanged("oceanic_delight:squid_tentacles", 0, 6)
        .itemOutputsRanged("oceanic_delight:glow_squid_tentacles", 0, 6)
    event.recipes.gtceu.industrial_fishery("pacific_fish_string_worm")
        .chancedInput("6x minecraft:string", 9500, 0)
        .itemInputs("4x aquaculture:worm")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(3)
        .itemOutputsRanged("aquaculture:pacific_halibut", 3, 9)
        .itemOutputsRanged("minecraft:cod", 3, 9)
        .itemOutputsRanged("aquaculture:pink_salmon", 3, 9)
        .itemOutputsRanged("aquaculture:rainbow_trout", 3, 9)
        .itemOutputsRanged("oceanic_delight:squid_tentacles", 3, 9)
        .itemOutputsRanged("oceanic_delight:glow_squid_tentacles", 3, 9)

    event.recipes.gtceu.industrial_fishery("pacific_fish_line_meat")
        .chancedInput("6x aquaculture:fishing_line", 3500, 0)
        .itemInputs("4x gtceu:meat_dust")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(3)
        .itemOutputsRanged("aquaculture:pacific_halibut", 0, 6)
        .itemOutputsRanged("minecraft:cod", 0, 6)
        .itemOutputsRanged("aquaculture:pink_salmon", 0, 6)
        .itemOutputsRanged("aquaculture:rainbow_trout", 0, 6)
        .itemOutputsRanged("oceanic_delight:squid_tentacles", 0, 6)
        .itemOutputsRanged("oceanic_delight:glow_squid_tentacles", 0, 6)
    event.recipes.gtceu.industrial_fishery("pacific_fish_line_worm")
        .chancedInput("6x aquaculture:fishing_line", 3500, 0)
        .itemInputs("4x aquaculture:worm")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(3)
        .itemOutputsRanged("aquaculture:pacific_halibut", 3, 9)
        .itemOutputsRanged("minecraft:cod", 3, 9)
        .itemOutputsRanged("aquaculture:pink_salmon", 3, 9)
        .itemOutputsRanged("aquaculture:rainbow_trout", 3, 9)
        .itemOutputsRanged("oceanic_delight:squid_tentacles", 3, 9)
        .itemOutputsRanged("oceanic_delight:glow_squid_tentacles", 3, 9)

    // African River
    event.recipes.gtceu.industrial_fishery("african_river_fish_string_meat")
        .chancedInput("6x minecraft:string", 9500, 0)
        .itemInputs("4x gtceu:meat_dust")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(4)
        .itemOutputsRanged("aquaculture:blackfish", 0, 6)
        .itemOutputsRanged("aquaculture:bayad", 0, 6)
        .itemOutputsRanged("aquaculture:boulti", 0, 6)
        .itemOutputsRanged("aquaculture:synodontis", 0, 6)
        .itemOutputsRanged("aquaculture:capitaine", 0, 6)
        .itemOutputsRanged("aquaculture:minnow", 0, 6)
    event.recipes.gtceu.industrial_fishery("african_river_fish_string_worm")
        .chancedInput("6x minecraft:string", 9500, 0)
        .itemInputs("4x aquaculture:worm")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(4)
        .itemOutputsRanged("aquaculture:blackfish", 0, 6)
        .itemOutputsRanged("aquaculture:bayad", 0, 6)
        .itemOutputsRanged("aquaculture:boulti", 0, 6)
        .itemOutputsRanged("aquaculture:synodontis", 0, 6)
        .itemOutputsRanged("aquaculture:capitaine", 0, 6)
        .itemOutputsRanged("aquaculture:minnow", 0, 6)

    event.recipes.gtceu.industrial_fishery("african_river_fish_line_meat")
        .chancedInput("6x aquaculture:fishing_line", 3500, 0)
        .itemInputs("4x gtceu:meat_dust")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(4)
        .itemOutputsRanged("aquaculture:blackfish", 0, 6)
        .itemOutputsRanged("aquaculture:bayad", 0, 6)
        .itemOutputsRanged("aquaculture:boulti", 0, 6)
        .itemOutputsRanged("aquaculture:synodontis", 0, 6)
        .itemOutputsRanged("aquaculture:capitaine", 0, 6)
        .itemOutputsRanged("aquaculture:minnow", 0, 6)
    event.recipes.gtceu.industrial_fishery("african_river_fish_line_worm")
        .chancedInput("6x aquaculture:fishing_line", 3500, 0)
        .itemInputs("4x aquaculture:worm")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(4)
        .itemOutputsRanged("aquaculture:blackfish", 0, 6)
        .itemOutputsRanged("aquaculture:bayad", 0, 6)
        .itemOutputsRanged("aquaculture:boulti", 0, 6)
        .itemOutputsRanged("aquaculture:synodontis", 0, 6)
        .itemOutputsRanged("aquaculture:capitaine", 0, 6)
        .itemOutputsRanged("aquaculture:minnow", 0, 6)

    // American River
    event.recipes.gtceu.industrial_fishery("american_river_fish_string_meat")
        .chancedInput("6x minecraft:string", 9500, 0)
        .itemInputs("4x gtceu:meat_dust")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(5)
        .itemOutputsRanged("aquaculture:smallmouth_bass", 0, 6)
        .itemOutputsRanged("aquaculture:bluegill", 0, 6)
        .itemOutputsRanged("aquaculture:gar", 0, 6)
        .itemOutputsRanged("aquaculture:minnow", 0, 6)
        .itemOutputsRanged("aquaculture:muskellunge", 0, 6)
        .itemOutputsRanged("aquaculture:perch", 0, 6)
    event.recipes.gtceu.industrial_fishery("american_river_fish_string_worm")
        .chancedInput("6x minecraft:string", 9500, 0)
        .itemInputs("4x aquaculture:worm")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(5)
        .itemOutputsRanged("aquaculture:smallmouth_bass", 0, 6)
        .itemOutputsRanged("aquaculture:bluegill", 0, 6)
        .itemOutputsRanged("aquaculture:gar", 0, 6)
        .itemOutputsRanged("aquaculture:minnow", 0, 6)
        .itemOutputsRanged("aquaculture:muskellunge", 0, 6)
        .itemOutputsRanged("aquaculture:perch", 0, 6)

    event.recipes.gtceu.industrial_fishery("american_river_fish_line_meat")
        .chancedInput("6x aquaculture:fishing_line", 3500, 0)
        .itemInputs("4x gtceu:meat_dust")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(5)
        .itemOutputsRanged("aquaculture:smallmouth_bass", 0, 6)
        .itemOutputsRanged("aquaculture:bluegill", 0, 6)
        .itemOutputsRanged("aquaculture:gar", 0, 6)
        .itemOutputsRanged("aquaculture:minnow", 0, 6)
        .itemOutputsRanged("aquaculture:muskellunge", 0, 6)
        .itemOutputsRanged("aquaculture:perch", 0, 6)
    event.recipes.gtceu.industrial_fishery("american_river_fish_line_worm")
        .chancedInput("6x aquaculture:fishing_line", 3500, 0)
        .itemInputs("4x aquaculture:worm")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(5)
        .itemOutputsRanged("aquaculture:smallmouth_bass", 0, 6)
        .itemOutputsRanged("aquaculture:bluegill", 0, 6)
        .itemOutputsRanged("aquaculture:gar", 0, 6)
        .itemOutputsRanged("aquaculture:minnow", 0, 6)
        .itemOutputsRanged("aquaculture:muskellunge", 0, 6)
        .itemOutputsRanged("aquaculture:perch", 0, 6)

    // Mushroom
    // Brown Shrooma, Red Shrooma, Red Grouper, Brown Trout, Red Mushroom Colony, Brown Mushroom Colony
    event.recipes.gtceu.industrial_fishery("mushroom_island_fish_string_meat")
        .chancedInput("6x minecraft:string", 9500, 0)
        .itemInputs("4x gtceu:meat_dust")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(6)
        .itemOutputsRanged("aquaculture:brown_shrooma", 0, 6)
        .itemOutputsRanged("aquaculture:red_shrooma", 0, 6)
        .itemOutputsRanged("aquaculture:brown_trout", 0, 6)
        .itemOutputsRanged("aquaculture:red_grouper", 0, 6)
        .itemOutputsRanged("farmersdelight:red_mushroom_colony", 0, 4)
        .itemOutputsRanged("farmersdelight:brown_mushroom_colony", 0, 4)
    event.recipes.gtceu.industrial_fishery("mushroom_island_fish_string_worm")
        .chancedInput("6x minecraft:string", 9500, 0)
        .itemInputs("4x aquaculture:worm")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(6)
        .itemOutputsRanged("aquaculture:brown_shrooma", 0, 6)
        .itemOutputsRanged("aquaculture:red_shrooma", 0, 6)
        .itemOutputsRanged("aquaculture:brown_trout", 0, 6)
        .itemOutputsRanged("aquaculture:red_grouper", 0, 6)
        .itemOutputsRanged("farmersdelight:red_mushroom_colony", 0, 4)
        .itemOutputsRanged("farmersdelight:brown_mushroom_colony", 0, 4)

    event.recipes.gtceu.industrial_fishery("mushroom_island_fish_line_meat")
        .chancedInput("6x aquaculture:fishing_line", 3500, 0)
        .itemInputs("4x gtceu:meat_dust")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(6)
        .itemOutputsRanged("aquaculture:brown_shrooma", 0, 6)
        .itemOutputsRanged("aquaculture:red_shrooma", 0, 6)
        .itemOutputsRanged("aquaculture:brown_trout", 0, 6)
        .itemOutputsRanged("aquaculture:red_grouper", 0, 6)
        .itemOutputsRanged("farmersdelight:red_mushroom_colony", 0, 4)
        .itemOutputsRanged("farmersdelight:brown_mushroom_colony", 0, 4)
    event.recipes.gtceu.industrial_fishery("mushroom_island_fish_line_worm")
        .chancedInput("6x aquaculture:fishing_line", 3500, 0)
        .itemInputs("4x aquaculture:worm")
        .EUt(GTValues.VHA[GTValues.MV])
        .duration(2400)
        .circuit(6)
        .itemOutputsRanged("aquaculture:brown_shrooma", 0, 6)
        .itemOutputsRanged("aquaculture:red_shrooma", 0, 6)
        .itemOutputsRanged("aquaculture:brown_trout", 0, 6)
        .itemOutputsRanged("aquaculture:red_grouper", 0, 6)
        .itemOutputsRanged("farmersdelight:red_mushroom_colony", 0, 4)
        .itemOutputsRanged("farmersdelight:brown_mushroom_colony", 0, 4)
})