ServerEvents.recipes(event => {
    // Controller recipe
    // TODO:

    // Feedstock recipes
    event.recipes.gtceu.chemical_reactor("silica_gem_feedstock")
        .itemInputs("4x gtceu:silicon_dioxide_dust")
        .inputFluids("gtceu:distilled_water 1000")
        .outputFluids("gtceu:silica_gem_stock 1000")
        .duration(200)
        .EUt(GTValues.VHA[GTValues.EV])

    event.recipes.gtceu.chemical_reactor("corundum_gem_feedstock")
        .itemInputs("4x gtceu:bauxite_dust")
        .inputFluids("gtceu:distilled_water 1000")
        .outputFluids("gtceu:corundum_gem_stock 1000")
        .duration(200)
        .EUt(GTValues.VHA[GTValues.EV])

    event.recipes.gtceu.large_chemical_reactor("beryl_gem_feedstock")
        .itemInputs("2x gtceu:silicon_dust", "2x gtceu:aluminium_dust", "2x gtceu:beryllium_oxide_dust")
        .inputFluids("gtceu:distilled_water 1000")
        .outputFluids("gtceu:beryl_gem_stock 1000")
        .duration(200)
        .EUt(GTValues.VHA[GTValues.EV])

    event.recipes.gtceu.large_chemical_reactor("garnet_gem_feedstock")
        .itemInputs("2x gtceu:silicon_dust", "2x gtceu:calcium_dust", "2x gtceu:iron_dust")
        .inputFluids("gtceu:distilled_water 1000")
        .outputFluids("gtceu:garnet_gem_stock 1000")
        .duration(200)
        .EUt(GTValues.VHA[GTValues.EV])

    event.recipes.gtceu.large_chemical_reactor("sodalite_gem_feedstock")
        .itemInputs("2x gtceu:aluminium_dust", "2x gtceu:silicon_dust", "3x gtceu:sodium_dust")
        .inputFluids("gtceu:distilled_water 1000")
        .outputFluids("gtceu:sodalite_gem_stock 1000")
        .duration(200)
        .EUt(GTValues.VHA[GTValues.EV])

    event.recipes.gtceu.chemical_reactor("phosphate_gem_feedstock")
        .itemInputs("2x gtceu:phosphate_dust")
        .inputFluids("gtceu:distilled_water 750", "gtceu:phosphoric_acid 250")
        .outputFluids("gtceu:phosphate_gem_stock 1000")
        .duration(200)
        .EUt(GTValues.VHA[GTValues.EV])

    // Tiberium line
    event.recipes.gtceu.neutron_chamber("tiberium_seed_creation")
        .chancedInput("6x kubejs:neutron_emitter", 3000, 0)
        .chancedInput("1x kubejs:quasi_stable_neutron_star", 500, 0)
        .itemInputs("4x gtceu:praseodymium_oxide_dust")
        .itemOutputs("1x gtceu:tiberium_seed_dust")
        .outputFluids("gtceu:oxygen_plasma 2000")
        .duration(480)
        .EUt(GTValues.VHA[GTValues.UEV])

    event.recipes.gtceu.gem_growing_vat("tiberium_seed_growth")
        .itemInputs("1x gtceu:tiberium_seed_dust", "12x gtceu:tricalcium_phosphate_dust", "8x gtceu:amethyst_dust")
        .inputFluids("gtceu:silica_gem_stock 3000", "gtceu:krypton 2000")
        .itemOutputs("1x gtceu:raw_tiberium_gem")
        .chancedOutput("1x gtceu:raw_tiberium_gem", 6000, 0)
        .chancedOutput("1x gtceu:raw_tiberium_gem", 3000, 0)
        .chancedOutput("1x gtceu:raw_tiberium_gem", 1000, 0)
        .duration(1200)
        .EUt(GTValues.VHA[GTValues.UV])

    event.recipes.gtceu.discharger('tiberium_purification_basic')
            .itemInputs("1x gtceu:raw_tiberium_gem", "1x monilabs:small_eltz_dust", Item.of("kubejs:hadal_energy_core", "{Damage:8000000}").weakNBT(), Item.of("kubejs:hadal_energy_core", "{Damage:8000000}").weakNBT())
            .itemOutputs(Item.of("kubejs:hadal_energy_core", "{Damage:0}").weakNBT(), Item.of("kubejs:hadal_energy_core", "{Damage:0}").weakNBT())
            .chancedOutput("gtceu:tiberium_dust", 4500, 0)
            .chancedOutput("gtceu:phosphophyllite_gem", 5500, 0)
            .chancedItemOutputLogic(ChanceLogic.XOR)
            .duration(10)
    event.recipes.gtceu.discharger('tiberium_purification_flawless')
            .itemInputs("1x gtceu:flawless_raw_tiberium_gem", "1x monilabs:small_eltz_dust", Item.of("kubejs:hadal_energy_core", "{Damage:8000000}").weakNBT(), Item.of("kubejs:hadal_energy_core", "{Damage:8000000}").weakNBT())
            .itemOutputs(Item.of("kubejs:hadal_energy_core", "{Damage:0}").weakNBT(), Item.of("kubejs:hadal_energy_core", "{Damage:0}").weakNBT())
            .chancedOutput("gtceu:tiberium_dust", 8000, 0)
            .chancedOutput("gtceu:flawless_phosphophyllite_gem", 2000, 0)
            .chancedItemOutputLogic(ChanceLogic.XOR)
            .duration(10)
    event.recipes.gtceu.discharger('tiberium_purification_exquisite')
            .itemInputs("1x gtceu:exquisite_raw_tiberium_gem", "1x monilabs:small_eltz_dust", Item.of("kubejs:hadal_energy_core", "{Damage:8000000}").weakNBT(), Item.of("kubejs:hadal_energy_core", "{Damage:8000000}").weakNBT())
            .itemOutputs(Item.of("kubejs:hadal_energy_core", "{Damage:0}").weakNBT(), Item.of("kubejs:hadal_energy_core", "{Damage:0}").weakNBT())
            .chancedOutput("gtceu:tiberium_dust", 9900, 0)
            .chancedOutput("gtceu:exquisite_phosphophyllite_gem", 100, 0)
            .chancedItemOutputLogic(ChanceLogic.XOR)
            .duration(10)
    
    /////// Generic gems
    //// Beryls
    // Emerald
    event.recipes.gtceu.gem_growing_vat("emerald_growing")
        .itemInputs("2x gtceu:silicon_dioxide_dust", "1x gtceu:small_vanadium_dust", "1x gtceu:small_chromium_dust")
        .inputFluids("gtceu:beryl_gem_stock 1000")
        .chancedOutput("minecraft:emerald", 9500, 0)
        .chancedOutput("minecraft:emerald", 5000, 0)
        .chancedOutput("minecraft:emerald", 2000, 0)
        .chancedOutput("gtceu:flawless_emerald_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_emerald_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1600)
    // Pezzottaite
    event.recipes.gtceu.gem_growing_vat("pezzottaite_growing")
        .itemInputs("2x gtceu:silicon_dioxide_dust", "1x gtceu:small_caesium_dust", "1x gtceu:small_lithium_dust")
        .inputFluids("gtceu:beryl_gem_stock 1000")
        .chancedOutput("gtceu:pezzottaite_gem", 9500, 0)
        .chancedOutput("gtceu:pezzottaite_gem", 5000, 0)
        .chancedOutput("gtceu:pezzottaite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_pezzottaite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_pezzottaite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1600)
    // Milarite
    event.recipes.gtceu.gem_growing_vat("milarite_growing")
        .itemInputs("2x gtceu:silicon_dioxide_dust", "1x gtceu:small_iron_dust")
        .inputFluids("gtceu:beryl_gem_stock 1000", "gtceu:iron_iii_chloride 500")
        .chancedOutput("gtceu:milarite_gem", 9500, 0)
        .chancedOutput("gtceu:milarite_gem", 5000, 0)
        .chancedOutput("gtceu:milarite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_milarite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_milarite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1600)
    // Aquamarine
    event.recipes.gtceu.gem_growing_vat("aquamarine_growing")
        .itemInputs("2x gtceu:silicon_dioxide_dust", "1x gtceu:small_iron_dust")
        .inputFluids("gtceu:beryl_gem_stock 1000", "gtceu:iron_ii_chloride 500")
        .chancedOutput("gtceu:aquamarine_gem", 9500, 0)
        .chancedOutput("gtceu:aquamarine_gem", 5000, 0)
        .chancedOutput("gtceu:aquamarine_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_aquamarine_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_aquamarine_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1600)
    // Morganite
    event.recipes.gtceu.gem_growing_vat("morganite_growing")
        .itemInputs("2x gtceu:silicon_dioxide_dust", "1x gtceu:small_manganese_dust")
        .inputFluids("gtceu:beryl_gem_stock 1000")
        .chancedOutput("gtceu:morganite_gem", 9500, 0)
        .chancedOutput("gtceu:morganite_gem", 5000, 0)
        .chancedOutput("gtceu:morganite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_morganite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_morganite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1600)
    // Euclase
    event.recipes.gtceu.gem_growing_vat("euclase_growing")
        .itemInputs("2x gtceu:silicon_dioxide_dust")
        .inputFluids("gtceu:beryl_gem_stock 1000", "minecraft:water 500")
        .chancedOutput("gtceu:euclase_gem", 9500, 0)
        .chancedOutput("gtceu:euclase_gem", 5000, 0)
        .chancedOutput("gtceu:euclase_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_euclase_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_euclase_gem", 250, 0)
        .circuit(2)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1600)
    // Chrysoberyl
    event.recipes.gtceu.gem_growing_vat("chrysoberyl_growing")
        .itemInputs("1x gtceu:beryllium_dust")
        .inputFluids("gtceu:beryl_gem_stock 1000", "gtceu:iron_iii_chloride 500")
        .chancedOutput("gtceu:chrysoberyl_gem", 9500, 0)
        .chancedOutput("gtceu:chrysoberyl_gem", 5000, 0)
        .chancedOutput("gtceu:chrysoberyl_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_chrysoberyl_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_chrysoberyl_gem", 250, 0)
        .circuit(2)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1600)
    // Bazzite
    event.recipes.gtceu.gem_growing_vat("bazzite_growing")
        .itemInputs("2x gtceu:silicon_dioxide_dust", "3x gtceu:small_scandium_dust")
        .inputFluids("gtceu:beryl_gem_stock 1000")
        .chancedOutput("gtceu:bazzite_gem", 9500, 0)
        .chancedOutput("gtceu:bazzite_gem", 5000, 0)
        .chancedOutput("gtceu:bazzite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_bazzite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_bazzite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1600)
    // Musgravite
    event.recipes.gtceu.gem_growing_vat("musgravite_growing")
        .itemInputs("2x gtceu:silicon_dioxide_dust", "1x gtceu:small_magnesium_dust", "1x gtceu:small_zinc_dust")
        .inputFluids("gtceu:beryl_gem_stock 1000")
        .chancedOutput("gtceu:musgravite_gem", 9500, 0)
        .chancedOutput("gtceu:musgravite_gem", 5000, 0)
        .chancedOutput("gtceu:musgravite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_musgravite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_musgravite_gem", 250, 0)
        .circuit(2)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1600)
    // Taaffeite
    event.recipes.gtceu.gem_growing_vat("taaffeite_growing")
        .itemInputs("2x gtceu:silicon_dioxide_dust", "2x gtceu:small_magnesium_dust")
        .inputFluids("gtceu:beryl_gem_stock 1000")
        .chancedOutput("gtceu:taaffeite_gem", 9500, 0)
        .chancedOutput("gtceu:taaffeite_gem", 5000, 0)
        .chancedOutput("gtceu:taaffeite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_taaffeite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_taaffeite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1600)
    // Red Beryl
    event.recipes.gtceu.gem_growing_vat("red_beryl_growing")
        .itemInputs("2x gtceu:silicon_dioxide_dust", "1x gtceu:small_manganese_dust")
        .inputFluids("gtceu:beryl_gem_stock 1000")
        .chancedOutput("gtceu:red_beryl_gem", 9500, 0)
        .chancedOutput("gtceu:red_beryl_gem", 5000, 0)
        .chancedOutput("gtceu:red_beryl_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_red_beryl_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_red_beryl_gem", 250, 0)
        .circuit(2)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1600)
    //// Silicates
    // Nether quartz
    event.recipes.gtceu.gem_growing_vat("nether_quartz_growing")
        .itemInputs("1x gtceu:glass_dust", "1x gtceu:small_sulfur_dust")
        .inputFluids("gtceu:silica_gem_stock 1000")
        .chancedOutput("minecraft:quartz", 9500, 0)
        .chancedOutput("minecraft:quartz", 5000, 0)
        .chancedOutput("minecraft:quartz", 2000, 0)
        .chancedOutput("gtceu:flawless_nether_quartz_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_nether_quartz_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1200)
    // Flint
    event.recipes.gtceu.gem_growing_vat("flint_growing")
        .itemInputs("1x gtceu:glass_dust", "1x gtceu:stone_dust")
        .inputFluids("gtceu:silica_gem_stock 1000")
        .chancedOutput("minecraft:flint", 9500, 0)
        .chancedOutput("minecraft:flint", 5000, 0)
        .chancedOutput("minecraft:flint", 2000, 0)
        .chancedOutput("minecraft:flint", 750, 0)
        .chancedOutput("minecraft:flint", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1200)
    // Amethyst
    event.recipes.gtceu.gem_growing_vat("amethyst_growing")
        .itemInputs("1x gtceu:glass_dust", "1x gtceu:small_iron_dust")
        .inputFluids("gtceu:silica_gem_stock 1000")
        .chancedOutput("minecraft:amethyst_shard", 9500, 0)
        .chancedOutput("minecraft:amethyst_shard", 5000, 0)
        .chancedOutput("minecraft:amethyst_shard", 2000, 0)
        .chancedOutput("gtceu:flawless_amethyst_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_amethyst_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1200)
    // Citrine
    event.recipes.gtceu.gem_growing_vat("citrine_growing")
        .itemInputs("1x gtceu:glass_dust", "1x gtceu:small_aluminium_dust")
        .inputFluids("gtceu:silica_gem_stock 1000")
        .chancedOutput("gtceu:citrine_gem", 9500, 0)
        .chancedOutput("gtceu:citrine_gem", 5000, 0)
        .chancedOutput("gtceu:citrine_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_citrine_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_citrine_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1200)
    // Quartzite
    event.recipes.gtceu.gem_growing_vat("quartzite_growing")
        .itemInputs("1x gtceu:glass_dust", "1x gtceu:small_nickel_dust")
        .inputFluids("gtceu:silica_gem_stock 1000")
        .chancedOutput("gtceu:quartzite_gem", 9500, 0)
        .chancedOutput("gtceu:quartzite_gem", 5000, 0)
        .chancedOutput("gtceu:quartzite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_quartzite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_quartzite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1200)
    // Certus Quartz
    event.recipes.gtceu.gem_growing_vat("certus_quartz_growing")
        .itemInputs("1x gtceu:glass_dust", "1x gtceu:small_boron_dust")
        .inputFluids("gtceu:silica_gem_stock 1000")
        .chancedOutput("ae2:certus_quartz_crystal", 9500, 0)
        .chancedOutput("ae2:certus_quartz_crystal", 5000, 0)
        .chancedOutput("ae2:certus_quartz_crystal", 2000, 0)
        .chancedOutput("gtceu:flawless_certus_quartz_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_certus_quartz_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1200)
    // Opal
    event.recipes.gtceu.gem_growing_vat("opal_growing")
        .itemInputs("1x gtceu:glass_dust")
        .inputFluids("gtceu:silica_gem_stock 1000", "minecraft:water 500")
        .chancedOutput("gtceu:opal_gem", 9500, 0)
        .chancedOutput("gtceu:opal_gem", 5000, 0)
        .chancedOutput("gtceu:opal_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_opal_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_opal_gem", 250, 0)
        .circuit(2)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1500)
    // Black Opal
    event.recipes.gtceu.gem_growing_vat("black_opal_growing")
        .itemInputs("1x gtceu:glass_dust")
        .inputFluids("gtceu:silica_gem_stock 1000", "minecraft:water 500")
        .chancedOutput("gtceu:black_opal_gem", 9500, 0)
        .chancedOutput("gtceu:black_opal_gem", 5000, 0)
        .chancedOutput("gtceu:black_opal_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_black_opal_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_black_opal_gem", 250, 0)
        .circuit(3)
        .EUt(GTValues.VHA[GTValues.UV])
        .duration(1700)
    //// Quasi-silicates
    // Zoisite
    event.recipes.gtceu.gem_growing_vat("zoisite_growing")
        .itemInputs("1x gtceu:silicon_dioxide_dust", "1x gtceu:small_calcium_dust", "1x gtceu:small_aluminium_dust")
        .inputFluids("gtceu:silica_gem_stock 1000", "minecraft:water 1000")
        .chancedOutput("gtceu:zoisite_gem", 9500, 0)
        .chancedOutput("gtceu:zoisite_gem", 5000, 0)
        .chancedOutput("gtceu:zoisite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_zoisite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_zoisite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1500)
    // Olivine
    event.recipes.gtceu.gem_growing_vat("olivine_growing")
        .itemInputs("1x gtceu:silicon_dioxide_dust", "1x gtceu:magnesium_dust", "1x gtceu:small_iron_dust")
        .inputFluids("gtceu:silica_gem_stock 1000")
        .chancedOutput("gtceu:olivine_gem", 9500, 0)
        .chancedOutput("gtceu:olivine_gem", 5000, 0)
        .chancedOutput("gtceu:olivine_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_olivine_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_olivine_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1500)
    // Ekanite
    event.recipes.gtceu.gem_growing_vat("ekanite_growing")
        .itemInputs("2x gtceu:silicon_dioxide_dust", "1x gtceu:calcium_dust", "1x gtceu:small_thorium_dust")
        .inputFluids("gtceu:silica_gem_stock 1000")
        .chancedOutput("gtceu:ekanite_gem", 9500, 0)
        .chancedOutput("gtceu:ekanite_gem", 5000, 0)
        .chancedOutput("gtceu:ekanite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_ekanite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_ekanite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1500)
    // Manganvesuvianite
    event.recipes.gtceu.gem_growing_vat("manganvesuvianite_growing")
        .itemInputs("4x gtceu:silicon_dioxide_dust", "1x gtceu:manganese_dust", "1x gtceu:iron_dust", "1x gtceu:magnesium_dust")
        .inputFluids("gtceu:silica_gem_stock 1000", "gtceu:garnet_gem_stock 1000", "minecraft:water 1000")
        .chancedOutput("gtceu:manganvesuvianite_gem", 9500, 0)
        .chancedOutput("gtceu:manganvesuvianite_gem", 5000, 0)
        .chancedOutput("gtceu:manganvesuvianite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_manganvesuvianite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_manganvesuvianite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1800)
    // Nambulite
    event.recipes.gtceu.gem_growing_vat("nambulite_growing")
        .itemInputs("1x gtceu:silicon_dioxide_dust", "1x gtceu:manganese_dust", "1x gtceu:small_lithium_dust", "1x gtceu:small_sodium_dust")
        .inputFluids("gtceu:silica_gem_stock 1000", "minecraft:water 500")
        .chancedOutput("gtceu:nambulite_gem", 9500, 0)
        .chancedOutput("gtceu:nambulite_gem", 5000, 0)
        .chancedOutput("gtceu:nambulite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_nambulite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_nambulite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1500)
    // Titanite
    event.recipes.gtceu.gem_growing_vat("titanite_growing")
        .itemInputs("1x gtceu:silicon_dioxide_dust", "1x gtceu:small_calcium_dust", "1x gtceu:small_titanium_dust")
        .inputFluids("gtceu:silica_gem_stock 1000")
        .chancedOutput("gtceu:titanite_gem", 9500, 0)
        .chancedOutput("gtceu:titanite_gem", 5000, 0)
        .chancedOutput("gtceu:titanite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_titanite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_titanite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1700)
    // Schizolite
    event.recipes.gtceu.gem_growing_vat("schizolite_growing")
        .itemInputs("1x gtceu:silicon_dioxide_dust", "1x gtceu:small_sodium_dust", "1x gtceu:small_calcium_dust", "1x gtceu:small_manganese_dust")
        .inputFluids("gtceu:silica_gem_stock 1000", "minecraft:water 500")
        .chancedOutput("gtceu:schizolite_gem", 9500, 0)
        .chancedOutput("gtceu:schizolite_gem", 5000, 0)
        .chancedOutput("gtceu:schizolite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_schizolite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_schizolite_gem", 250, 0)
        .circuit(2)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1500)
    // Zircon
    event.recipes.gtceu.gem_growing_vat("zircon_growing")
        .itemInputs("1x gtceu:silicon_dioxide_dust", "1x gtceu:small_zirconium_dust")
        .inputFluids("gtceu:silica_gem_stock 1000")
        .chancedOutput("gtceu:zircon_gem", 9500, 0)
        .chancedOutput("gtceu:zircon_gem", 5000, 0)
        .chancedOutput("gtceu:zircon_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_zircon_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_zircon_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1600)
    // Hexagonite
    event.recipes.gtceu.gem_growing_vat("hexagonite_growing")
        .itemInputs("2x gtceu:silicon_dioxide_dust", "1x gtceu:magnesium_dust", "1x gtceu:small_calcium_dust")
        .inputFluids("gtceu:silica_gem_stock 1000")
        .chancedOutput("gtceu:hexagonite_gem", 9500, 0)
        .chancedOutput("gtceu:hexagonite_gem", 5000, 0)
        .chancedOutput("gtceu:hexagonite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_hexagonite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_hexagonite_gem", 250, 0)
        .circuit(2)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1800)
    //// Corundums
    // Sapphire
    event.recipes.gtceu.gem_growing_vat("sapphire_growing")
        .itemInputs("1x gtceu:bauxite_dust", "1x gtceu:small_iron_dust", "1x gtceu:small_titanium_dust")
        .inputFluids("gtceu:corundum_gem_stock 1000")
        .chancedOutput("gtceu:sapphire_gem", 9500, 0)
        .chancedOutput("gtceu:sapphire_gem", 5000, 0)
        .chancedOutput("gtceu:sapphire_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_sapphire_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_sapphire_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1200)
    // Green Sapphire
    event.recipes.gtceu.gem_growing_vat("green_sapphire_growing")
        .itemInputs("1x gtceu:bauxite_dust", "2x gtceu:small_iron_dust")
        .inputFluids("gtceu:corundum_gem_stock 1000")
        .chancedOutput("gtceu:green_sapphire_gem", 9500, 0)
        .chancedOutput("gtceu:green_sapphire_gem", 5000, 0)
        .chancedOutput("gtceu:green_sapphire_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_green_sapphire_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_green_sapphire_gem", 250, 0)
        .circuit(2)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1200)
    // Spinel
    event.recipes.gtceu.gem_growing_vat("spinel_growing")
        .itemInputs("1x gtceu:bauxite_dust", "1x gtceu:small_chromium_dust", "1x gtceu:small_magnesium_dust", "1x gtceu:small_iron_dust")
        .inputFluids("gtceu:corundum_gem_stock 500", "gtceu:garnet_gem_stock 500")
        .chancedOutput("gtceu:spinel_gem", 9500, 0)
        .chancedOutput("gtceu:spinel_gem", 5000, 0)
        .chancedOutput("gtceu:spinel_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_spinel_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_spinel_gem", 250, 0)
        .circuit(3)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1200)
    // Ruby
    event.recipes.gtceu.gem_growing_vat("ruby_growing")
        .itemInputs("1x gtceu:bauxite_dust", "1x gtceu:small_chromium_dust")
        .inputFluids("gtceu:corundum_gem_stock 1000")
        .chancedOutput("gtceu:ruby_gem", 9500, 0)
        .chancedOutput("gtceu:ruby_gem", 5000, 0)
        .chancedOutput("gtceu:ruby_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_ruby_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_ruby_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1400)
    // Eltic Crystal
    event.recipes.gtceu.gem_growing_vat("eltic_growing")
        .itemInputs("1x gtceu:bauxite_dust", "1x monilabs:small_eltz_dust", "1x gtceu:small_certus_quartz_dust")
        .inputFluids("gtceu:corundum_gem_stock 1000")
        .chancedOutput("gtceu:impure_eltic_gem", 9500, 0)
        .chancedOutput("gtceu:impure_eltic_gem", 5000, 0)
        .chancedOutput("gtceu:impure_eltic_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_impure_eltic_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_impure_eltic_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1800)
    //// Garnets
    // Spessartine
    event.recipes.gtceu.gem_growing_vat("spessartine_growing")
        .itemInputs("1x gtceu:red_garnet_dust", "1x gtceu:small_manganese_dust", "1x gtceu:small_aluminium_dust")
        .inputFluids("gtceu:garnet_gem_stock 1000")
        .chancedOutput("gtceu:spessartine_gem", 9500, 0)
        .chancedOutput("gtceu:spessartine_gem", 5000, 0)
        .chancedOutput("gtceu:spessartine_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_spessartine_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_spessartine_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1100)
    // Almandine
    event.recipes.gtceu.gem_growing_vat("almandine_growing")
        .itemInputs("1x gtceu:red_garnet_dust", "1x gtceu:small_iron_dust", "1x gtceu:small_aluminium_dust")
        .inputFluids("gtceu:garnet_gem_stock 1000")
        .chancedOutput("gtceu:almandine_gem", 9500, 0)
        .chancedOutput("gtceu:almandine_gem", 5000, 0)
        .chancedOutput("gtceu:almandine_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_almandine_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_almandine_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1100)
    // Yellow Garnet
    event.recipes.gtceu.gem_growing_vat("yellow_garnet_growing")
        .itemInputs("1x gtceu:yellow_garnet_dust")
        .inputFluids("gtceu:garnet_gem_stock 1000")
        .chancedOutput("gtceu:yellow_garnet_gem", 9500, 0)
        .chancedOutput("gtceu:yellow_garnet_gem", 5000, 0)
        .chancedOutput("gtceu:yellow_garnet_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_yellow_garnet_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_yellow_garnet_gem", 250, 0)
        .circuit(2)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1100)
    // Red Garnet
    event.recipes.gtceu.gem_growing_vat("red_garnet_growing")
        .itemInputs("1x gtceu:red_garnet_dust")
        .inputFluids("gtceu:garnet_gem_stock 1000")
        .chancedOutput("gtceu:red_garnet_gem", 9500, 0)
        .chancedOutput("gtceu:red_garnet_gem", 5000, 0)
        .chancedOutput("gtceu:red_garnet_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_red_garnet_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_red_garnet_gem", 250, 0)
        .circuit(2)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1100)
    // Andradite
    event.recipes.gtceu.gem_growing_vat("andradite_growing")
        .itemInputs("1x gtceu:yellow_garnet_dust", "1x gtceu:small_calcium_dust", "1x gtceu:small_iron_dust")
        .inputFluids("gtceu:garnet_gem_stock 1000")
        .chancedOutput("gtceu:andradite_gem", 9500, 0)
        .chancedOutput("gtceu:andradite_gem", 5000, 0)
        .chancedOutput("gtceu:andradite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_andradite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_andradite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1100)
    // Uvarovite
    event.recipes.gtceu.gem_growing_vat("uvarovite_growing")
        .itemInputs("1x gtceu:yellow_garnet_dust", "1x gtceu:small_calcium_dust", "1x gtceu:small_chromium_dust")
        .inputFluids("gtceu:garnet_gem_stock 1000")
        .chancedOutput("gtceu:uvarovite_gem", 9500, 0)
        .chancedOutput("gtceu:uvarovite_gem", 5000, 0)
        .chancedOutput("gtceu:uvarovite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_uvarovite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_uvarovite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1100)
    // Grossular
    event.recipes.gtceu.gem_growing_vat("grossular_growing")
        .itemInputs("1x gtceu:yellow_garnet_dust", "1x gtceu:small_calcium_dust", "1x gtceu:small_aluminium_dust")
        .inputFluids("gtceu:garnet_gem_stock 1000")
        .chancedOutput("gtceu:grossular_gem", 9500, 0)
        .chancedOutput("gtceu:grossular_gem", 5000, 0)
        .chancedOutput("gtceu:grossular_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_grossular_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_grossular_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1100)
    // Pyrope
    event.recipes.gtceu.gem_growing_vat("pyrope_growing")
        .itemInputs("1x gtceu:red_garnet_dust", "1x gtceu:small_aluminium_dust", "1x gtceu:small_magnesium_dust")
        .inputFluids("gtceu:garnet_gem_stock 1000")
        .chancedOutput("gtceu:pyrope_gem", 9500, 0)
        .chancedOutput("gtceu:pyrope_gem", 5000, 0)
        .chancedOutput("gtceu:pyrope_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_pyrope_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_pyrope_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1100)
    // Rubellite
    event.recipes.gtceu.gem_growing_vat("rubellite_growing")
        .itemInputs("1x gtceu:red_garnet_dust", "1x gtceu:small_sodium_dust", "1x gtceu:small_aluminium_dust")
        .inputFluids("gtceu:garnet_gem_stock 500", "gtceu:silica_gem_stock 500", "minecraft:water 500")
        .chancedOutput("gtceu:rubellite_gem", 9500, 0)
        .chancedOutput("gtceu:rubellite_gem", 5000, 0)
        .chancedOutput("gtceu:rubellite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_rubellite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_rubellite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1300)
    // Anorthite
    event.recipes.gtceu.gem_growing_vat("anorthite_growing")
        .itemInputs("1x gtceu:yellow_garnet_dust")
        .inputFluids("gtceu:garnet_gem_stock 500", "gtceu:silica_gem_stock 500")
        .chancedOutput("gtceu:anorthite_gem", 9500, 0)
        .chancedOutput("gtceu:anorthite_gem", 5000, 0)
        .chancedOutput("gtceu:anorthite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_anorthite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_anorthite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1300)
    //// Sodalite-like
    // Sodalite
    event.recipes.gtceu.gem_growing_vat("sodalite_growing")
        .itemInputs("1x gtceu:sodium_dust")
        .inputFluids("gtceu:sodalite_gem_stock 1000", "gtceu:chlorine 500")
        .chancedOutput("gtceu:sodalite_gem", 9500, 0)
        .chancedOutput("gtceu:sodalite_gem", 5000, 0)
        .chancedOutput("gtceu:sodalite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_sodalite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_sodalite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1000)
    // Lazurite
    event.recipes.gtceu.gem_growing_vat("lazurite_growing")
        .itemInputs("1x gtceu:sodium_dust", "1x gtceu:calcium_dust")
        .inputFluids("gtceu:sodalite_gem_stock 1000")
        .chancedOutput("gtceu:lazurite_gem", 9500, 0)
        .chancedOutput("gtceu:lazurite_gem", 5000, 0)
        .chancedOutput("gtceu:lazurite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_lazurite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_lazurite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1000)
    // Lapis
    event.recipes.gtceu.gem_growing_vat("lapis_growing")
        .itemInputs("1x gtceu:sodium_dust", "1x gtceu:calcium_dust")
        .inputFluids("gtceu:sodalite_gem_stock 1000", "gtceu:chlorine 500")
        .chancedOutput("minecraft:lapis_lazuli", 9500, 0)
        .chancedOutput("minecraft:lapis_lazuli", 5000, 0)
        .chancedOutput("minecraft:lapis_lazuli", 2000, 0)
        .chancedOutput("gtceu:flawless_lapis_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_lapis_gem", 250, 0)
        .circuit(2)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1000)
    //// Arsenate hydride
    // Legrandite
    event.recipes.gtceu.gem_growing_vat("legrandite_growing")
        .itemInputs("1x gtceu:arsenic_trioxide_dust", "1x gtceu:small_zinc_dust")
        .inputFluids("minecraft:water 1500", "gtceu:arsenic 500")
        .chancedOutput("gtceu:legrandite_gem", 9500, 0)
        .chancedOutput("gtceu:legrandite_gem", 5000, 0)
        .chancedOutput("gtceu:legrandite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_legrandite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_legrandite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1800)
    // Mixite
    event.recipes.gtceu.gem_growing_vat("mixite_growing")
        .itemInputs("1x gtceu:arsenic_trioxide_dust", "1x gtceu:small_copper_dust", "1x gtceu:small_bismuth_dust")
        .inputFluids("minecraft:water 1500", "gtceu:arsenic 500")
        .chancedOutput("gtceu:mixite_gem", 9500, 0)
        .chancedOutput("gtceu:mixite_gem", 5000, 0)
        .chancedOutput("gtceu:mixite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_mixite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_mixite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1800)
    //// Vanadoxide
    // Cavansite
    event.recipes.gtceu.gem_growing_vat("cavansite_growing")
        .itemInputs("1x gtceu:vanadium_pentoxide_dust", "1x gtceu:small_calcium_dust") 
        .inputFluids("gtceu:silica_gem_stock 1000", "minecraft:water 1000")
        .chancedOutput("gtceu:cavansite_gem", 9500, 0)
        .chancedOutput("gtceu:cavansite_gem", 5000, 0)
        .chancedOutput("gtceu:cavansite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_cavansite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_cavansite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1600)
    // Vanadinite
    event.recipes.gtceu.gem_growing_vat("vanadinite_growing")
        .itemInputs("1x gtceu:vanadium_pentoxide_dust", "1x gtceu:lead_dust") 
        .inputFluids("gtceu:chlorine 1000")
        .chancedOutput("gtceu:vanadinite_gem", 9500, 0)
        .chancedOutput("gtceu:vanadinite_gem", 5000, 0)
        .chancedOutput("gtceu:vanadinite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_vanadinite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_vanadinite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1600)
    //// Borate
    // Ulexite
    event.recipes.gtceu.gem_growing_vat("ulexite_growing")
        .itemInputs("1x gtceu:borosilicate_glass_dust", "1x gtceu:small_sodium_dust", "1x gtceu:small_calcium_dust") 
        .inputFluids("minecraft:water 2000")
        .chancedOutput("gtceu:ulexite_gem", 9500, 0)
        .chancedOutput("gtceu:ulexite_gem", 5000, 0)
        .chancedOutput("gtceu:ulexite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_ulexite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_ulexite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1400)
    // Tusionite
    event.recipes.gtceu.gem_growing_vat("tusionite_growing")
        .itemInputs("1x gtceu:borosilicate_glass_dust", "1x gtceu:small_tin_dust", "1x gtceu:small_manganese_dust") 
        .inputFluids("gtceu:distilled_water 1000")
        .chancedOutput("gtceu:tusionite_gem", 9500, 0)
        .chancedOutput("gtceu:tusionite_gem", 5000, 0)
        .chancedOutput("gtceu:tusionite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_tusionite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_tusionite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1400)
    // Chambersite
    event.recipes.gtceu.gem_growing_vat("chambersite_growing")
        .itemInputs("1x gtceu:borosilicate_glass_dust", "1x gtceu:manganese_dioxide_dust") 
        .inputFluids("gtceu:chlorine 1000")
        .chancedOutput("gtceu:chambersite_gem", 9500, 0)
        .chancedOutput("gtceu:chambersite_gem", 5000, 0)
        .chancedOutput("gtceu:chambersite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_chambersite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_chambersite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1400)
    // Datolite
    event.recipes.gtceu.gem_growing_vat("datolite_growing")
        .itemInputs("1x gtceu:borosilicate_glass_dust", "1x gtceu:small_calcium_dust", "1x gtceu:small_silicon_dust") 
        .inputFluids("gtceu:distilled_water 1000")
        .chancedOutput("gtceu:datolite_gem", 9500, 0)
        .chancedOutput("gtceu:datolite_gem", 5000, 0)
        .chancedOutput("gtceu:datolite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_datolite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_datolite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1400)
    //// Phosphate
    // Herderite
    event.recipes.gtceu.gem_growing_vat("herderite_growing")
        .itemInputs("1x gtceu:phosphate_dust", "1x gtceu:small_calcium_dust", "1x gtceu:small_beryllium_dust") 
        .inputFluids("gtceu:phosphate_gem_stock 1000", "minecraft:water 250", "gtceu:fluorine 250")
        .chancedOutput("gtceu:herderite_gem", 9500, 0)
        .chancedOutput("gtceu:herderite_gem", 5000, 0)
        .chancedOutput("gtceu:herderite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_herderite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_herderite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1200)
    // Vivianite
    event.recipes.gtceu.gem_growing_vat("vivianite_growing")
        .itemInputs("1x gtceu:phosphate_dust", "2x gtceu:small_iron_dust", "1x gtceu:small_manganese_dust", "1x gtceu:small_magnesium_dust") 
        .inputFluids("gtceu:phosphate_gem_stock 1000", "minecraft:water 1500")
        .chancedOutput("gtceu:vivianite_gem", 9500, 0)
        .chancedOutput("gtceu:vivianite_gem", 5000, 0)
        .chancedOutput("gtceu:vivianite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_vivianite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_vivianite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1200)
    // Xenotime
    event.recipes.gtceu.gem_growing_vat("xenotime_growing")
        .itemInputs("1x gtceu:phosphate_dust", "1x gtceu:small_yttrium_dust", "1x gtceu:small_lanthanum_dust") 
        .inputFluids("gtceu:phosphate_gem_stock 1000")
        .chancedOutput("gtceu:xenotime_gem", 9500, 0)
        .chancedOutput("gtceu:xenotime_gem", 5000, 0)
        .chancedOutput("gtceu:xenotime_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_xenotime_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_xenotime_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1800)
    // Phosphosiderite
    event.recipes.gtceu.gem_growing_vat("phosphosiderite_growing")
        .itemInputs("1x gtceu:phosphate_dust", "1x gtceu:small_iron_dust") 
        .inputFluids("gtceu:phosphate_gem_stock 1000", "minecraft:water 500")
        .chancedOutput("gtceu:phosphosiderite_gem", 9500, 0)
        .chancedOutput("gtceu:phosphosiderite_gem", 5000, 0)
        .chancedOutput("gtceu:phosphosiderite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_phosphosiderite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_phosphosiderite_gem", 250, 0)
        .circuit(2)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1200)
    // Apatite
    event.recipes.gtceu.gem_growing_vat("apatite_growing")
        .itemInputs("1x gtceu:phosphate_dust", "1x gtceu:calcium_dust") 
        .inputFluids("gtceu:phosphate_gem_stock 1000", "gtceu:chlorine 500")
        .chancedOutput("gtceu:apatite_gem", 9500, 0)
        .chancedOutput("gtceu:apatite_gem", 5000, 0)
        .chancedOutput("gtceu:apatite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_apatite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_apatite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1000)
    // Triplite
    event.recipes.gtceu.gem_growing_vat("triplite_growing")
        .itemInputs("1x gtceu:phosphate_dust", "1x gtceu:small_iron_dust", "1x gtceu:small_manganese_dust") 
        .inputFluids("gtceu:phosphate_gem_stock 1000", "minecraft:water 250", "gtceu:fluorine 250")
        .chancedOutput("gtceu:triplite_gem", 9500, 0)
        .chancedOutput("gtceu:triplite_gem", 5000, 0)
        .chancedOutput("gtceu:triplite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_triplite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_triplite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1200)
    // Fluoroapatite
    event.recipes.gtceu.gem_growing_vat("fluoroapatite_growing")
        .itemInputs("1x gtceu:phosphate_dust", "1x gtceu:calcium_dust") 
        .inputFluids("gtceu:phosphate_gem_stock 1000", "gtceu:fluorine 500")
        .chancedOutput("gtceu:fluoroapatite_gem", 9500, 0)
        .chancedOutput("gtceu:fluoroapatite_gem", 5000, 0)
        .chancedOutput("gtceu:fluoroapatite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_fluoroapatite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_fluoroapatite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1000)
    // Triphyllite
    event.recipes.gtceu.gem_growing_vat("triphyllite_growing")
        .itemInputs("1x gtceu:phosphate_dust", "1x gtceu:small_iron_dust", "1x gtceu:small_lithium_dust") 
        .inputFluids("gtceu:phosphate_gem_stock 1000")
        .chancedOutput("gtceu:triphyllite_gem", 9500, 0)
        .chancedOutput("gtceu:triphyllite_gem", 5000, 0)
        .chancedOutput("gtceu:triphyllite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_triphyllite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_triphyllite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1200)
    // Torbernite
    event.recipes.gtceu.gem_growing_vat("torbernite_growing")
        .itemInputs("1x gtceu:phosphate_dust", "1x gtceu:small_copper_dust", "1x gtceu:small_uranium_dust") 
        .inputFluids("gtceu:phosphate_gem_stock 1000", "minecraft:water 2000")
        .chancedOutput("gtceu:torbernite_gem", 9500, 0)
        .chancedOutput("gtceu:torbernite_gem", 5000, 0)
        .chancedOutput("gtceu:torbernite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_torbernite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_torbernite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1600)
    // Turquoise
    event.recipes.gtceu.gem_growing_vat("turquoise_growing")
        .itemInputs("1x gtceu:phosphate_dust", "1x gtceu:small_copper_dust", "1x gtceu:aluminium_dust") 
        .inputFluids("gtceu:phosphate_gem_stock 1000", "minecraft:water 1500")
        .chancedOutput("gtceu:turquoise_gem", 9500, 0)
        .chancedOutput("gtceu:turquoise_gem", 5000, 0)
        .chancedOutput("gtceu:turquoise_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_turquoise_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_turquoise_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1400)
    // Monazite
    event.recipes.gtceu.gem_growing_vat("monazite_growing")
        .itemInputs("1x gtceu:phosphate_dust", "1x gtceu:small_cerium_dust", "1x gtceu:small_lanthanum_dust") 
        .inputFluids("gtceu:phosphate_gem_stock 1000")
        .chancedOutput("gtceu:monazite_gem", 9500, 0)
        .chancedOutput("gtceu:monazite_gem", 5000, 0)
        .chancedOutput("gtceu:monazite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_monazite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_monazite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1800)
    // Vayrynenite
    event.recipes.gtceu.gem_growing_vat("vayrynenite_growing")
        .itemInputs("1x gtceu:phosphate_dust", "1x gtceu:small_manganese_dust", "1x gtceu:small_beryllium_dust") 
        .inputFluids("gtceu:phosphate_gem_stock 1000", "minecraft:water 250", "gtceu:fluorine 250")
        .chancedOutput("gtceu:vayrynenite_gem", 9500, 0)
        .chancedOutput("gtceu:vayrynenite_gem", 5000, 0)
        .chancedOutput("gtceu:vayrynenite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_vayrynenite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_vayrynenite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1400)
    // Phosphophyllite
    event.recipes.gtceu.gem_growing_vat("phosphophyllite_growing")
        .itemInputs("1x gtceu:phosphate_dust", "1x gtceu:small_zinc_dust", "1x gtceu:small_iron_dust") 
        .inputFluids("gtceu:phosphate_gem_stock 1000", "minecraft:water 1000")
        .chancedOutput("gtceu:phosphophyllite_gem", 9500, 0)
        .chancedOutput("gtceu:phosphophyllite_gem", 5000, 0)
        .chancedOutput("gtceu:phosphophyllite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_phosphophyllite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_phosphophyllite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1200)
    //// Carbides
    // Diamond
    event.recipes.gtceu.gem_growing_vat("diamond_growing")
        .itemInputs("1x gtceu:carbon_dust") 
        .inputFluids("gtceu:carbon 1000")
        .chancedOutput("minecraft:diamond", 9500, 0)
        .chancedOutput("minecraft:diamond", 5000, 0)
        .chancedOutput("minecraft:diamond", 2000, 0)
        .chancedOutput("gtceu:flawless_diamond_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_diamond_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.UHV])
        .duration(3600)
    // Moissanite
    event.recipes.gtceu.gem_growing_vat("moissanite_growing")
        .itemInputs("1x gtceu:carbon_dust") 
        .inputFluids("gtceu:carbon 1000", "gtceu:silicon 1000")
        .chancedOutput("gtceu:moissanite_gem", 9500, 0)
        .chancedOutput("gtceu:moissanite_gem", 5000, 0)
        .chancedOutput("gtceu:moissanite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_moissanite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_moissanite_gem", 250, 0)
        .circuit(2)
        .EUt(GTValues.VHA[GTValues.UV])
        .duration(2400)
    //// Carbonate
    // Strontianite
    event.recipes.gtceu.gem_growing_vat("strontianite_growing")
        .itemInputs("1x gtceu:calcium_carbonate_dust", "1x gtceu:small_strontium_dust") 
        .inputFluids("minecraft:water 1000")
        .chancedOutput("gtceu:strontianite_gem", 9500, 0)
        .chancedOutput("gtceu:strontianite_gem", 5000, 0)
        .chancedOutput("gtceu:strontianite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_strontianite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_strontianite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(900)
    // Witherite
    event.recipes.gtceu.gem_growing_vat("witherite_growing")
        .itemInputs("1x gtceu:calcium_carbonate_dust", "1x gtceu:small_barium_dust") 
        .inputFluids("minecraft:water 1000")
        .chancedOutput("gtceu:witherite_gem", 9500, 0)
        .chancedOutput("gtceu:witherite_gem", 5000, 0)
        .chancedOutput("gtceu:witherite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_witherite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_witherite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(900)
    // Otavite
    event.recipes.gtceu.gem_growing_vat("otavite_growing")
        .itemInputs("1x gtceu:calcium_carbonate_dust", "1x gtceu:small_cadmium_dust") 
        .inputFluids("minecraft:water 1000")
        .chancedOutput("gtceu:otavite_gem", 9500, 0)
        .chancedOutput("gtceu:otavite_gem", 5000, 0)
        .chancedOutput("gtceu:otavite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_otavite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_otavite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(900)
    //// Titanium/Tungsten
    // Ferberite
    event.recipes.gtceu.gem_growing_vat("ferberite_growing")
        .itemInputs("1x gtceu:tungsten_trioxide_dust", "1x gtceu:small_iron_dust") 
        .inputFluids("gtceu:distilled_water 1000")
        .chancedOutput("gtceu:ferberite_gem", 9500, 0)
        .chancedOutput("gtceu:ferberite_gem", 5000, 0)
        .chancedOutput("gtceu:ferberite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_ferberite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_ferberite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.UV])
        .duration(1800)
    // Stolzite
    event.recipes.gtceu.gem_growing_vat("stolzite_growing")
        .itemInputs("1x gtceu:tungsten_trioxide_dust", "1x gtceu:small_lead_dust") 
        .inputFluids("gtceu:distilled_water 1000")
        .chancedOutput("gtceu:stolzite_gem", 9500, 0)
        .chancedOutput("gtceu:stolzite_gem", 5000, 0)
        .chancedOutput("gtceu:stolzite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_stolzite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_stolzite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.UV])
        .duration(1800)
    // Rutile
    event.recipes.gtceu.gem_growing_vat("rutile_growing")
        .itemInputs("1x gtceu:titanium_suboxide_dust", "1x gtceu:small_titanium_dust", "1x gtceu:small_iron_dust") 
        .inputFluids("gtceu:distilled_water 1000")
        .chancedOutput("gtceu:rutile_gem", 9500, 0)
        .chancedOutput("gtceu:rutile_gem", 5000, 0)
        .chancedOutput("gtceu:rutile_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_rutile_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_rutile_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.UV])
        .duration(2000)
    // Brookite
    event.recipes.gtceu.gem_growing_vat("brookite_growing")
        .itemInputs("1x gtceu:titanium_suboxide_dust", "1x gtceu:small_titanium_dust", "1x gtceu:small_niobium_dust") 
        .inputFluids("gtceu:distilled_water 1000")
        .chancedOutput("gtceu:brookite_gem", 9500, 0)
        .chancedOutput("gtceu:brookite_gem", 5000, 0)
        .chancedOutput("gtceu:brookite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_brookite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_brookite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.UV])
        .duration(2000)
    // Anatase
    event.recipes.gtceu.gem_growing_vat("anatase_growing")
        .itemInputs("1x gtceu:titanium_suboxide_dust", "1x gtceu:small_titanium_dust", "1x gtceu:small_tantalum_dust") 
        .inputFluids("gtceu:distilled_water 1000")
        .chancedOutput("gtceu:anatase_gem", 9500, 0)
        .chancedOutput("gtceu:anatase_gem", 5000, 0)
        .chancedOutput("gtceu:anatase_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_anatase_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_anatase_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.UV])
        .duration(2000)
    //// Fluoride
    // Fluorite
    event.recipes.gtceu.gem_growing_vat("fluorite_growing")
        .itemInputs("1x gtceu:calcium_dust", "1x gtceu:small_calcium_dust") 
        .inputFluids("gtceu:fluorine 1000")
        .chancedOutput("gtceu:fluorite_gem", 9500, 0)
        .chancedOutput("gtceu:fluorite_gem", 5000, 0)
        .chancedOutput("gtceu:fluorite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_fluorite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_fluorite_gem", 250, 0)
        .circuit(3)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1000)
    // Villiaumite
    event.recipes.gtceu.gem_growing_vat("villiaumite_growing")
        .itemInputs("1x gtceu:sodium_dust", "1x gtceu:small_sodium_dust") 
        .inputFluids("gtceu:fluorine 1000")
        .chancedOutput("gtceu:villiaumite_gem", 9500, 0)
        .chancedOutput("gtceu:villiaumite_gem", 5000, 0)
        .chancedOutput("gtceu:villiaumite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_villiaumite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_villiaumite_gem", 250, 0)
        .circuit(3)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1300)
    // Topaz
    event.recipes.gtceu.gem_growing_vat("topaz_growing")
        .itemInputs("1x gtceu:aluminium_dust") 
        .inputFluids("gtceu:silica_gem_stock 1000", "gtceu:fluorine 500")
        .chancedOutput("gtceu:topaz_gem", 9500, 0)
        .chancedOutput("gtceu:topaz_gem", 5000, 0)
        .chancedOutput("gtceu:topaz_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_topaz_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_topaze_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1500)
    // Blue Topaz
    event.recipes.gtceu.gem_growing_vat("blue_topaz_growing")
        .itemInputs("1x gtceu:aluminium_dust") 
        .inputFluids("gtceu:silica_gem_stock 1000", "gtceu:fluorine 500", "minecraft:water 500")
        .chancedOutput("gtceu:blue_topaz_gem", 9500, 0)
        .chancedOutput("gtceu:blue_topaz_gem", 5000, 0)
        .chancedOutput("gtceu:blue_topaz_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_blue_topaz_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_blue_topaz_gem", 250, 0)
        .circuit(2)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1500)
    //// Sulfide
    // Realgar
    event.recipes.gtceu.gem_growing_vat("realgar_growing")
        .itemInputs("1x gtceu:arsenic_dust", "gtceu:sulfur_dust") 
        .inputFluids("gtceu:distilled_water 1000", "gtceu:arsenic 1000")
        .chancedOutput("gtceu:realgar_gem", 9500, 0)
        .chancedOutput("gtceu:realgar_gem", 5000, 0)
        .chancedOutput("gtceu:realgar_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_realgar_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_realgar_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1400)
    // Xanthoconite
    event.recipes.gtceu.gem_growing_vat("xanthoconite_growing")
        .itemInputs("1x gtceu:arsenic_dust", "gtceu:sulfur_dust", "gtceu:silver_dust") 
        .inputFluids("gtceu:distilled_water 1000")
        .chancedOutput("gtceu:xanthoconite_gem", 9500, 0)
        .chancedOutput("gtceu:xanthoconite_gem", 5000, 0)
        .chancedOutput("gtceu:xanthoconite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_xanthoconite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_xanthoconite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1400)
    // Cinnabar
    event.recipes.gtceu.gem_growing_vat("cinnabar_growing")
        .itemInputs("1x gtceu:sulfur_dust") 
        .inputFluids("gtceu:mercury 1000")
        .chancedOutput("gtceu:cinnabar_gem", 9500, 0)
        .chancedOutput("gtceu:cinnabar_gem", 5000, 0)
        .chancedOutput("gtceu:cinnabar_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_cinnabar_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_cinnabar_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1000)
    //// Sulfate
    // Selenite
    event.recipes.gtceu.gem_growing_vat("selenite_growing")
        .itemInputs("1x gtceu:potassium_sulfate_dust", "gtceu:small_calcium_dust") 
        .inputFluids("minecraft:water 1000")
        .chancedOutput("gtceu:selenite_gem", 9500, 0)
        .chancedOutput("gtceu:selenite_gem", 5000, 0)
        .chancedOutput("gtceu:selenite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_selenite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_selenite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(600)
    // Celstine
    event.recipes.gtceu.gem_growing_vat("celestine_growing")
        .itemInputs("1x gtceu:potassium_sulfate_dust", "gtceu:small_strontium_dust") 
        .inputFluids("gtceu:distilled_water 1000")
        .chancedOutput("gtceu:celestine_gem", 9500, 0)
        .chancedOutput("gtceu:celestine_gem", 5000, 0)
        .chancedOutput("gtceu:celestine_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_celestine_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_celestine_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1000)
    //// Other
    // Lithium Niobate
    event.recipes.gtceu.gem_growing_vat("lithium_niobate_growing")
        .itemInputs("1x gtceu:lithium_oxide_dust", "gtceu:small_niobium_dust") 
        .inputFluids("minecraft:water 1000", "gtceu:oxygen 500")
        .chancedOutput("gtceu:lithium_niobate_gem", 9500, 0)
        .chancedOutput("gtceu:lithium_niobate_gem", 5000, 0)
        .chancedOutput("gtceu:lithium_niobate_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_lithium_niobate_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_lithium_niobate_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1800)
    // Salt
    event.recipes.gtceu.gem_growing_vat("salt_growing")
        .itemInputs("2x gtceu:salt_dust") 
        .inputFluids("gtceu:salt_water 1000")
        .chancedOutput("gtceu:salt_gem", 9500, 0)
        .chancedOutput("gtceu:salt_gem", 5000, 0)
        .chancedOutput("gtceu:salt_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_salt_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_salt_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(900)
    // Rock Salt
    event.recipes.gtceu.gem_growing_vat("rock_salt_growing")
        .itemInputs("2x gtceu:rock_salt_dust", "gtceu:small_potassium_hydroxide_dust") 
        .inputFluids("gtceu:salt_water 1000")
        .chancedOutput("gtceu:rock_salt_gem", 9500, 0)
        .chancedOutput("gtceu:rock_salt_gem", 5000, 0)
        .chancedOutput("gtceu:rock_salt_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_rock_salt_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_rock_salt_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(900)
    // Manganite
    event.recipes.gtceu.gem_growing_vat("manganite_growing")
        .itemInputs("1x gtceu:manganese_dust", "gtceu:small_manganese_dust") 
        .inputFluids("gtceu:distilled_water 1000")
        .chancedOutput("gtceu:manganite_gem", 9500, 0)
        .chancedOutput("gtceu:manganite_gem", 5000, 0)
        .chancedOutput("gtceu:manganite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_manganite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_manganite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1500)
    // Dulysite
    event.recipes.gtceu.gem_growing_vat("dulysite_growing")
        .itemInputs("1x gtceu:duranium_dust", "gtceu:small_duranium_dust") 
        .inputFluids("gtceu:chlorine 1000")
        .chancedOutput("gtceu:dulysite_gem", 9500, 0)
        .chancedOutput("gtceu:dulysite_gem", 5000, 0)
        .chancedOutput("gtceu:dulysite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_dulysite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_dulysite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(2100)
    // Calomel
    event.recipes.gtceu.gem_growing_vat("calomel_growing")
        .itemInputs("1x gtceu:mercury_dust") 
        .inputFluids("gtceu:chlorine 1000", "gtceu:mercury 1000")
        .chancedOutput("gtceu:calomel_gem", 9500, 0)
        .chancedOutput("gtceu:calomel_gem", 5000, 0)
        .chancedOutput("gtceu:calomel_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_calomel_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_calomel_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1200)
    // Sperrylite
    event.recipes.gtceu.gem_growing_vat("sperrylite_growing")
        .itemInputs("1x gtceu:platinum_dust", "gtceu:small_palladium_dust") 
        .inputFluids("gtceu:arsenic 1000")
        .chancedOutput("gtceu:sperrylite_gem", 9500, 0)
        .chancedOutput("gtceu:sperrylite_gem", 5000, 0)
        .chancedOutput("gtceu:sperrylite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_sperrylite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_sperrylite_gem", 250, 0)
        .circuit(1)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1800)
    // Malachite
    event.recipes.gtceu.gem_growing_vat("malachite_growing")
        .itemInputs("1x gtceu:copper_dust", "gtceu:small_copper_dust") 
        .inputFluids("gtceu:distilled_water 1000", "gtceu:carbon_dioxide 1000")
        .chancedOutput("gtceu:malachite_gem", 9500, 0)
        .chancedOutput("gtceu:malachite_gem", 5000, 0)
        .chancedOutput("gtceu:malachite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_malachite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_malachite_gem", 250, 0)
        .circuit(2)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1400)
    // Lindgrenite
    event.recipes.gtceu.gem_growing_vat("lindgrenite_growing")
        .itemInputs("1x gtceu:molybdenum_trioxide_dust", "2x gtceu:small_copper_dust") 
        .inputFluids("minecraft:water 1000")
        .chancedOutput("gtceu:lindgrenite_gem", 9500, 0)
        .chancedOutput("gtceu:lindgrenite_gem", 5000, 0)
        .chancedOutput("gtceu:lindgrenite_gem", 2000, 0)
        .chancedOutput("gtceu:flawless_lindgrenite_gem", 750, 0)
        .chancedOutput("gtceu:exquisite_lindgrenite_gem", 250, 0)
        .circuit(2)
        .EUt(GTValues.VHA[GTValues.ZPM])
        .duration(1400)
})