ServerEvents.recipes(event => {
    // Controller recipe - TODO:

    // Inherited LCR/electrolyzer recipes
    event.recipes.gtceu.neutron_chamber("actinium_from_radon_salt_inherit")
        .chancedInput("6x kubejs:neutron_emitter", 25, 0)
        .itemInputs("kubejs:radium_salt")
        .itemOutputs("gtceu:rock_salt_dust")
        .chancedFluidOutputLogic(ChanceLogic.XOR)
        .chancedFluidOutput("gtceu:actinium 144", 2000, 0)
        .chancedFluidOutput("gtceu:radon 250", 8000, 0)
        .duration(160)
        .EUt(GTValues.VHA[GTValues.ZPM])
    event.recipes.gtceu.neutron_chamber("actinium_from_uranic_solution_inherit")
        .chancedInput("6x kubejs:neutron_emitter", 25, 0)
        .inputFluids("gtceu:uranic_solution 2000")
        .itemOutputs("3x gtceu:lead_chloride_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:actinium_dust", 2000, 0)
        .chancedOutput("gtceu:thorium_dust", 3333, 0)
        .chancedOutput("3x gtceu:uraninite_dust", 5000, 0)
        .outputFluids("minecraft:water 1000")
        .duration(160)
        .EUt(GTValues.VHA[GTValues.ZPM])

    // Forced decomposition of actinides & pre-actinides
    // Bismuth
    event.recipes.gtceu.neutron_chamber("bismuth_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:bismuth_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:tin_dust", 4000, 0)
        .chancedOutput("gtceu:antimony_dust", 2500, 0)
        .chancedOutput("gtceu:tellurium_dust", 2000, 0)
        .chancedOutput("gtceu:lead_dust", 900, 0)
        .chancedOutput("gtceu:polonium_dust", 600, 0)
        .chancedFluidOutput("gtceu:radon 100", 500, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Polonium
    event.recipes.gtceu.neutron_chamber("polonium_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:polonium_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:lead_dust", 6000, 0)
        .chancedOutput("gtceu:bismuth_dust", 3000, 0)
        .chancedOutput("gtceu:tellurium_dust", 500, 0)
        .chancedOutput("gtceu:selenium_dust", 500, 0)
        .chancedFluidOutput("gtceu:radon 500", 1500, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Astatine
    event.recipes.gtceu.neutron_chamber("astatine_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:astatine_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:iodine_dust", 6500, 0)
        .chancedOutput("gtceu:tellurium_dust", 3000, 0)
        .chancedOutput("gtceu:bismuth_dust", 500, 0)
        .chancedFluidOutput("gtceu:xenon 250", 2500, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Radon
    event.recipes.gtceu.neutron_chamber("radon_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .inputFluids("gtceu:radon 1000")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:lead_dust", 5000, 0)
        .chancedOutput("gtceu:tin_dust", 3000, 0)
        .chancedOutput("gtceu:polonium_dust", 1000, 0)
        .chancedOutput("gtceu:bismuth_dust", 800, 0)
        .chancedOutput("gtceu:astatine_dust", 200, 0)
        .chancedFluidOutput("gtceu:helium 250", 1500, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Francium
    event.recipes.gtceu.neutron_chamber("francium_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:francium_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:caesium_dust", 5000, 0)
        .chancedOutput("gtceu:rubidium_dust", 4000, 0)
        .chancedOutput("gtceu:strontium_dust", 900, 0)
        .chancedOutput("gtceu:radium_dust", 100, 0)
        .chancedFluidOutput("gtceu:radon 500", 2000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Radium
    event.recipes.gtceu.neutron_chamber("radium_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:radium_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:barium_dust", 5000, 0)
        .chancedOutput("gtceu:strontium_dust", 4000, 0)
        .chancedOutput("gtceu:lead_dust", 600, 0)
        .chancedOutput("gtceu:polonium_dust", 400, 0)
        .chancedFluidOutput("gtceu:helium 250", 1000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Actinium
    event.recipes.gtceu.neutron_chamber("actinium_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:actinium_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:thorium_dust", 5000, 0)
        .chancedOutput("gtceu:radium_dust", 3000, 0)
        .chancedOutput("gtceu:lead_dust", 1000, 0)
        .chancedFluidOutput("gtceu:radon 1000", 3000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Thorium
    event.recipes.gtceu.neutron_chamber("thorium_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:thorium_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:lead_dust", 6500, 0)
        .chancedOutput("gtceu:zirconium_dust", 2500, 0)
        .chancedOutput("gtceu:actinium_dust", 900, 0)
        .chancedOutput("gtceu:francium_dust", 100, 0)
        .chancedFluidOutput("gtceu:xenon 1000", 1000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Thorium 232
    event.recipes.gtceu.neutron_chamber("thorium_232_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:thorium_232_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:lead_dust", 6500, 0)
        .chancedOutput("gtceu:zirconium_dust", 2500, 0)
        .chancedOutput("gtceu:technetium_dust", 700, 0)
        .chancedOutput("gtceu:iodine_dust", 300, 0)
        .chancedFluidOutput("gtceu:xenon 1000", 1000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Protactinium
    event.recipes.gtceu.neutron_chamber("protactinium_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:protactinium_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:actinium_dust", 4000, 0)
        .chancedOutput("gtceu:thorium_dust", 3000, 0)
        .chancedOutput("gtceu:lead_dust", 2500, 0)
        .chancedOutput("gtceu:technetium_dust", 300, 0)
        .chancedOutput("gtceu:niobium_dust", 200, 0)
        .chancedFluidOutput("gtceu:xenon 500", 500, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Uranium 233
    event.recipes.gtceu.neutron_chamber("uranium_233_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:uranium_233_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:strontium_dust", 3000, 0)
        .chancedOutput("gtceu:barium_dust", 2500, 0)
        .chancedOutput("gtceu:zirconium_dust", 2500, 0)
        .chancedOutput("gtceu:iodine_dust", 1000, 0)
        .chancedOutput("gtceu:bismuth_dust", 900, 0)
        .chancedOutput("gtceu:astatine_dust", 100, 0)
        .chancedFluidOutput("gtceu:krypton 1000", 2000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Uranium 235
    event.recipes.gtceu.neutron_chamber("uranium_235_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:uranium_235_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:zirconium_dust", 3000, 0)
        .chancedOutput("gtceu:strontium_dust", 2500, 0)
        .chancedOutput("gtceu:barium_dust", 2500, 0)
        .chancedOutput("gtceu:iodine_dust", 1000, 0)
        .chancedOutput("gtceu:thallium_dust", 900, 0)
        .chancedOutput("gtceu:francium_dust", 100, 0)
        .chancedFluidOutput("gtceu:xenon 1000", 2000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Uranium
    event.recipes.gtceu.neutron_chamber("uranium_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:uranium_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:barium_dust", 3000, 0)
        .chancedOutput("gtceu:strontium_dust", 2500, 0)
        .chancedOutput("gtceu:zirconium_dust", 2500, 0)
        .chancedOutput("gtceu:iodine_dust", 1000, 0)
        .chancedOutput("gtceu:lead_dust", 900, 0)
        .chancedOutput("gtceu:radium_dust", 100, 0)
        .chancedFluidOutput("gtceu:xenon 1000", 1000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Neptunium 236
    event.recipes.gtceu.neutron_chamber("neptunium_236_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:neptunium_236_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:zirconium_dust", 3000, 0)
        .chancedOutput("gtceu:ruthenium_dust", 2500, 0)
        .chancedOutput("gtceu:tin_dust", 2000, 0)
        .chancedOutput("gtceu:molybdenum_dust", 1500, 0)
        .chancedOutput("gtceu:palladium_dust", 600, 0)
        .chancedOutput("gtceu:technetium_dust", 400, 0)
        .chancedFluidOutput("gtceu:krypton 1000", 1000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Neptunium
    event.recipes.gtceu.neutron_chamber("neptunium_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:neptunium_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:zirconium_dust", 3000, 0)
        .chancedOutput("gtceu:molybdenum_dust", 2500, 0)
        .chancedOutput("gtceu:tin_dust", 2000, 0)
        .chancedOutput("gtceu:ruthenium_dust", 1500, 0)
        .chancedOutput("gtceu:technetium_dust", 600, 0)
        .chancedOutput("gtceu:palladium_dust", 400, 0)
        .chancedFluidOutput("gtceu:xenon 1000", 1000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Plutonium 238
    event.recipes.gtceu.neutron_chamber("plutonium_238_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:plutonium_238_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:barium_dust", 5000, 0)
        .chancedOutput("gtceu:promethium_dust", 2500, 0)
        .chancedOutput("gtceu:rhodium_dust", 2000, 0)
        .chancedOutput("gtceu:technetium_dust", 800, 0)
        .chancedOutput("gtceu:caesium_dust", 200, 0)
        .chancedFluidOutput("gtceu:krypton 500", 1500, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Plutonium
    event.recipes.gtceu.neutron_chamber("plutonium_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:plutonium_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:barium_dust", 4000, 0)
        .chancedOutput("gtceu:neodymium_dust", 2500, 0)
        .chancedOutput("gtceu:ruthenium_dust", 2500, 0)
        .chancedOutput("gtceu:technetium_dust", 600, 0)
        .chancedOutput("gtceu:caesium_dust", 400, 0)
        .chancedFluidOutput("gtceu:krypton 500", 1500, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Plutonium 241
    event.recipes.gtceu.neutron_chamber("plutonium_241_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:plutonium_241_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:barium_dust", 4000, 0)
        .chancedOutput("gtceu:ruthenium_dust", 2500, 0)
        .chancedOutput("gtceu:europium_dust", 2500, 0)
        .chancedOutput("gtceu:technetium_dust", 500, 0)
        .chancedOutput("gtceu:caesium_dust", 500, 0)
        .chancedFluidOutput("gtceu:krypton 750", 1500, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Plutonium 242
    event.recipes.gtceu.neutron_chamber("plutonium_242_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:plutonium_242_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:barium_dust", 5500, 0)
        .chancedOutput("gtceu:neodymium_dust", 2000, 0)
        .chancedOutput("gtceu:ruthenium_dust", 1500, 0)
        .chancedOutput("gtceu:technetium_dust", 600, 0)
        .chancedOutput("gtceu:caesium_dust", 400, 0)
        .chancedFluidOutput("gtceu:krypton 1000", 1500, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Americium 241
    event.recipes.gtceu.neutron_chamber("americium_241_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:americium_241_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:cadmium_dust", 4000, 0)
        .chancedOutput("gtceu:niobium_dust", 3000, 0)
        .chancedOutput("gtceu:indium_dust", 2000, 0)
        .chancedOutput("gtceu:rubidium_dust", 700, 0)
        .chancedOutput("gtceu:thulium_dust", 300, 0)
        .chancedFluidOutput("gtceu:xenon 500", 2000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Americium 242
    event.recipes.gtceu.neutron_chamber("americium_242_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:americium_242_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:cadmium_dust", 4000, 0)
        .chancedOutput("gtceu:zirconium_dust", 3000, 0)
        .chancedOutput("gtceu:antimony_dust", 2000, 0)
        .chancedOutput("gtceu:technetium_dust", 700, 0)
        .chancedOutput("gtceu:caesium_dust", 300, 0)
        .chancedFluidOutput("gtceu:xenon 500", 2000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Americium
    event.recipes.gtceu.neutron_chamber("americium_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:americium_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:tin_dust", 3000, 0)
        .chancedOutput("gtceu:zirconium_dust", 3000, 0)
        .chancedOutput("gtceu:cadmium_dust", 3000, 0)
        .chancedOutput("gtceu:technetium_dust", 500, 0)
        .chancedOutput("gtceu:caesium_dust", 500, 0)
        .chancedFluidOutput("gtceu:xenon 500", 2000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Curium 243
    event.recipes.gtceu.neutron_chamber("curium_243_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:curium_243_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:rhodium_dust", 3500, 0)
        .chancedOutput("gtceu:molybdenum_dust", 2500, 0)
        .chancedOutput("gtceu:yttrium_dust", 2000, 0)
        .chancedOutput("gtceu:barium_dust", 1000, 0)
        .chancedOutput("gtceu:rhenium_dust", 700, 0)
        .chancedOutput("gtceu:technetium_dust", 300, 0)
        .chancedFluidOutput("gtceu:krypton 350", 2000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Curium 245
    event.recipes.gtceu.neutron_chamber("curium_245_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:curium_245_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:ruthenium_dust", 3000, 0)
        .chancedOutput("gtceu:molybdenum_dust", 3000, 0)
        .chancedOutput("gtceu:titanium_dust", 1800, 0)
        .chancedOutput("gtceu:barium_dust", 1200, 0)
        .chancedOutput("gtceu:lutetium_dust", 700, 0)
        .chancedOutput("gtceu:selenium_dust", 300, 0)
        .chancedFluidOutput("gtceu:krypton 250", 2000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Curium
    event.recipes.gtceu.neutron_chamber("curium_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:curium_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:ruthenium_dust", 3500, 0)
        .chancedOutput("gtceu:molybdenum_dust", 2500, 0)
        .chancedOutput("gtceu:zirconium_dust", 2000, 0)
        .chancedOutput("gtceu:barium_dust", 1000, 0)
        .chancedOutput("gtceu:erbium_dust", 700, 0)
        .chancedOutput("gtceu:technetium_dust", 300, 0)
        .chancedFluidOutput("gtceu:krypton 250", 2000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Curium 247
    event.recipes.gtceu.neutron_chamber("curium_247_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:curium_247_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:palladium_dust", 3500, 0)
        .chancedOutput("gtceu:zirconium_dust", 2500, 0)
        .chancedOutput("gtceu:strontium_dust", 2000, 0)
        .chancedOutput("gtceu:francium_dust", 1000, 0)
        .chancedOutput("gtceu:terbium_dust", 700, 0)
        .chancedOutput("gtceu:technetium_dust", 300, 0)
        .chancedFluidOutput("gtceu:krypton 250", 2000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Berkelium
    event.recipes.gtceu.neutron_chamber("berkelium_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:berkelium_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:tin_dust", 5000, 0)
        .chancedOutput("gtceu:ruthenium_dust", 2000, 0)
        .chancedOutput("gtceu:palladium_dust", 2000, 0)
        .chancedOutput("gtceu:iodine_dust", 800, 0)
        .chancedOutput("gtceu:technetium_dust", 200, 0)
        .chancedFluidOutput("gtceu:xenon 450", 1000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Berkelium 248
    event.recipes.gtceu.neutron_chamber("berkelium_248_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:berkelium_248_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:tin_dust", 5000, 0)
        .chancedOutput("gtceu:osmium_dust", 2000, 0)
        .chancedOutput("gtceu:nickel_dust", 2000, 0)
        .chancedOutput("gtceu:iodine_dust", 600, 0)
        .chancedOutput("gtceu:technetium_dust", 400, 0)
        .chancedFluidOutput("gtceu:xenon 750", 1000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Californium 249
    event.recipes.gtceu.neutron_chamber("californium_249_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:californium_249_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:zirconium_dust", 5000, 0)
        .chancedOutput("gtceu:tellurium_dust", 2500, 0)
        .chancedOutput("gtceu:polonium_dust", 1500, 0)
        .chancedOutput("gtceu:rubidium_dust", 700, 0)
        .chancedOutput("gtceu:promethium_dust", 300, 0)
        .chancedFluidOutput("gtceu:xenon 7500", 3000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Californium 250
    event.recipes.gtceu.neutron_chamber("californium_250_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:californium_250_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:hafnium_dust", 3000, 0)
        .chancedOutput("gtceu:selenium_dust", 3000, 0)
        .chancedOutput("gtceu:astatine_dust", 3000, 0)
        .chancedOutput("gtceu:rubidium_dust", 600, 0)
        .chancedOutput("gtceu:promethium_dust", 400, 0)
        .chancedFluidOutput("gtceu:xenon 2000", 1000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Californium
    event.recipes.gtceu.neutron_chamber("californium_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:californium_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:zirconium_dust", 4000, 0)
        .chancedOutput("gtceu:antimony_dust", 3000, 0)
        .chancedOutput("gtceu:radium_dust", 2000, 0)
        .chancedOutput("gtceu:rubidium_dust", 900, 0)
        .chancedOutput("gtceu:promethium_dust", 100, 0)
        .chancedFluidOutput("gtceu:xenon 1000", 2500, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Californium 252
    event.recipes.gtceu.neutron_chamber("californium_252_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:californium_252_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:zirconium_dust", 6000, 0)
        .chancedOutput("gtceu:tin_dust", 2000, 0)
        .chancedOutput("gtceu:barium_dust", 1000, 0)
        .chancedOutput("gtceu:rubidium_dust", 950, 0)
        .chancedOutput("gtceu:promethium_dust", 50, 0)
        .chancedFluidOutput("gtceu:xenon 1000", 4500, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Einsteinium
    event.recipes.gtceu.neutron_chamber("einsteinium_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:einsteinium_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:strontium_dust", 5500, 0)
        .chancedOutput("gtceu:yttrium_dust", 2000, 0)
        .chancedOutput("gtceu:molybdenum_dust", 1500, 0)
        .chancedOutput("gtceu:technetium_dust", 600, 0)
        .chancedOutput("gtceu:strontium_dust", 400, 0)
        .chancedFluidOutput("gtceu:krypton 1000", 2250, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Einsteinium 253
    event.recipes.gtceu.neutron_chamber("einsteinium_253_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:einsteinium_253_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:strontium_dust", 3500, 0)
        .chancedOutput("gtceu:scandium_dust", 3000, 0)
        .chancedOutput("gtceu:tungsten_dust", 2500, 0)
        .chancedOutput("gtceu:technetium_dust", 500, 0)
        .chancedOutput("gtceu:strontium_dust", 500, 0)
        .chancedFluidOutput("gtceu:krypton 1000", 2250, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Einsteinium 254
    event.recipes.gtceu.neutron_chamber("einsteinium_254_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:einsteinium_254_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:strontium_dust", 3500, 0)
        .chancedOutput("gtceu:yttrium_dust", 2500, 0)
        .chancedOutput("gtceu:molybdenum_dust", 2000, 0)
        .chancedOutput("gtceu:rhenium_dust", 1200, 0)
        .chancedOutput("gtceu:calcium_dust", 800, 0)
        .chancedFluidOutput("gtceu:krypton 1000", 2250, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Fermium 255
    event.recipes.gtceu.neutron_chamber("fermium_255_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:fermium_255_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:cerium_dust", 4000, 0)
        .chancedOutput("gtceu:chromium_dust", 3000, 0)
        .chancedOutput("gtceu:radium_dust", 1500, 0)
        .chancedOutput("gtceu:promethium_dust", 1500, 0)
        .chancedFluidOutput("gtceu:neon 2500", 2000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Fermium
    event.recipes.gtceu.neutron_chamber("fermium_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:fermium_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:neodymium_dust", 6000, 0)
        .chancedOutput("gtceu:ruthenium_dust", 2000, 0)
        .chancedOutput("gtceu:barium_dust", 1000, 0)
        .chancedOutput("gtceu:technetium_dust", 1000, 0)
        .chancedFluidOutput("gtceu:neon 2500", 2000, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Mendelevium
    event.recipes.gtceu.neutron_chamber("mendelevium_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:mendelevium_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:samarium_dust", 4500, 0)
        .chancedOutput("gtceu:selenium_dust", 2000, 0)
        .chancedOutput("gtceu:arsenic_dust", 1500, 0)
        .chancedOutput("gtceu:gadolinium_dust", 600, 0)
        .chancedOutput("gtceu:thallium_dust", 400, 0)
        .chancedFluidOutput("gtceu:xenon 2500", 1500, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
    // Nobelium
    event.recipes.gtceu.neutron_chamber("nobelium_forced_fission")
        .chancedInput("6x kubejs:neutron_emitter", 1000, 0)
        .itemInputs("gtceu:nobelium_dust")
        .chancedItemOutputLogic(ChanceLogic.XOR)
        .chancedOutput("gtceu:lanthanum_dust", 1500, 0)
        .chancedOutput("gtceu:niobium_dust", 1500, 0)
        .chancedOutput("gtceu:gallium_dust", 1000, 0)
        .chancedOutput("gtceu:astatine_dust", 1000, 0)
        .chancedOutput("gtceu:dysprosium_dust", 800, 0)
        .chancedOutput("gtceu:thallium_dust", 700, 0)
        .chancedOutput("gtceu:scandium_dust", 600, 0)
        .chancedOutput("gtceu:ytterbium_dust", 600, 0)
        .chancedOutput("gtceu:cobalt_dust", 400, 0)
        .chancedOutput("gtceu:thulium_dust", 400, 0)
        .chancedOutput("gtceu:vanadium_dust", 300, 0)
        .chancedOutput("gtceu:lead_dust", 200, 0)
        .chancedFluidOutput("gtceu:argon 2500", 1500, 0)
        .duration(600)
        .EUt(GTValues.VA[GTValues.UV])
})