ServerEvents.recipes(event => {
    // Controller

    // Ores
    function processOre(id, liquid, initOut, washOut, postOut, finalOut, type, magnet1, magnet2, gemName) {
        if (type == "gem") {
            event.recipes.gtceu.ore_processing_factory(`${id}_full_processing`)
                .itemInputs(`128x gtceu:crushed_${id}_ore`)
                .inputFluids(`gtceu:${liquid} 8000`)
                .itemOutputs(`256x gtceu:${id}_dust`, 
                    `50x gtceu:${initOut}_dust`,
                    `90x gtceu:${washOut}_dust`,
                    `82x gtceu:${postOut}_dust`,
                    `18x gtceu:${finalOut}_dust`,
                    `45x ${gemName}`,
                    `13x gtceu:flawless_${id}_gem`,
                    `4x gtceu:exquisite_${id}_gem`)
                .duration(240)
                .EUt(GTValues.VA[GTValues.ZPM])
        }
        else if (type == "magnetic") {
            event.recipes.gtceu.ore_processing_factory(`${id}_full_processing`)
                .itemInputs(`128x gtceu:crushed_${id}_ore`)
                .inputFluids(`gtceu:${liquid} 8000`)
                .itemOutputs(`256x gtceu:${id}_dust`, 
                    `50x gtceu:${initOut}_dust`,
                    `90x gtceu:${washOut}_dust`,
                    `75x gtceu:${postOut}_dust`,
                    `18x gtceu:${finalOut}_dust`,
                    `13x gtceu:${magnet1}_dust`,
                    `50x ${magnet2}`)
                .duration(240)
                .EUt(GTValues.VA[GTValues.ZPM])
        }
        else {
            event.recipes.gtceu.ore_processing_factory(`${id}_full_processing`)
            .itemInputs(`128x gtceu:crushed_${id}_ore`)
            .inputFluids(`gtceu:${liquid} 8000`)
            .itemOutputs(`256x gtceu:${id}_dust`, 
                `50x gtceu:${initOut}_dust`,
                `90x gtceu:${washOut}_dust`,
                `75x gtceu:${postOut}_dust`,
                `18x gtceu:${finalOut}_dust`)
            .duration(240)
            .EUt(GTValues.VA[GTValues.ZPM])
        }
    }

    processOre("almandine", "distilled_water", "red_garnet", "red_garnet", "aluminium", "aluminium", "gem", null, null, "gtceu:almandine_gem")
    processOre("aluminium", "sodium_persulfate", "bauxite", "rutile", "bauxite", "ilmenite", "normal", null, null, null)
    processOre("alunite", "distilled_water", "magnesite", "magnesite", "alunite", "microcline", "normal", null, null, null)
    processOre("amethyst", "distilled_water", "quartzite", "quartzite", "amethyst", "charged_certus_quartz", "gem", null, null, "minecraft:amethyst_shard")
    processOre("anatase", "mercury", "magnetite", "zirconium", "rutile", "zirconium", "gem", null, null, "gtceu:anatase_gem")
    processOre("andradite", "distilled_water", "calcium", "calcium", "iron", "silicon", "gem", null, null, "gtceu:andradite_gem")
    processOre("anorthite", "nitric_acid", "sodium", "aluminium", "sodium", "aluminium", "gem", null, null, "gtceu:anorthite_gem")
    processOre("apatite", "distilled_water", "tricalcium_phosphate", "tricalcium_phosphate", "phosphate", "pyrochlore", "gem", null, null, "gtceu:apatite_gem")
    processOre("aquamarine", "distilled_water", "pyrite", "pyrite", "euclase", "brookite", "gem", null, null, "gtceu:aquamarine_gem")
    processOre("aragonite", "distilled_water", "calcite", "calcite", "strontianite", "witherite", "normal", null, null, null)
    processOre("argentite", "nitric_acid", "lead", "zinc", "sulfur", "zinc", "normal", null, null, null)
    processOre("arsenopyrite", "nitric_acid", "sulfur", "sulfur", "cobalt", "sulfur", "normal", null, null, null)
    processOre("asbestos", "distilled_water", "diatomite", "diatomite", "silicon", "magnesium", "normal", null, null, null)
    processOre("azurite", "nitric_acid", "calcite", "malachite", "calcium_hydroxide", "barite", "normal", null, null, null)
    processOre("barite", "distilled_water", "barite", "barite", "barite", "barite", "normal", null, null, null)
    processOre("basaltic_mineral_sand", "distilled_water", "basalt", "basalt", "magnetite", "magnetite", "magnetic", "gold", "minecraft:gold_nugget", null)
    processOre("bastnasite", "distilled_water", "neodymium", "neodymium", "rare_earth", "rare_earth", "magnetic", "neodymium", "gtceu:neodymium_dust", null)
    processOre("bauxite", "sodium_persulfate", "grossular", "gallium", "rutile", "gallium", "normal", null, null, null)
    processOre("bazzite", "distilled_water", "euclase", "euclase", "hematite", "fluorite", "gem", null, null, "gtceu:bazzite_gem")
    processOre("bentonite", "distilled_water", "aluminium", "aluminium", "calcium", "magnesium", "normal", null, null, null)
    processOre("beryllium", "distilled_water", "emerald", "emerald", "emerald", "thorium_232", "normal", null, null, null)
    processOre("bismite", "nitric_acid", "tin", "bismuth", "bismuth", "bismuth", "normal", null, null, null)
    processOre("black_opal", "distilled_water", "opal", "opal", "quartzite", "yellow_limonite", "normal", null, null, null)
    processOre("blue_topaz", "distilled_water", "topaz", "topaz", "topaz", "topaz", "gem", null, null, "gtceu:blue_topaz_gem")
    processOre("borax", "distilled_Water", "salt", "salt", "boron", "rock_salt", "normal", null, null, null)
    processOre("bornite", "mercury", "pyrite", "gold", "cobalt", "cadmium", "normal", null, null, null)
    processOre("briartite", "distilled_water", "copper", "copper", "sphalerite", "germanium_disulfide", "normal", null, null, null)
    processOre("brookite", "mercury", "hematite", "tantalite", "niobium", "tantalite", "gem", null, null, "gtceu:brookite_gem")
    processOre("cadmoindite", "hydrobromic_acid", "spinel", "cadmium", "indite", "hawleyite", "normal", null, null, null)
    processOre("calcite", "distilled_water", "aragonite", "aragonite", "strontium", "sodalite", "normal", null, null, null)
    processOre("calomel", "hydrobromic_acid", "cinnabar", "tetrahedrite", "yellow_limonite", "coccinite", "gem", null, null, "gtceu:calomel_gem")
    processOre("carnotite", "nitric_acid", "uraninite", "vanadium", "potassium", "vanadium", "normal", null, null, null)
    processOre("cassiterite", "distilled_water", "tin", "tin", "bismuth", "bismuth", "normal", null, null, null)
    processOre("cassiterite_sand", "distilled_water", "tin", "tin", "tin", "tin", "normal", null, null, null)
    // processOre("cavansite", "distilled_water", "certus_quartz", "certus_quartz", "calcium", "vanadium_pentoxide", "gem", null, null, "gtceu:cavansite_gem")
    processOre("celestine", "distilled_water", "selenite", "selenite", "sulfur", "barite", "gem", null, null, "gtceu:celestine_gem")
    //processOre("certus_quartz", "distilled_water", "nether_quartz", "nether_quartz", "barite", "barite", "gem", null, null, "ae2:certus_quartz_crystal")
    processOre("chalcocite", "distilled_water", "sulfur", "sulfur", "massicot", "silver", "normal", null, null, null)
    processOre("chalcopyrite", "mercury", "pyrite", "gold", "cobalt", "cadmium", "normal", null, null, null)
    processOre("chambersite", "distilled_water", "rock_salt", "rock_salt", "salt", "borax", "gem", null, null, "gtceu:chambersite_gem")
    processOre("chromite", "distilled_water", "iron", "iron", "magnesium", "chromium", "magnetic", "iron", "minecraft:iron_nugget", null)
    processOre("chrysoberyl", "distilled_water", "quartzite", "quartzite", "lithium", "niobium", "gem", null, null, "gtceu:chrysoberyl_gem")
    // processOre("cinnabar", "distilled_water", "redstone", "redstone", "sulfur", "glowtone", "gem", null, null, "gtceu:cinnabar_gem")
    processOre("citrine", "hexafluorosilicic_acid", "nether_quartz", "amethyst", "yellow_limonite", "yellow_limonite", "gem", null, null, "gtceu:citrine_gem")
    processOre("coal", "distilled_water", "coal", "coal", "coal", "thorium", "gem", null, null, "minecraft:coal")
    processOre("cobalt", "sodium_persulfate", "cobalt_oxide", "cobaltite", "cobaltite", "cobaltite", "normal", null, null, null)
    processOre("cobaltite", "sodium_persulfate", "sulfur", "cobalt", "cobalt", "cobalt", "normal", null, null, null)
    processOre("coccinite", "hydrobromic_acid", "pyrite", "iodine", "calomel", "calomel", "normal", null, null, null)
    processOre("columbite", "nitric_acid", "manganese", "niobium", "tantalum", "niobium", "normal", null, null, null)
    processOre("copper", "mercury", "cobalt", "gold", "gold", "nickel", "normal", null, null, null)
    processOre("cryolite", "distilled_water", "salt", "salt", "bauxite", 'iodine', "normal", null, null, null)
    processOre("cuprorhodsite", "distilled_water", "chalcocite", "chalcocite", "platinum", "ruthenium", "normal", null, null, null)
    processOre("darmstadtite", "distilled_water", "rhodium_sulfate", "rhodium_sulfate", "rare_earth", "darmstadtium", "normal", null, null, null)
    processOre("datolite", "distilled_water", "quartzite", "quartzite", "borax", "zircon", "gem", null, null, "gtceu:datolite_gem")
    processOre("diamond", "distilled_water", "graphite", "graphite", "graphite", "graphite", "gem", null, null, "minecraft:diamond")
    processOre("diatomite", "distilled_water", "hematite", "hematite", "sapphire", "sapphire", "normal", null, null, null)
    processOre("dilithium", "distilled_water", "lithium", "lithium", "cobalt", "platinum", "gem", null, null, "gtceu:dilithium_gem")
    processOre("dulysite", "distilled_water", "sphalerite", "sphalerite", "duranium", "europium", "gem", null, null, "gtceu:dulysite_gem")
    processOre("dzhalindite", "hydrobromic_acid", "cassiterite", "cadmoindite", "tin", "indite", "normal", null, null, null)
    processOre("ekanite", "distilled_water", "magnetite", "magnetite", "lead", "uraninite", "gem", null, null, "gtceu:ekanite_gem")
    // processOre("electrotine", "distilled_water", "redstone", "redstone", "electrum", "diamond", "normal", null, null, null)
    processOre("emerald", "distilled_water", "beryllium", "beryllium", "vanadium", "vanadium", "gem", null, null, "minecraft:emerald")
    processOre("euclase", "distilled_water", "charged_certus_quartz", "fluorite", "fluorite", "anatase", "gem", null, null, "gtceu:euclase_gem")
    processOre("ferberite", "mercury", "magnetite", "tungstite", "hubnerite", "wolframite", "gem", null, null, "gtceu:ferberite_gem")
    processOre("fergusonite", "distilled_water", "scandium", "scandium", "tantalite", "thorium", "normal", null, null, null)
    processOre("fluorite", "distilled_water", "calcite", "calcite", "barite", "barite", "gem", null, null, "fluorite_gem")
    processOre("fluoroapatite", "distilled_water", "fluorite", "fluorite", "apatite", "monazite", "gem", null, null, "gtceu:fluoroapatite_gem")
    processOre("fullers_earth", "distilled_water", "aluminium", "aluminium", "silicon", "magnesium", "normal", null, null, null)
    processOre("gadolinite", "hexafluorosilicic_acid", "beryllium_oxide", "gadolinium", "thorium_232", "monazite", "normal", null, null, null)
    processOre("galena", "mercury", "sulfur", "silver", "silver", "silver", "normal", null, null, null)
    processOre("gallite", "nitric_acid", "chalcopyrite", "germanium_disulfide", "gallium", "gallium", "normal", null, null, null)
    processOre("garnet_sand", "distilled_water", "red_garnet", "red_garnet", "yellow_garnet", "yellow_garnet", "normal", null, null, null)
    processOre("garnierite", "distilled_water", "iron", "iron", "nickel", "nickel", "normal", null, null, null)
    processOre("germanite", "sodium_persulfate", "molybdenite", "briartite", "realgar", "gallium", "normal", null, null, null)
    processOre("glauconite_sand", "distilled_water", "sodium", "sodium", "aluminum", "iron", "magnetic", "iron", "minecraft:iron_nugget", null)
    processOre("goethite", "distilled_water", "malachite", "malachite", "yellow_limonite", "yellow_limonite", "magnetic", "iron", "minecraft:iron_nugget", null)
    processOre("gold", "mercury", "copper", "silver", "nickel", "silver", "normal", null, null, null)
    processOre("granitic_mineral_sand", "distilled_water", "deepslate", "deepslate", "magnetite", "magnetite", "magnetic", "gold", "minecraft:gold_nugget", null)
    processOre("graphite", "distilled_water", "carbon", "carbon", "carbon", "carbon", "normal", null, null, null)
    processOre("green_sapphire", "distilled_water", "aluminium", "aluminium", "sapphire", "sapphire", "gem", null, null, "gtceu:green_sapphire_gem")
    processOre("grossular", "distilled_water", "yellow_garnet", "yellow_garnet", "calcium", "calcium", "gem", null, null, "gtceu:grossular_gem")
    processOre("guyanaite", "sodium_persulfate", "zincochromite", "chromite", "graphite", "zircon", "normal", null, null, null)
    processOre("gypsum", "distilled_water", "sulfur", "sulfur", "calcium", "salt", "normal", null, null, null)
    processOre("hawleyite", "hydrobromic_acid", "sphalerite", "gallium", "cadmium", "sulfur", "normal", null, null, null)
    processOre("hematite", "distilled_water", "magnetite", "magnetite", "calcium", "magnesium", "magnetic", "iron", "minecraft:iron_nugget", null)
    processOre("heptasartorite", "mercury", "selenium", "cobaltite", "tellurium", "lorandite", "normal", null, null, null)
    processOre("herderite", "distilled_water", "fluoroapatite", "fluoroapatite", "fluorite", "iodine", "gem", null, null, "gtceu:herderite_gem")
    processOre("hexagonite", "distilled_water", "magnesite", "magnesite", "zincite", "magnanese", "gem", null, null, "gtceu:hexagonite_gem")
    processOre("hubnerite", "mercury", "pyrolusite", "brookite", "ferberite", "wolframite", "normal", null, null, null)
    processOre("ilmenite", "sodium_persulfate", "iron", "ilmenite_slag", "rutile", "rutile", "magnetic", "iron", "minecraft:iron_nugget", null)
    processOre("indite", "hydrobromic_acid", "spinel", "dzhalindite", "pyrite", "tellurium", "normal", null, null, null)
    processOre("iodargyrite", "hydrobromic_acid", "galena", "bromoargyrite", "silver", "bromoargyrite", "normal", null, null, null)
    processOre("iridosmine", "distilled_water", "osmium", "osmium", "iridium", "rhodium", "normal", null, null, null)
    processOre("iron", "sodium_persulfate", "nickel", "gold", "tin", "tin", "normal", null, null, null)
    processOre("kaemanite", "distilled_water", "niobium", "niobium", "trinium_sulfide", "trinium", "normal", null, null, null)
    processOre("kolbeckite", "distilled_water", "yttrium", "yttrium", "phosphosiderite", "rare_earth", "normal", null, null, null)
    processOre("kyanite", "distilled_water", "talc", "talc", "aluminium", "silicon", "normal", null, null, null)
    processOre("labyrinthite", "hexafluorosilicic_acid", "fluorite", "thallium", "cerium", "rubidium", "normal", null, null, null)
    processOre("lapis", "distilled_water", "lazurite", "lazurite", "sodalite", "pyrite", "gem", null, null, "minecraft:lapis_lazuli")
    processOre("laurite", "distilled_water", "pyrite", "pyrite", "ruthenium", "rhodium", "normal", null, null, null)
    processOre("lazurite", "distilled_water", "sodalite", "sodalite", "lapis", "lapis", "gem", null, null, "gtceu:lazurite_gem")
    processOre("lead", "distilled_water", "silver", "silver", "sulfur", "sulfur", "normal", null, null, null)
    processOre("legrandite", "distilled_water", "goethite", "goethite", "pyrite", "realgar", "gem", null, null, "gtceu:legrandite_gem")
    processOre("lepidolite", "nitric_acid", "lithium", "rubidium", "caesium", "boron", "normal", null, null, null)
    processOre("yellow_limonite", "sodium_persulfate", "nickel", "cobalt_oxide", "goethite", "cobalt_oxide", "magnetic", "iron", "minecraft:iron_nugget", null)
    processOre("lindgrenite", "sodium_persulfate", "powellite", "rheniite", "molybdenite", "malachite", "gem", null, null, "gtceu:lindgrenite_gem")
    processOre("lithium", "distilled_water", "lithium", "lithium", "sodium", "lithium", "normal", null, null, null)
    processOre("lorandite", "mercury", "realgar", "stibnite", "cinnabar", "gold", "normal", null, null, null)
    processOre("madocite", "mercury", "sphalerite", "selenium", "stibnite", "pyrite", "normal", null, null, null)
    processOre("magnesite", "distilled_water", "magnesium", "magnesium", "magnesium", "cobaltite", "normal", null, null, null)
    processOre("magnetite", "mercury", "iron", "gold", "gold", "gold", "magnetic", "gold", "minecraft:gold_nugget", null)
    processOre("malachite", "sodium_persulfate", "goethite", "zincite", "calcite", "zincite", "gem", null, null, "gtceu:malachite_gem")
    processOre("manganite", "distilled_water", "goethite", "goethite", "pyrolusite", "barite", "gem", null, null, "gtceu:manganite_gem")
    processOre("manganvesuvianite", "hexafluorosilicic_acid", "calcite", "strontianite", "grossular", "manganite", "gem", null, null, "gtceu:manganvesuvianite_gem")
    processOre("melonite", "mercury", "pentlandite", "platinum", "nickel", "sperrylite", "normal", null, null, null)
    processOre("merenskyite", "mercury", "chalcopyrite", "sperrylite", "temagamite", "palladium", "normal", null, null, null)
    processOre("mica", "distilled_water", "potassium", "potassium", "aluminium", "aluminium", "normal", null, null, null)
    processOre("microcline", "distilled_water", "alunite", "alunite", "rubidium", "thallium", "normal", null, null, null)
    processOre("milarite", "distilled_water", "chrysoberyl", "chrysoberyl", "emerald", "pezzottaite", "gem", null, null, "gtceu:milarite_gem")
    processOre("mixite", "sodium_persulfate", "malachite", "azurite", "monazite", "xenotime", "gem", null, null, "gtceu:mixite_gem")
    processOre("mohite", "mercury", "tetrahedrite", "bronze", "cassiterite", "chalcocite", "normal", null, null, null)
    processOre("moissanite", "distilled_water", "diamond", "diamond", "moissanite", "germanium", "gem", null, null, "gtceu:moissanite_gem")
    processOre("molybdenite", "nitric_acid", "molybdenum", "rheniite", "sulfur", "quartzite", "normal", null, null, null)
    processOre("molybdenum", "distilled_water", "molybdenite", "molybdenite", "molybdenum_trioxide", "tungsten_trioxide", "normal", null, null, null)
    processOre("monazite", "distilled_water", "thorium", "thorium", "neodymium", "rare_earth", "gem", null, null, "gtceu:monazite_gem")
    processOre("morganite", "distilled_water", "lepidolite", "lepidolite", "euclase", "aquamarine", "gem", null, null, "gtceu:morganite_gem")
    processOre("mottramite", "sodium_persulfate", "calcite", "russellite", "vanadinite", "vanadium_magnetite", "normal", null, null, null)
    processOre("musgravite", "distilled_water", "taaffeite", "taaffeite", "morganite", "thorium", "gem", null, null, "gtceu:musgravite_gem")
    processOre("nambulite", "hexafluorosilicic_acid", "aragonite", "magnesite", "almandine", "grossular", "gem", null, null, "gtceu:nambulite_gem")
    processOre("naquadah", "distilled_water", "sulfur", "sulfur", "barite", "enriched_naquadah", "magnetic", "enriched_naquadah", "enriched_naquadah", null)
    processOre("neodymium", "distilled_water", "rare_earth", "rare_earth", "rare_earth", "rare_earth", "normal", null, null, null)
    processOre("nether_quartz", "distilled_water", "quartzite", "quartzite", "quartzite", "quartzite", "gem", null, null, "minecraft:quartz")
    processOre("netherite_scrap", "distilled_water", "obsidian", "obsidian", "obsidian", "rarest_metal_mixture", "normal", null, null, null)
    processOre("nickel", "mercury", "cobalt", "platinum", "iron", "platinum", "magnetic", "iron", "minecraft:iron_nugget", null)
    processOre("oilsands", "distilled_water", "clay", "clay", "oilsands", "granitic_mineral_sand", "normal", null, null, null)
    processOre("olivine", "distilled_water", "pyrope", "pyrope", "magnesium", "manganese", "gem", null, null, "gtceu:olivine_gem")
    processOre("opal", "distilled_water", "opal", "opal", "basaltic_mineral_sand", "black_opal", "gem", null, null, "gtceu:opal_gem")
    processOre("osmiridium", "distilled_water", "iridium", "iridium", "osmium", "ruthenium", "normal", null, null, null)
    processOre("otavite", "hydrobromic_acid", "aragonite", "strontianite", "malachite", "witherite", "gem", null, null, "gtceu:otavite_gem")
    processOre("palladium", "distilled_water", "platinum", "platinum", "palladium", "merenskyite", "normal", null, null, null)
    processOre("pentlandite", "sodium_persulfate", "iron", "cobalt", "sulfur", "cobalt", "magnetic", "iron", "minecraft:iron_nugget", null)
    processOre("pezzottaite", "hexafluorosilicic_acid", "morganite", "caesium", "manganese", "rubidium", "gem", null, null, "gtceu:pezzottaite_gem")
    processOre("phosphophyllite", "distilled_water", "triphyllite", "triphyllite", "chalcopyrite", "legrandite", "gem", null, null, "gtceu:phosphophyllite_gem")
    processOre("phosphosiderite", "distilled_water", "triphyllite", "triphyllite", "turquoise", "vivianite", "gem", null, null, "gtceu:phosphosiderite_gem")
    processOre("pitchblende", "distilled_water", "thorium_232", "thorium_232", "uraninite", "lead", "normal", null, null, null)
    processOre("platinum", "mercury", "nickel", "palladium", "nickel", "cobalt", "normal", null, null, null)
    processOre("plutonium", "distilled_water", "uraninite", "uraninite", "lead", "uraninite", "normal", null, null, null)
    processOre("pollucite", "distilled_water", "caesium", "caesium", "aluminium", "potassium", "normal", null, null, null)
    processOre("powellite", "distilled_water", "iron", "iron", "potassium", "molybdenite", "normal", null, null, null)
    processOre("purpurite", "distilled_water", "phosphosiderite", "phosphosiderite", "hematite", "amethyst", "normal", null, null, null)
    processOre("pyrite", "distilled_water", "sulfur", "sulfur", "tricalcium_phosphate", "iron", "magnetic", "iron", "minecraft:iron_nugget", null)
    processOre("pyrochlore", "distilled_water", "apatite", "apatite", "calcium", "niobium", "normal", null, null, null)
    processOre("pyrolusite", "distilled_water", "manganese", "manganese", "tantalite", "niobium", "normal", null, null, null)
    processOre("pyrope", "distilled_water", "red_garnet", "red_garnet", "magnesium", "magnesium", "gem", null, null, "gtceu:pyrope_gem")
    processOre("quartzite", "distilled_water", "certus_quartz", "certus_quartz", "barite", "barite", "gem", null, null, "gtceu:quartzite_gem")
    processOre("realgar", "distilled_water", "sulfur", "sulfur", "antimony", "barite", "gem", null, null, "gtceu:realgar_gem")
    processOre("red_beryl", "distilled_water", "emerald", "emerald", "pyrolusite", "pezzottaite", "gem", null, null, "gtceu:red_beryl_gem")
    processOre("red_garnet", "distilled_water", "spessartine", "spessartine", "pyrope", "almandine", "gem", null, null, "gtceu:red_garnet_gem")
    // processOre("redstone", "distilled_water", "cinnabar", "cinnabar", "rare_earth", "glowstone", "normal", null, null, null)
    processOre("rheniite", "mercury", "sphalerite", "molybdenite", "molybdenite", "laurite", "normal", null, null, null)
    processOre("rhodplumsite", "mercury", "teallite", "ruthenium", "sperrylite", "platinum", "normal", null, null, null)
    processOre("rock_salt", "distilled_water", "salt", "salt", "borax", "borax", "gem", null, null, "gtceu:rock_salt_gem")
    processOre("rubellite", "hexafluorosilicic_acid", "lepidolite", "molybdenite", "chromite", "microcline", "gem", null, null, "gtceu:rubellite_gem")
    processOre("ruby", "distilled_water", "chromium", "chromium", "red_garnet", "red_garnet", "gem", null, null, "gtceu:ruby_gem")
    processOre("russellite", "mercury", "cassiterite", "tungstite", "scheelite", "topaz", "normal", null, null, null)
    processOre("rutile", "distilled_water", "iron", "iron", "quartzite", "rutile", "gem", null, null, "gtceu:rutile_gem")
    processOre("salt", "distilled_water", "rock_salt", "rock_salt", "borax", "borax", "gem", null, null, "gtceu:salt_gem")
    processOre("saltpeter", "nitric_acid", "saltpeter", "thallium", "potassium", "salt", "normal", null, null, null)
    processOre("samarskite-yb", "distilled_water", "yellow_garnet", "yellow_garnet", "uraninite", "yttrium", "normal", null, null, null)
    processOre("sapphire", "distilled_water", "aluminium", "aluminium", "green_sapphire", "green_sapphire", "gem", null, null, "gtceu:sapphire_gem")
    processOre("scheelite", "distilled_water", "manganese", "manganese", "molybdenum", "calcium", "normal", null, null, null)
    processOre("schizolite", "hexafluorosilicic_acid", "spodumene", "pollucite", "sodalite", "lapis", "gem", null, null, "schizolite_gem")
    processOre("selenite", "distilled_water", "gypsum", "gypsum", "calcite", "selenium", "gem", null, null, "gtceu:selenite_gem")
    processOre("cooperite", "mercury", "nickel", "palladium", "nickel", "cobalt", "normal", null, null, null)
    processOre("silver", "mercury", "lead", "gold", "sulfur", "sulfur", "normal", null, null, null)
    processOre("snowchestite", "distilled_water", "chalcopyrite", "chalcopyrite", "vanadium_magnetite", "naquadah_hydroxide", "normal", null, null, null)
    processOre("soapstone", "distilled_water", "silicon_dioxide", "silicon_dioxide", "magnesium", "calcite", "normal", null, null, null)
    processOre("sodalite", "distilled_water", "lazurite", "lazurite", "lapis", "lapis", "gem", null, null, "gtceu:sodalite_gem")
    processOre("sperrylite", "nitric_acid", "platinum", "palladium", "nickel", "palladium", "gem", null, null, "gtceu:sperrylite_gem")
    processOre("spessartine", "distilled_water", "red_garnet", "red_garnet", "manganese", "manganese", "gem", null, null, "gtceu:spessartine_gem")
    processOre("sphalerite", "sodium_persulfate", "yellow_garnet", "zinc", "gallium", "cadmium", "normal", null, null, null)
    processOre("spinel", "distilled_water", "olivine", "olivine", "chromite", "ruby", "gem", null, null, "gtceu:spinel_gem")
    processOre("spodumene", "distilled_water", "aluminium", "aluminium", "lithium", "rubidium", "normal", null, null, null)
    processOre("stibiotantalite", "distilled_water", "cassiterite", "cassiterite", "niobium", "tantalite", "gem", null, null, "gtceu:stibiotantalite_gem")
    processOre("stibnite", "sodium_persulfate", "antimony_trioxide", "cinnabar", "antimony", "cinnabar", "normal", null, null, null)
    processOre("stolzite", "nitric_acid", "lead", "molybdenum", "manganese", "molybdenum", "gem", null, null, "gtceu:stolzite_gem")
    processOre("strontianite", "distilled_water", "aragonite", "aragonite", "barite", "celestine", "gem", null, null, "gtceu:strontianite_gem")
    processOre("suanite", "distilled_water", "magnesite", "magnesite", "malachite", "gold", "normal", null, null, null)
    processOre("sulfur", "distilled_water", "sulfur", "sulfur", "sulfur", "selenium", "normal", null, null, null)
    processOre("taaffeite", "distilled_water", "spinel", "spinel", "chrysoberyl", "musgravite", "gem", null, null, "gtceu:taaffeite_gem")
    processOre("talc", "distilled_water", "clay", "clay", "carbon", "clay", "normal", null, null, null)
    processOre("tantalite", "distilled_water", "manganese", "manganese", "niobium", "tantalum", "normal", null, null)
    processOre("tarapacaite", "distilled_water", "chromite", "chromite", "potassium_chromate", "potassium_chromate", "normal", null, null, null)
    processOre("teallite", "mercury", "galena", "silver", 'bismuth', "stibnite", "normal", null, null, null)
    processOre("temagamite", "nitric_acid", "melonite", "silver", "chalcopyrite", "galena", "normal", null, null, null)
    processOre("tetrahedrite", "sodium_persulfate", "antimony", "cadmium", "zinc", "cadmium", "normal", null, null, null)
    processOre("thorium", "distilled_water", "uraninite", "uraninite", "lead", "lead", "normal", null, null, null)
    processOre("thortveitite", "hexafluorosilicic_acid", "scandium", "praseodymium", "nether_quartz", "rare_earth", "normal", null, null, null)
    processOre("tin", "sodium_persulfate", "iron", "zinc", "zinc", "zinc", "magnetic", "iron", "minecraft:iron_nugget", null)
    processOre("titanite", "nitric_acid", "calcium", "rare_earth", "rutile", "fluorite", "gem", null, null, "gtceu:titanite_gem")
    processOre("topaz", "distilled_water", "blue_topaz", "blue_topaz", "blue_topaz", "blue_topaz", "gem", null, null, "gtceu:topaz_gem")
    processOre("torbernite", "sodium_persulfate", "uraninite", "plutonium", "lindgrenite", "azurite", "gem", null, null, "gtceu:torbernite_gem")
    processOre("tricalcium_phosphate", "distilled_water", "apatite", "apatite", "phosphate", "pyrochlore", "normal", null, null, null)
    processOre("triphyllite", "distilled_water", "phosphophyllite", "phosphophyllite", "goethite", "manganese", "gem", null, null, "gtceu:triphyllite_gem")
    processOre("triplite", "distilled_water", "red_garnet", "red_garnet", "almandine", "phosphosiderite", "gem", null, null, "gtceu:triplite_gem")
    processOre("trona", "distilled_water", "sodium", "sodium", "soda_ash", "soda_ash", "normal", null, null, null)
    processOre("tungstate", "mercury", "manganese", "lithium", "silver", "lithium", "normal", null, null, null)
    processOre("tungstite", "distilled_water", "goethite", "goethite", "tungstate", "scheelite", "normal", null, null, null)
    processOre("turquoise", "sodium_persulfate", "charged_certus_quartz", "torbernite", "kyanite", "lindgrenite", "gem", null, null, "gtceu:turquoise_gem")
    processOre("tusionite", "distilled_water", "cassiterite", "cassiterite", "borax", "manganese", "gem", null, null, "gtceu:tusionite_gem")
    processOre("ulexite", "distilled_water", "trona", "trona", "borax", "borax", "gem", null, null, "gtceu:ulexite_gem")
    processOre("ullmannite", "mercury", "pyrite", "arsenic", "stibnite", "cobaltite", "normal", null, null, null)
    processOre("umangite", "sodium_persulfate", "chalcocite", "chalcocite", "tellurium", "mohite", "selenium", "normal", null, null, null)
    processOre("uraninite", "distilled_water", "uraninite", "uraninite", "thorium_232", "silver", "normal", null, null, null)
    processOre("uvarovite", "distilled_water", "calcium", "calcium", "chromium", "silicon", "gem", null, null, "gtceu:uvarovite_gem")
    processOre("vanadinite", "mercury", "yellow_limonite", "hubnerite", "galena", "ferberite", "gem", null, null, "gtceu:vanadinite_gem")
    processOre("vanadium_magnetite", "distilled_water", "magnetite", "magnetite", "magnetite", "vanadium", "magnetic", "gold", "minecraft:gold_nugget", null)
    processOre("vayrynenite", "distilled_water", "fluoroapatite", "fluoroapatite", "red_beryl", "morganite", "gem", null, null, "gtceu:vayrynenite_gem")
    processOre("villiaumite", "distilled_water", "sodalite", "sodalite", "lazurite", "villiaumite", "gem", null, null, "gtceu:villiaumite_gem")
    processOre("vivianite", "distilled_water", "aragonite", "aragonite", "magnesite", "phosphosiderite", "gem", null, null, "gtceu:vivianite_gem")
    processOre("wakefieldite", "sodium_persulfate", "xenotime", "neodymium", "monazite", "cerium", "normal", null, null, null)
    processOre("witherite", "distilled_water", "aragonite", "aragonite", "strontianite", "otavite", "gem", null, null, "gtceu:witherite_gem")
    processOre("wodginite", "distilled_water", "tantalite", "tantalite", "microcline", "niobium", "normal", null, null, null)
    processOre("wolframite", "nitric_acid", "iron", "tungstite", "manganese", "fluorite", "normal", null, null, null)
    processOre("wulfenite", "distilled_water", "iron", "iron", "manganese", "manganese", "normal", null, null, null)
    processOre("xanthoconite", "mercury", "galena", "sperrylite", "teallite", "arsenic", "gem", null, null, "gtceu:xanthoconite_gem")
    processOre("xenotime", "nitric_acid", "yttrium", "samarium", "rare_earth", "samarium", "gem", null, null, "gtceu:xenotime_gem")
    processOre("xilingolite", "mercury", "teallite", "xanthoconite", "sphalerite", "molybdenite", "normal", null, null, null)
    processOre("yellow_garnet", "distilled_water", "andradite", "andradite", "grossular", "uvarovite", "gem", null, null, "gtceu:yellow_garnet_gem")
    processOre("zavaritskite", "distilled_water", "fluorite", "fluorite", "cassiterite", "gold", "normal", null, null, null)
    processOre("zeolite", "distilled_water", "calcium", "calcium", "silicon", "aluminium", "normal", null, null, null)
    processOre("zincochromite", "sodium_persulfate", "spinel", "uraninite", "chromite", "zincite", "normal", null, null, null)
    processOre("zincite", "distilled_water", "iron", "iron", "manganese", "manganese", "normal", null, null, null)
    processOre("zircon", "distilled_water", "citrine", "citrine", "anatase", "hafnium", "gem", null, null, "gtceu:zircon_gem")
    processOre("zoisite", "distilled_water", "gypsum", "gypsum", "hexagonite", "rubellite", "gem", null, null, "gtceu:zoisite_gem")

    // Mod id dust issues - manual recipes
    event.recipes.gtceu.ore_processing_factory(`certus_quartz_full_processing`)
        .itemInputs(`128x gtceu:crushed_certus_quartz_ore`)
        .inputFluids(`gtceu:distilled_water 8000`)
        .itemOutputs(`256x ae2:certus_quartz_dust`, 
            `50x gtceu:nether_quartz_dust`,
            `90x gtceu:nether_quartz_dust`,
            `82x gtceu:barite_dust`,
            `18x gtceu:barite_dust`,
            `45x ae2:certus_quartz_crystal`,
            `13x gtceu:flawless_certus_quartz_gem`,
            `4x gtceu:exquisite_certus_quartz_gem`)
        .duration(240)
        .EUt(GTValues.VA[GTValues.ZPM])
    event.recipes.gtceu.ore_processing_factory(`electrotine_full_processing`)
        .itemInputs(`128x gtceu:crushed_electrotine_ore`)
        .inputFluids(`gtceu:distilled_water 8000`)
        .itemOutputs(`256x gtceu:electrotine_dust`, 
            `50x minecraft:redstone`,
            `90x minecraft:redstone`,
            `82x gtceu:electrum_dust`,
            `18x gtceu:diamond_dust`)
        .duration(240)
        .EUt(GTValues.VA[GTValues.ZPM])
    event.recipes.gtceu.ore_processing_factory(`redstone_full_processing`)
        .itemInputs(`128x gtceu:crushed_redstone_ore`)
        .inputFluids(`gtceu:distilled_water 8000`)
        .itemOutputs(`256x minecraft:redstone`, 
            `50x gtceu:cinnabar_dust`,
            `90x gtceu:cinnabar_dust`,
            `82x gtceu:rare_earth_dust`,
            `18x minecraft:glowstone_dust`)
        .duration(240)
        .EUt(GTValues.VA[GTValues.ZPM])
    event.recipes.gtceu.ore_processing_factory(`cinnabar_full_processing`)
        .itemInputs(`128x gtceu:crushed_cinnabar_ore`)
        .inputFluids(`gtceu:distilled_water 8000`)
        .itemOutputs(`256x gtceu:cinnabar_dust`, 
            `50x minecraft:redstone`,
            `90x minecraft:redstone`,
            `82x gtceu:sulfur_dust`,
            `18x minecraft:glowstone_dust`,
            `45x gtceu:cinnabar_gem`,
            `13x gtceu:flawless_cinnabar_gem`,
            `4x gtceu:exquisite_cinnabar_gem`)
        .duration(240)
        .EUt(GTValues.VA[GTValues.ZPM])
    event.recipes.gtceu.ore_processing_factory(`cavansite_full_processing`)
        .itemInputs(`128x gtceu:crushed_cavansite_ore`)
        .inputFluids(`gtceu:distilled_water 8000`)
        .itemOutputs(`256x gtceu:cavansite_dust`, 
            `50x ae2:certus_quartz_dust`,
            `90x ae2:certus_quartz_dust`,
            `82x gtceu:calcium_dust`,
            `18x gtceu:vanadium_pentoxide_dust`,
            `45x gtceu:cavansite_gem`,
            `13x gtceu:flawless_cavansite_gem`,
            `4x gtceu:exquisite_cavansite_gem`)
        .duration(240)
        .EUt(GTValues.VA[GTValues.ZPM])
})