/**
 * Polymerizer single/multiblock
 */

ServerEvents.recipes(event => {
    // MB Recipe goes here


    // Polyethylene
    event.remove({id:"gtceu:chemical_reactor/polyethylene_from_air"})
    event.remove({id:"gtceu:chemical_reactor/polyethylene_from_oxygen"})
    event.remove({id:"gtceu:large_chemical_reactor/polyethylene_from_air"})
    event.remove({id:"gtceu:large_chemical_reactor/polyethylene_from_oxygen"})
    event.remove({id:"gtceu:large_chemical_reactor/polyethylene_from_tetrachloride_air"})
    event.remove({id:"gtceu:large_chemical_reactor/polyethylene_from_tetrachloride_oxygen"})
    event.recipes.gtceu.polymerization("polyethylene_from_air")
        .inputFluids("gtceu:ethylene 144", "gtceu:air 1000")
        .outputFluids("gtceu:polyethylene 144")
        .circuit(1)
        .EUt(GTValues.VA[GTValues.LV])
        .duration(160)
    event.recipes.gtceu.polymerization("polyethylene_from_oxygen")
        .inputFluids("gtceu:ethylene 144", "gtceu:oxygen 1000")
        .outputFluids("gtceu:polyethylene 216")
        .circuit(1)
        .EUt(GTValues.VA[GTValues.LV])
        .duration(160)
    event.recipes.gtceu.polymerization("polyethylene_from_tetrachloride_air")
        .inputFluids("gtceu:ethylene 2160", "gtceu:air 7500")
        .outputFluids("gtceu:polyethylene 3240")
        .circuit(3)
        .EUt(GTValues.VA[GTValues.LV])
        .duration(160)
    event.recipes.gtceu.polymerization("polyethylene_from_tetrachloride_oxygen")
        .inputFluids("gtceu:ethylene 2160", "gtceu:oxygen 7500", "gtceu:titanium_tetrachloride 100")
        .outputFluids("gtceu:polyethylene 4320")
        .circuit(3)
        .EUt(GTValues.VA[GTValues.LV])
        .duration(160)
    event.recipes.gtceu.polymerization("polyethylene_hardmode")
        .inputFluids(Fluid.of("gtceu:ethylene", 2160), Fluid.of("gtceu:oxygen", 7500))
        .itemInputs("#forge:dusts/phthalic_anhydride")
        .circuit(7)
        .outputFluids(Fluid.of("gtceu:polyethylene", 4320))
        .EUt(GTValues.VA[GTValues.LV])
        .duration(800)

    // Polyvinyl Chloride (PVC)
    event.remove({id:"gtceu:chemical_reactor/polyvinyl_chloride_from_air"})
    event.remove({id:"gtceu:chemical_reactor/polyvinyl_chloride_from_oxygen"})
    event.remove({id:"gtceu:large_chemical_reactor/polyvinyl_chloride_from_air"})
    event.remove({id:"gtceu:large_chemical_reactor/polyvinyl_chloride_from_oxygen"})
    event.remove({id:"gtceu:large_chemical_reactor/polyvinyl_chloride_from_tetrachloride_air"})
    event.remove({id:"gtceu:large_chemical_reactor/polyvinyl_chloride_from_tetrachloride_oxygen"})
    event.recipes.gtceu.polymerization("polyvinyl_chloride_from_air")
        .inputFluids("gtceu:vinyl_chloride 144", "gtceu:air 1000")
        .outputFluids("gtceu:polyvinyl_chloride 144")
        .circuit(1)
        .EUt(GTValues.VA[GTValues.LV])
        .duration(160)
    event.recipes.gtceu.polymerization("polyvinyl_chloride_from_oxygen")
        .inputFluids("gtceu:vinyl_chloride 144", "gtceu:oxygen 1000")
        .outputFluids("gtceu:polyvinyl_chloride 216")
        .circuit(1)
        .EUt(GTValues.VA[GTValues.LV])
        .duration(160)
    event.recipes.gtceu.polymerization("polyvinyl_chloride_from_tetrachloride_air")
        .inputFluids("gtceu:vinyl_chloride 2160", "gtceu:air 7500")
        .outputFluids("gtceu:polyvinyl_chloride 3240")
        .circuit(3)
        .EUt(GTValues.VA[GTValues.LV])
        .duration(160)
    event.recipes.gtceu.polymerization("polyvinyl_chloride_from_tetrachloride_oxygen")
        .inputFluids("gtceu:vinyl_chloride 2160", "gtceu:oxygen 7500", "gtceu:titanium_tetrachloride 100")
        .outputFluids("gtceu:polyvinyl_chloride 4320")
        .circuit(3)
        .EUt(GTValues.VA[GTValues.LV])
        .duration(160)
    event.recipes.gtceu.polymerization("polyvinyl_chloride_hardmode")
        .inputFluids(Fluid.of("gtceu:vinyl_chloride", 2160), Fluid.of("gtceu:oxygen", 7500))
        .itemInputs("#forge:dusts/phthalic_anhydride")
        .circuit(7)
        .outputFluids(Fluid.of("gtceu:polyvinyl_chloride", 4320))
        .EUt(GTValues.VA[GTValues.LV])
        .duration(800)

    // Polyphenylene Sulfide (PPS)
    event.remove({id:"gtceu:chemical_reactor/polyphenylene_sulfide_from_air"})
    event.remove({id:"gtceu:chemical_reactor/polyphenylene_sulfide_from_oxygen"})
    event.remove({id:"gtceu:large_chemical_reactor/polyphenylene_sulfide_from_air"})
    event.remove({id:"gtceu:large_chemical_reactor/polyphenylene_sulfide_from_oxygen"})
    event.recipes.gtceu.polymerization("polyphenylene_sulfide_from_air")
        .inputFluids("gtceu:dichlorobenzene 1000", "gtceu:air 16000")
        .itemInputs("3x gtceu:sodium_sulfide_dust")
        .outputFluids("gtceu:polyphenylene_sulfide 1000")
        .itemOutputs("4x gtceu:salt_dust")
        .EUt(360)
        .duration(240)
    event.recipes.gtceu.polymerization("polyphenylene_sulfide_from_oxygen")
        .inputFluids("gtceu:dichlorobenzene 1000", "gtceu:oxygen 8000")
        .itemInputs("3x gtceu:sodium_sulfide_dust")
        .outputFluids("gtceu:polyphenylene_sulfide 1000")
        .itemOutputs("4x gtceu:salt_dust")
        .EUt(360)
        .duration(240)

    // Polybenzimidazole (PBI)
    event.remove({id:"gtceu:chemical_reactor/polybenzimidazole"})
    event.remove({id:"gtceu:large_chemical_reactor/polybenzimidazole"})
    event.recipes.gtceu.polymerization("polybenzimidazole")
        .inputFluids("gtceu:diaminobenzidine 1000", "gtceu:diphenyl_isophthalate 1000")
        .outputFluids("gtceu:phenol 1000", "gtceu:polybenzimidazole 1008")
        .duration(100)
        .EUt(7680)

    // Polyvinyl Butyral (PVB)
    event.remove({id:"gtceu:chemical_reactor/polyvinyl_butyral"})
    event.remove({id:"gtceu:large_chemical_reactor/polyvinyl_butyral"})
    event.recipes.gtceu.polymerization("polyvinyl_butyral")
        .inputFluids("gtceu:butyraldehyde 250", "gtceu:polyvinyl_acetate 144")
        .outputFluids("gtceu:polyvinyl_butyral 144")
        .duration(400)
        .EUt(480)

    // Polytetrafluoroethylene (PTFE)
    event.remove({id:"gtceu:chemical_reactor/ptfe_from_air"})
    event.remove({id:"gtceu:chemical_reactor/ptfe_from_oxygen"})
    event.remove({id:"gtceu:large_chemical_reactor/ptfe_from_air"})
    event.remove({id:"gtceu:large_chemical_reactor/ptfe_from_oxygen"})
    event.remove({id:"gtceu:large_chemical_reactor/ptfe_from_tetrachloride_air"})
    event.remove({id:"gtceu:large_chemical_reactor/ptfe_from_tetrachloride_oxygen"})
    event.recipes.gtceu.polymerization("ptfe_from_air")
        .inputFluids("gtceu:tetrafluoroethylene 144", "gtceu:air 1000")
        .outputFluids("gtceu:polytetrafluoroethylene 144")
        .circuit(1)
        .EUt(GTValues.VA[GTValues.LV])
        .duration(160)
    event.recipes.gtceu.polymerization("ptfe_from_oxygen")
        .inputFluids("gtceu:tetrafluoroethylene 144", "gtceu:oxygen 1000")
        .outputFluids("gtceu:polytetrafluoroethylene 216")
        .circuit(1)
        .EUt(GTValues.VA[GTValues.LV])
        .duration(160)
    event.recipes.gtceu.polymerization("ptfe_from_tetrachloride_air")
        .inputFluids("gtceu:tetrafluoroethylene 2160", "gtceu:air 7500")
        .outputFluids("gtceu:polytetrafluoroethylene 3240")
        .circuit(3)
        .EUt(GTValues.VA[GTValues.LV])
        .duration(160)
    event.recipes.gtceu.polymerization("ptfe_from_tetrachloride_oxygen")
        .inputFluids("gtceu:tetrafluoroethylene 2160", "gtceu:oxygen 7500", "gtceu:titanium_tetrachloride 100")
        .outputFluids("gtceu:polytetrafluoroethylene 4320")
        .circuit(3)
        .EUt(GTValues.VA[GTValues.LV])
        .duration(160)
    event.recipes.gtceu.polymerization("ptfe_hardmode")
        .inputFluids(Fluid.of("gtceu:tetrafluoroethylene", 2160), Fluid.of("gtceu:oxygen", 7500))
        .itemInputs("#forge:dusts/phthalic_anhydride")
        .circuit(7)
        .outputFluids(Fluid.of("gtceu:polytetrafluoroethylene", 4320))
        .EUt(GTValues.VA[GTValues.LV])
        .duration(800)

    // Polyvinyl Acetate (PVA)
    event.remove({id:"gtceu:chemical_reactor/polyvinyl_acetate_from_air"})
    event.remove({id:"gtceu:chemical_reactor/polyvinyl_acetate_from_oxygen"})
    event.remove({id:"gtceu:large_chemical_reactor/polyvinyl_acetate_from_air"})
    event.remove({id:"gtceu:large_chemical_reactor/polyvinyl_acetate_from_oxygen"})
    event.remove({id:"gtceu:large_chemical_reactor/polyvinyl_acetate_from_tetrachloride_air"})
    event.remove({id:"gtceu:large_chemical_reactor/polyvinyl_acetate_from_tetrachloride_oxygen"})
    event.recipes.gtceu.polymerization("polyvinyl_acetate_from_air")
        .inputFluids("gtceu:vinyl_acetate 144", "gtceu:air 1000")
        .outputFluids("gtceu:polyvinyl_acetate 144")
        .circuit(1)
        .EUt(GTValues.VA[GTValues.LV])
        .duration(160)
    event.recipes.gtceu.polymerization("polyvinyl_acetate_from_oxygen")
        .inputFluids("gtceu:vinyl_acetate 144", "gtceu:oxygen 1000")
        .outputFluids("gtceu:polyvinyl_acetate 216")
        .circuit(1)
        .EUt(GTValues.VA[GTValues.LV])
        .duration(160)
    event.recipes.gtceu.polymerization("polyvinyl_acetate_from_tetrachloride_air")
        .inputFluids("gtceu:vinyl_acetate 2160", "gtceu:air 7500")
        .outputFluids("gtceu:polyvinyl_acetate 3240")
        .circuit(3)
        .EUt(GTValues.VA[GTValues.LV])
        .duration(160)
    event.recipes.gtceu.polymerization("polyvinyl_acetate_from_tetrachloride_oxygen")
        .inputFluids("gtceu:vinyl_acetate 2160", "gtceu:oxygen 7500", "gtceu:titanium_tetrachloride 100")
        .outputFluids("gtceu:polyvinyl_acetate 4320")
        .circuit(3)
        .EUt(GTValues.VA[GTValues.LV])
        .duration(160)
    event.recipes.gtceu.polymerization("polyvinyl_acetate_hardmode")
        .inputFluids(Fluid.of("gtceu:vinyl_acetate", 2160), Fluid.of("gtceu:oxygen", 7500))
        .itemInputs("#forge:dusts/phthalic_anhydride")
        .circuit(7)
        .outputFluids(Fluid.of("gtceu:polyvinyl_acetate", 4320))
        .EUt(GTValues.VA[GTValues.LV])
        .duration(800)

    // Polycaprolactam (PCL)
    event.recipes.gtceu.polymerization("polycaprolactam")
        .inputFluids("gtceu:nitrogen 1000")
        .itemInputs("gtceu:caprolactam_dust")
        .circuit(1)
        .outputFluids("gtceu:polycaprolactam 144")
        .duration(150)
        .EUt(120)

    // Polyether Ether Ketone (PEEK)
    event.recipes.gtceu.polymerization("polyether_ether_ketone")
        .chancedFluidInput("gtceu:sulfolane 500", 700, 0)
        .itemInputs("24x gtceu:4-4-difluorobenzophenone_dust", "14x gtceu:hydroquinone_dust", "5x gtceu:soda_ash_dust")
        .itemOutputs("4x gtceu:sodium_fluoride_dust")
        .outputFluids("gtceu:polyether_ether_ketone 1000", "gtceu:carbon_dioxide 1000", "minecraft:water 1000")
        .duration(400)
        .EUt(GTValues.VA[GTValues.ZPM])

    // Polyethyl Cyanoacrylate (PECA)
    event.recipes.gtceu.polymerization("polyethyl_cyanoacrylate")
        .chancedFluidInput("gtceu:dimethyl_sulfoxide 200", 100, 0)
        .inputFluids("gtceu:ethyl_cyanoacrylate 144", "minecraft:water 1000")
        .outputFluids("gtceu:polyethyl_cyanoacrylate 144")
        .duration(300)
        .EUt(GTValues.VA[GTValues.LuV])
    event.recipes.gtceu.polymerization("polyethyl_cyanoacrylate_distilled")
        .chancedFluidInput("gtceu:dimethyl_sulfoxide 200", 100, 0)
        .inputFluids("gtceu:ethyl_cyanoacrylate 96", "gtceu:distilled_water 1000")
        .outputFluids("gtceu:polyethyl_cyanoacrylate 144")
        .duration(300)
        .EUt(GTValues.VA[GTValues.LuV])

    // Polypropylene (PPE)
    event.recipes.gtceu.polymerization("polypropylene_from_air")
        .inputFluids("gtceu:propene 144", "gtceu:air 1000")
        .outputFluids("gtceu:polypropylene 144")
        .circuit(1)
        .EUt(GTValues.VA[GTValues.MV])
        .duration(160)
    event.recipes.gtceu.polymerization("polypropylene_from_oxygen")
        .inputFluids("gtceu:propene 144", "gtceu:oxygen 1000")
        .outputFluids("gtceu:polypropylene 216")
        .circuit(1)
        .EUt(GTValues.VA[GTValues.MV])
        .duration(160)
    event.recipes.gtceu.polymerization("polypropylene_from_tetrachloride_air")
        .inputFluids("gtceu:propene 2160", "gtceu:air 7500")
        .outputFluids("gtceu:polypropylene 3240")
        .circuit(3)
        .EUt(GTValues.VA[GTValues.MV])
        .duration(160)
    event.recipes.gtceu.polymerization("polypropylene_from_tetrachloride_oxygen")
        .inputFluids("gtceu:propene 2160", "gtceu:oxygen 7500", "gtceu:titanium_tetrachloride 100")
        .outputFluids("gtceu:polypropylene 4320")
        .circuit(3)
        .EUt(GTValues.VA[GTValues.MV])
        .duration(160)
    event.recipes.gtceu.polymerization("polypropylene_hardmode")
        .inputFluids(Fluid.of("gtceu:propene", 2160), Fluid.of("gtceu:oxygen", 7500))
        .itemInputs("#forge:dusts/phthalic_anhydride")
        .circuit(7)
        .outputFluids(Fluid.of("gtceu:polypropylene", 4320))
        .EUt(GTValues.VA[GTValues.MV])
        .duration(800)

    // Polyacrylonitrile (PAN) - TODO: subcomponent recipes
    event.recipes.gtceu.polymerization("polyacrylonitrile")
        .inputFluids("gtceu:acrylonitrile 900", "gtceu:acrylic_acid 100")
        .outputFluids("gtceu:polyacrylonitrile 1000")
        .circuit(1)
        .EUt(GTValues.VA[GTValues.LuV])
        .duration(300)
    
    // Bonus: PAN subrecipes
    event.recipes.gtceu.large_chemical_reactor("acrylonitrile")
        .inputFluids("gtceu:propene 1000", "gtceu:ammonia 1000", "gtceu:oxygen 1500")
        .outputFluids("gtceu:acrylonitrile 1000", "minecraft:water 3000")
        .circuit(4)
        .EUt(GTValues.VA[GTValues.LuV])
        .duration(400)
    
    event.recipes.gtceu.large_chemical_reactor("acrylic_acid_distilled")
        .inputFluids("gtceu:acetylene 500", "gtceu:carbon_monoxide 2000", "gtceu:distilled_water 1000")
        .chancedInput("gtceu:nickel_dust", 100, 0)
        .outputFluids("gtceu:acrylic_acid 750")
        .EUt(GTValues.VA[GTValues.IV])
        .duration(600)

    event.recipes.gtceu.large_chemical_reactor("acrylic_acid")
        .inputFluids("gtceu:acetylene 500", "gtceu:carbon_monoxide 2000", "minecraft:water 1000")
        .chancedInput("gtceu:nickel_dust", 200, 0)
        .outputFluids("gtceu:acrylic_acid 500")
        .EUt(GTValues.VA[GTValues.IV])
        .duration(600)
})
