
#Settings for accelerators
[general]
	#Accelerators size scale.
	#Defines size range for accelerators and affects calculations.
	#Size chart according to the scale:
	#1 - min size = 6, max size = 100
	#2 - min size = 60, max size = 1000
	#3 - min size = 600, max size = 10000
	#Range: 1 ~ 3
	scale_preset = 1
	#Beam attenuation rate.
	#Defines how much focus is lost per block in the beamline.
	#Default value is 0.02, which means 2% energy loss per block.
	#It also depends on scale preset
	#Range: 0.0 ~ 1.0
	beam_attenuation_rate = 0.02
	#The scaling factor for the beam attenuation equation.
	#Range: 0.0 ~ 2.147483647E9
	beam_scaling = 10000.0

#Particle chamber
[particle_chamber]
	#Min size.
	#Range: 5 ~ 11
	min_size = 5
	#Max size.
	#Range: 7 ~ 11
	max_size = 11

