/**
 * Material Registry for Oil catalysts
 */

GTCEuStartupEvents.registry("gtceu:material", event => {
    // Catalysts
    event.create("scandium_lanthanum_oil_catalyst")
        .dust().iconSet("fine")
        .color(0xE8C49E)
        .components("1x scandium", "3x lanthanum", "11x chlorine")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    event.create("platinum_rhenium_oil_catalyst")
        .dust().iconSet("fine")
        .color(0xDFDCC8)
        .components("1x platinum", "1x rhenium", "5x chlorine")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    // Catalyzed fractions
    // ScLa catalyst - Works on both hydro and steam cracking
    // Refinery gas
    event.create("scla_catalyzed_lightly_hydro_cracked_gas")
        .fluid()
        .color(0xE0D8C6)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("scla_catalyzed_severely_hydro_cracked_gas")
        .fluid()
        .color(0x9B9081)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("scla_catalyzed_lightly_steam_cracked_gas")
        .fluid()
        .color(0xC8BBAA)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("scla_catalyzed_severely_steam_cracked_gas")
        .fluid()
        .color(0x8F7E70)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    // Naphtha
    event.create("scla_catalyzed_lightly_hydro_cracked_naphtha")
        .fluid()
        .color(0xD9C168)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("scla_catalyzed_severely_hydro_cracked_naphtha")
        .fluid()
        .color(0xA28E40)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("scla_catalyzed_lightly_steam_cracked_naphtha")
        .fluid()
        .color(0xC4A844)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("scla_catalyzed_severely_steam_cracked_naphtha")
        .fluid()
        .color(0x8F6E20)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    // Light Fuel
    event.create("scla_catalyzed_lightly_hydro_cracked_light_fuel")
        .fluid()
        .color(0xF1E2A0)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("scla_catalyzed_severely_hydro_cracked_light_fuel")
        .fluid()
        .color(0xCFC080)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("scla_catalyzed_lightly_steam_cracked_light_fuel")
        .fluid()
        .color(0xE6D890)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("scla_catalyzed_severely_steam_cracked_light_fuel")
        .fluid()
        .color(0xBFA060)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    // Heavy Fuel
    event.create("scla_catalyzed_lightly_hydro_cracked_heavy_fuel")
        .fluid()
        .color(0xA18544)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("scla_catalyzed_severely_hydro_cracked_heavy_fuel")
        .fluid()
        .color(0x6E5428)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("scla_catalyzed_lightly_steam_cracked_heavy_fuel")
        .fluid()
        .color(0x8F6E30)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("scla_catalyzed_severely_steam_cracked_heavy_fuel")
        .fluid()
        .color(0x5E4320)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    // PtRe catalyst - Works on hydro cracking only
    // Refinery Gas
    event.create("ptre_catalyzed_lightly_hydro_cracked_gas")
        .fluid()
        .color(0xD8D0C0)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("ptre_catalyzed_severely_hydro_cracked_gas")
        .fluid()
        .color(0x9A9080)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    // Naphtha
    event.create("ptre_catalyzed_lightly_hydro_cracked_naphtha")
        .fluid()
        .color(0xD0C060)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("ptre_catalyzed_severely_hydro_cracked_naphtha")
        .fluid()
        .color(0x9C8E38)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    // Light Fuel
    event.create("ptre_catalyzed_lightly_hydro_cracked_light_fuel")
        .fluid()
        .color(0xE8D890)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("ptre_catalyzed_severely_hydro_cracked_light_fuel")
        .fluid()
        .color(0xC0B070)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    // Heavy Fuel
    event.create("ptre_catalyzed_lightly_hydro_cracked_heavy_fuel")
        .fluid()
        .color(0x9B7F38)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create("ptre_catalyzed_severely_hydro_cracked_heavy_fuel")
        .fluid()
        .color(0x6A5320)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
        
})
