// priority: -10
/**
 * Material Registry for ores.
 */

GTCEuStartupEvents.registry("gtceu:material", event => {

    // Snowchestite is part of harder Naquadah Processing
    event.create("snowchestite")
        .dust().ore()
        .color(0x274c9f).iconSet("shiny")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
        .components("3x naquadah_oxide", "pyromorphite")
        .addOreByproducts("chalcopyrite", "vanadium_magnetite", "naquadah_hydroxide")

    // Earth
    event.create("azurite")
        .dust().ore(2, 3)
        .iconSet(GTMaterialIconSet.SHINY)
        .color(0x162eba).secondaryColor(0x053f2b)
        .components(GTMaterials.Copper.multiply(3), GTMaterials.Carbon.multiply(2), GTMaterials.Oxygen.multiply(8), GTMaterials.Hydrogen.multiply(2))
        .formula("Cu3(CO3)2(OH)2")
        .addOreByproducts(GTMaterials.Calcite, GTMaterials.CalciumHydroxide, GTMaterials.Barite, GTMaterials.Malachite)
        .washedIn(GTMaterials.NitricAcid)
        .oreSmeltInto(GTMaterials.Copper)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    // Moon
    event.create("dilithium")
        .gem().ore(2, 1)
        .iconSet("dilithium")
        .color(0xfdd2df).secondaryColor(0xfa52b5)
        .element(GTElements.get("dilithium"))
        .addOreByproducts(GTMaterials.Lithium, GTMaterials.Cobalt, GTMaterials.Platinum)

    event.create("fluorite")
        .gem().ore()
        .iconSet(GTMaterialIconSet.DIAMOND)
        .color(0x0c9949)
        .components(GTMaterials.Calcium.multiply(1), GTMaterials.Fluorine.multiply(2))
        .addOreByproducts(GTMaterials.Calcite, GTMaterials.Barite)

    event.create("anorthite")
        .gem().ore(2, 2)
        .iconSet(GTMaterialIconSet.GEM_VERTICAL)
        .color(0xddd4af).secondaryColor(0x575d60)
        .components(GTMaterials.Calcium.multiply(1), GTMaterials.Aluminium.multiply(2), GTMaterials.Silicon.multiply(2), GTMaterials.Oxygen.multiply(8))
        .addOreByproducts(GTMaterials.Sodium, GTMaterials.Sodium, GTMaterials.Aluminium)
        .washedIn(GTMaterials.NitricAcid)

    // Mars
    event.create("columbite")
        .dust().ore(2, 2)
        .iconSet(GTMaterialIconSet.METALLIC)
        .color(0x304868).secondaryColor(0x161a1e)
        .components(GTMaterials.Iron.multiply(1), GTMaterials.Niobium.multiply(2), GTMaterials.Oxygen.multiply(6))
        .addOreByproducts(GTMaterials.Manganese, GTMaterials.Tantalum, GTMaterials.Niobium)
        .washedIn(GTMaterials.NitricAcid)

    event.create("arsenopyrite")
        .dust().ore(2, 2)
        .iconSet(GTMaterialIconSet.ROUGH)
        .color(0xced89c).secondaryColor(0x375944)
        .components(GTMaterials.Iron.multiply(1), GTMaterials.Arsenic.multiply(1), GTMaterials.Sulfur.multiply(1))
        .addOreByproducts(GTMaterials.Sulfur, GTMaterials.Cobalt, GTMaterials.Sulfur)
        .washedIn(GTMaterials.NitricAcid)

    event.create("carnotite")
        .dust().ore(2, 2)
        .iconSet(GTMaterialIconSet.METALLIC)
        .color(0xe8de29).secondaryColor(0xb58c34)
        .components(GTMaterials.Potassium.multiply(2), GTMaterials.Uraninite.multiply(6), GTMaterials.Vanadium.multiply(2), GTMaterials.Oxygen.multiply(8), GTMaterials.Water.multiply(9))
        .formula("K2(UO2)2(VO4)2(H2O)3")
        .addOreByproducts(GTMaterials.Uraninite, GTMaterials.Potassium, GTMaterials.Vanadium)
        .washedIn(GTMaterials.NitricAcid)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    // Venus
    event.create("cuprorhodsite")
        .dust().ore()
        .iconSet(GTMaterialIconSet.BRIGHT)
        .color(0xc1aa82)
        .components(GTMaterials.Copper.multiply(1), GTMaterials.Iron.multiply(1), GTMaterials.Rhodium.multiply(4), GTMaterials.Sulfur.multiply(8))
        .addOreByproducts(GTMaterials.Chalcocite, GTMaterials.Platinum, GTMaterials.Ruthenium)

    event.create("argentite")
        .dust().ore(2, 2)
        .iconSet(GTMaterialIconSet.ROUGH)
        .color(0xc6c6b8).secondaryColor(0x1c1c28)
        .components(GTMaterials.Silver.multiply(2), GTMaterials.Sulfur.multiply(1))
        .addOreByproducts(GTMaterials.Lead, GTMaterials.Sulfur, GTMaterials.Zinc)
        .washedIn(GTMaterials.NitricAcid)
        .oreSmeltInto(GTMaterials.Silver)

    event.create("titanite")
        .gem().ore(2, 2)
        .iconSet(GTMaterialIconSet.GEM_HORIZONTAL)
        .color(0xa3ba3d).secondaryColor(0x355b30)
        .components(GTMaterials.Calcium.multiply(1), GTMaterials.Titanium.multiply(1), GTMaterials.Silicon.multiply(1), GTMaterials.Oxygen.multiply(5))
        .addOreByproducts(GTMaterials.Calcium, GTMaterials.Rutile, GTMaterials.get("fluorite"), GTMaterials.RareEarth)
        .washedIn(GTMaterials.NitricAcid)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    event.create("xenotime")
        .gem().ore(1, 2)
        .color(0xaa802a).secondaryColor(0x211a14)
        .components(GTMaterials.Yttrium.multiply(1), GTMaterials.Phosphate.multiply(1))
        .addOreByproducts(GTMaterials.Yttrium, GTMaterials.RareEarth, GTMaterials.Samarium)
        .washedIn(GTMaterials.NitricAcid)

    event.create("gallite")
        .dust().ore(1, 2)
        .color(0xedb376).secondaryColor(0x5b5563)
        .components(GTMaterials.Copper.multiply(1), GTMaterials.Gallium.multiply(1), GTMaterials.Sulfur.multiply(2))
        .addOreByproducts(GTMaterials.Chalcopyrite, GTMaterials.Gallium, GTMaterials.Gallium, GTMaterials.get("germanium_disulfide"))
        .washedIn(GTMaterials.NitricAcid)

    event.create("briartite")
        .dust().ore()
        .color(0xc4bf60).secondaryColor(0xa5a598)
        .components(GTMaterials.Chalcocite.multiply(3), GTMaterials.Sphalerite.multiply(2), "3x germanium_disulfide")
        .addOreByproducts(GTMaterials.Copper, GTMaterials.Sphalerite, GTMaterials.get("germanium_disulfide"))
        .washedIn(GTMaterials.Mercury)
        .flags(GTMaterialFlags.DECOMPOSITION_BY_CENTRIFUGING)

    // Mercury
    event.create("laurite")
        .dust().ore()
        .iconSet(GTMaterialIconSet.DIAMOND)
        .color(0x6f2c23)
        .components("ruthenium", "2x sulfur")
        .addOreByproducts("pyrite", "ruthenium", "rhodium")

    event.create("wolframite")
        .dust().ore(2, 2)
        .color(0xa0734e).secondaryColor(0x405275)
        .components(GTMaterials.Iron.multiply(1), GTMaterials.Manganese.multiply(1), GTMaterials.Tungsten.multiply(2), GTMaterials.Oxygen.multiply(8))
        .formula("(Fe,Mn)(WO3)O")
        .addOreByproducts(GTMaterials.Iron, GTMaterials.Manganese, GTMaterials.get("fluorite"))
        .washedIn(GTMaterials.NitricAcid)
        .separatedInto(GTMaterials.Iron)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    event.create("bismite")
        .dust().ore(2, 2)
        .color(0xd3e298).secondaryColor(0x43dbad)
        .components(GTMaterials.Bismuth.multiply(2), GTMaterials.Oxygen.multiply(3))
        .addOreByproducts(GTMaterials.Tin, GTMaterials.Bismuth)
        .washedIn(GTMaterials.NitricAcid)

    event.create("sperrylite")
        .gem().ore(2, 2)
        .color(0xaaa399).secondaryColor(0x37474F)
        .components(GTMaterials.Platinum.multiply(1), GTMaterials.Arsenic.multiply(2))
        .addOreByproducts(GTMaterials.Platinum, GTMaterials.Nickel, GTMaterials.Palladium)
        .washedIn(GTMaterials.NitricAcid)

    // Glacio
    event.create("iridosmine")
        .dust().ore()
        .iconSet(GTMaterialIconSet.METALLIC)
        .color(0x54afff).secondaryColor(0x1b5651)
        .components("2x osmium", "1x iridium")
        .addOreByproducts("osmium", "iridium", "rhodium")

    event.create("kaemanite")
        .dust().ore()
        .iconSet(GTMaterialIconSet.BRIGHT)
        .color(0xe7413c)
        .components("trinium", "tantalum", "4x oxygen")
        .addOreByproducts("niobium", "trinium_sulfide", "trinium")

    event.create("stolzite")
        .gem().ore(2, 3)
        .color(0xa5591f).secondaryColor(0x564517)
        .components(GTMaterials.Lead.multiply(1), GTMaterials.Tungsten.multiply(1), GTMaterials.Oxygen.multiply(4))
        .formula("Pb(WO3)O")
        .addOreByproducts(GTMaterials.Lead, GTMaterials.Manganese, GTMaterials.Molybdenum)
        .washedIn(GTMaterials.NitricAcid)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION, GTMaterialFlags.CRYSTALLIZABLE, GTMaterialFlags.GENERATE_LENS)

    // MM-Exclusive
    event.create("darmstadtite")
        .dust().ore(2, 1)
        .iconSet(GTMaterialIconSet.DULL)
        .color(0x99AA87)
        .components(GTMaterials.Darmstadtium.multiply(2), GTMaterials.Sulfur.multiply(3))
        .addOreByproducts(GTMaterials.RhodiumSulfate, GTMaterials.RareEarth, GTMaterials.Darmstadtium)

    event.create("dulysite")
        .gem().ore(2, 1)
        .iconSet(GTMaterialIconSet.DIAMOND)
        .color(0xF5EFC0)
        .components(GTMaterials.Duranium, GTMaterials.Chlorine.multiply(3))
        .addOreByproducts(GTMaterials.Sphalerite, GTMaterials.Duranium, GTMaterials.Europium)

    // ZFG-Exclusive
    event.create("anatase")
        .gem().ore(2, 1)
        .iconSet(GTMaterialIconSet.GEM_HORIZONTAL)
        .color(0x092743).secondaryColor(0x0d0803)
        .components(GTMaterials.Titanium.multiply(1), GTMaterials.Oxygen.multiply(2))
        .addOreByproducts(GTMaterials.Magnetite, GTMaterials.Rutile, GTMaterials.Zirconium)
        .washedIn(GTMaterials.Mercury)
        .flags(GTMaterialFlags.GENERATE_LENS)
    
    event.create("black_opal")
        .gem().ore(3, 1)
        .iconSet(GTMaterialIconSet.OPAL)
        .color(0x201457).secondaryColor(0xe00f4f)
        .components(GTMaterials.Silicon.multiply(1), GTMaterials.Oxygen.multiply(2), GTMaterials.Water.multiply(1))
        .formula("SiO2·H2O")
        .addOreByproducts(GTMaterials.Opal, GTMaterials.Quartzite, GTMaterials.YellowLimonite)

    event.create('brookite')
        .gem().ore(1, 1)
        .iconSet(GTMaterialIconSet.CERTUS)
        .color(0xf08400).secondaryColor(0x402300)
        .components(GTMaterials.Titanium.multiply(1), GTMaterials.Oxygen.multiply(2))
        .addOreByproducts(GTMaterials.Hematite, GTMaterials.Niobium, GTMaterials.Tantalite)
        .washedIn(GTMaterials.Mercury)
    
    event.create("vanadium_pentoxide") // Move back to chemline_harder_misc.js if possible
        .dust()
        .color(0xffcf33).iconSet("rough")
        .components("2x vanadium", "5x oxygen")
    
    event.create('cavansite')
        .gem().ore(1, 1)
        .iconSet(GTMaterialIconSet.LAPIS)
        .color(0x1a99ff).secondaryColor(0x2bb8e3)
        .components(GTMaterials.Calcium.multiply(1), GTMaterials.Vanadium.multiply(1), GTMaterials.Silicon.multiply(4), GTMaterials.Oxygen.multiply(11), GTMaterials.Water.multiply(4))
        .formula("Ca(VO)Si4O10·4H2O")
        .addOreByproducts("vanadium_pentoxide", "vanadium_pentoxide", "vanadium_pentoxide")
        // .addOreByproducts(GTMaterials.CertusQuartz, GTMaterials.Calcium, "vanadium_pentoxide")

    event.create('chambersite')
        .gem().ore(1, 1)
        .iconSet("triangle") // TODO: custom triangular iconSet
        .color(0x7e5c9e).secondaryColor(0x291140)
        .components(GTMaterials.Manganese.multiply(3), GTMaterials.Boron.multiply(7), GTMaterials.Oxygen.multiply(13), GTMaterials.Chlorine.multiply(1))
        .addOreByproducts(GTMaterials.RockSalt, GTMaterials.Salt, GTMaterials.Borax)
    
    event.create('chrysoberyl')
        .gem().ore(3, 1)
        .iconSet(GTMaterialIconSet.EMERALD)
        .color(0xedf03f).secondaryColor(0xd8d9a0)
        .components(GTMaterials.Beryllium.multiply(1), GTMaterials.Aluminium.multiply(2), GTMaterials.Oxygen.multiply(4))
        .addOreByproducts(GTMaterials.Quartzite, GTMaterials.Lithium, GTMaterials.Niobium)
        .flags(GTMaterialFlags.CRYSTALLIZABLE)
    
    event.create('citrine')
        .gem().ore(3, 1)
        .iconSet(GTMaterialIconSet.FINE)
        .color(0xfdff7d).secondaryColor(0xebb44c)
        .components(GTMaterials.Silicon.multiply(1), GTMaterials.Oxygen.multiply(2))
        .addOreByproducts(GTMaterials.NetherQuartz, GTMaterials.YellowLimonite, GTMaterials.YellowLimonite)
        .washedIn(GTMaterials.get("hexafluorosilicic_acid"))
        .flags(GTMaterialFlags.GENERATE_LENS, GTMaterialFlags.CRYSTALLIZABLE, GTMaterialFlags.DISABLE_DECOMPOSITION)

    event.create('cryolite')
        .dust().ore(1, 1)
        .iconSet(GTMaterialIconSet.DULL)
        .color(0xfff9df).secondaryColor(0xe3dae2)
        .components(GTMaterials.Sodium.multiply(3), GTMaterials.Aluminium.multiply(1), GTMaterials.Fluorine.multiply(6))
        .addOreByproducts(GTMaterials.Salt, GTMaterials.Bauxite, GTMaterials.Iodine)

    event.create('ekanite')
        .gem().ore(1, 1)
        .iconSet(GTMaterialIconSet.EMERALD)
        .color(0xa1bd57).secondaryColor(0x6c8038)
        .components(GTMaterials.Calcium.multiply(2), GTMaterials.Thorium.multiply(1), GTMaterials.Silicon.multiply(8), GTMaterials.Oxygen.multiply(20))
        .addOreByproducts(GTMaterials.Magnetite, GTMaterials.Lead, GTMaterials.Uraninite)

    event.create('fergusonite')
        .dust().ore(1, 1)
        .iconSet(GTMaterialIconSet.DULL)
        .color(0xb09569).secondaryColor(0x706b55)
        .components("1x yttrium", '1x rare_earth', "1x niobium", "4x oxygen")
        .addOreByproducts("scandium", "tantalite", "thorium", "scheelite")
        .formula("(Y,?)NbO4")

    event.create('gadolinite')
        .dust().ore(1, 1)
        .iconSet(GTMaterialIconSet.DULL)
        .color(0x80634f).secondaryColor(0x212833)
        .components("2x rare_earth", "1x iron", "2x beryllium", "2x silicon", "10 oxygen")
        .addOreByproducts("beryllium_oxide", "thorium", "gadolinium", "monazite")
        .formula("(Ce,La,Nd,Y)2FeBe2Si2O10")
        .washedIn(GTMaterials.get("hexafluorosilicic_acid"))

    event.create('germanite')
        .dust().ore(1, 1)
        .iconSet(GTMaterialIconSet.BRIGHT)
        .color(0x788c94).secondaryColor(0x595552)
        .components("26x copper", "4x germanium", "4x iron", "32x sulfur")
        .addOreByproducts("molybdenite", "realgar", "gallium", "briartite")
        .washedIn("sodium_persulfate")

    event.create("hawleyite")
        .dust().ore(1, 1)
        .color(0xf0d61c).secondaryColor(0xd4db3d)
        .iconSet(GTMaterialIconSet.SAND)
        .components("1x cadmium, 1x sulfur").formula("CdS")
        .addOreByproducts("sphalerite", "cadmium", "gallium")
        .washedIn(GTMaterials.get("hydrobromic_acid"))
        .oreSmeltInto("cadmium")

    event.create("hexagonite")
        .gem().ore(2, 1)
        .color(0xd4c7d6).secondaryColor(0x963d78)
        .iconSet(GTMaterialIconSet.LAPIS)
        .components("2x calcium", "5x magnesium", "8x silicon", "24x oxygen", "2x hydrogen")
        .formula("Ca2Mg5(Si8O22)(OH)2")
        .addOreByproducts("magnesite", "zincite", "manganese", "zincite")

    event.create("bromoargyrite")
        .dust()
        .color(0xB02E14).secondaryColor(0x665b54)
        .iconSet(GTMaterialIconSet.BRIGHT)
        .components("1x silver", "1x bromine")

    event.create("iodargyrite")
        .dust().ore(1, 1)
        .color(0xb05214).secondaryColor(0x665b54)
        .iconSet(GTMaterialIconSet.BRIGHT)
        .components("1x silver", "1x iodine")
        .addOreByproducts("galena", "silver", "bromoargyrite")
        .washedIn("hydrobromic_acid")
        .oreSmeltInto("silver")

    event.create("legrandite")
        .gem().ore(1, 1)
        .color(0xf7dd1a).secondaryColor(0xccad4d)
        .iconSet(GTMaterialIconSet.LAPIS)
        .components("2x zinc", "1x arsenic", "5x oxygen", "1x hydrogen", "1x water")
        .formula("Zn2(AsO4)(OH)·(H2O)")
        .addOreByproducts("goethite", "pyrite", "realgar")
        .oreSmeltInto("zinc")

    event.create("lorandite")
        .dust().ore(1, 1)
        .color(0xe81348).secondaryColor(0xa11538)
        .iconSet(GTMaterialIconSet.CERTUS)
        .components("1x thallium", "1x arsenic", "2x sulfur")
        .addOreByproducts("realgar", "cinnabar", "gold", "stibnite")
        .washedIn("mercury")

    event.create("madocite")
        .dust().ore(1, 1)
        .color(0xa0b593).secondaryColor(0x535452)
        .iconSet(GTMaterialIconSet.BRIGHT)
        .components("17x lead", "16x antimony", "16x arsenic", "41x sulfur")
        .formula("Pb17(Sb,As)16S41")
        .addOreByproducts("sphalerite", "stibnite", "pyrite", "selenium")
        .washedIn("mercury")

    event.create("manganite")
        .gem().ore(1, 1)
        .color(0x2a3026).secondaryColor(0x070d04)
        .iconSet(GTMaterialIconSet.LIGNITE)
        .components("1x manganese", "2x oxygen", "1x hydrogen")
        .formula("MnO(OH)")
        .addOreByproducts("goethite", "pyrolusite", "barite")
        .oreSmeltInto("manganese")
        .flags(GTMaterialFlags.GENERATE_LENS)

    event.create("melonite")
        .dust().ore(1, 1)
        .color(0xc2af28).secondaryColor(0x4d4a3c)
        .iconSet(GTMaterialIconSet.METALLIC)
        .components("1x nickel", "2x tellurium")
        .washedIn("mercury")
        .oreSmeltInto("nickel")
        .addOreByproducts("pentlandite", "nickel", "sperrylite", "platinum")

    event.create("microcline")
        .dust().ore(1, 1)
        .color(0xf7e1e6).secondaryColor(0xc79887)
        .iconSet(GTMaterialIconSet.LAPIS)
        .components("1x potassium", "1x aluminium", "3x silicon", "8x oxygen")
        .addOreByproducts("alunite", "rubidium", "thallium")

    event.create("mohite")
        .dust().ore(1, 1)
        .color(0x587A6B).secondaryColor(0x6E6E43)
        .iconSet(GTMaterialIconSet.DULL)
        .components("2x copper", "1x tin", "3x sulfur")
        .washedIn("mercury")
        .oreSmeltInto("bronze")
        .addOreByproducts("tetrahedrite", "cassiterite", "chalcocite", "bronze")

    event.create("moissanite")
        .gem().ore(2, 1)
        .color(0xe3e3e3).secondaryColor(0x7a807f)
        .iconSet(GTMaterialIconSet.DIAMOND)
        .components("1x silicon", "1x carbon")
        .addOreByproducts("diamond", "certus", "germanium")
        .flags(GTMaterialFlags.GENERATE_LENS)

    event.create("nambulite")
        .gem().ore(1, 1)
        .color(0xfc3353).secondaryColor(0xd92518)
        .iconSet(GTMaterialIconSet.GEM_HORIZONTAL)
        .components("1x lithium", "1x sodium", "4x manganese", "5x silicon", "15x oxygen", "1x hydrogen")
        .formula("(Li,Na)Mn4Si5O14(OH)")
        .washedIn(GTMaterials.get("hydrobromic_acid"))
        .addOreByproducts("calcite", "almandine", "grossular", "magnesite")
        .flags(GTMaterialFlags.GENERATE_LENS)

    event.create("rubellite")
        .gem().ore(1, 1)
        .color(0xed27a8).secondaryColor(0xe01e5f)
        .iconSet(GTMaterialIconSet.DIAMOND)
        .components("1x sodium", "1x lithium", "7x aluminium", "6x silicon", "31x oxygen", "3x boron", "4x hydrogen")
        .formula("Na(Li, Al)Al6Si6O18(BO3)3(OH)4")
        .washedIn(GTMaterials.get("hydrobromic_acid"))
        .addOreByproducts("lepidolite", "chromite", "microcline", "molybdenite")
        .flags(GTMaterialFlags.GENERATE_LENS) // Magenta lens

    event.create("russellite")
        .dust().ore(1, 1)
        .color(0xdbdba5).secondaryColor(0xe6e543)
        .iconSet(GTMaterialIconSet.SAND)
        .components("2x bismuth", "1x tungsten", "6x oxygen")
        .washedIn("mercury")
        .oreSmeltInto("bismuth")
        .addOreByproducts("cassiterite", "scheelite", "topaz", "tungstate")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION) 

    event.create('samarskite-yb')
        .dust().ore(1, 1)
        .color(0x40403b).secondaryColor(0x35402d)
        .iconSet(GTMaterialIconSet.DULL)
        .components("2x ytterbium", "2x iron", "2x niobium", "2x tantalum", "8x oxygen")
        .formula("(YbFe)2(Nb,Ta)2O8")
        .addOreByproducts("yellow_garnet", "uraninite", "yttrium")

    event.create('schizolite')
        .gem().ore(3, 1)
        .color(0xe0b8c3).secondaryColor(0xd67a93)
        .iconSet(GTMaterialIconSet.FINE)
        .components("1x sodium", "1x calcium", "1x manganese", "8x silicon", "9x oxygen", "1x hydrogen")
        .formula("NaCaMnSi8O8(OH)")
        .washedIn(GTMaterials.get("hexafluorosilicic_acid"))
        .addOreByproducts("spodumene", "sodalite", "lapis")
        .flags(GTMaterialFlags.GENERATE_LENS) // Pink lens

    event.create('selenite')
        .gem().ore(2, 1)
        .color(0xf2f2f2).secondaryColor(0xcfcfcf)
        .iconSet(GTMaterialIconSet.CERTUS)
        .components("1x calcium", "1x sulfur", "4x oxygen", "2x water")
        .formula("CaSO4·2H2O")
        .addOreByproducts("gypsum", "calcite", "selenium")
        .flags(GTMaterialFlags.GENERATE_LENS) // White lens

    event.create('spinel')
        .gem().ore(2, 1)
        .color(0xf22e58).secondaryColor(0xc90a98)
        .iconSet(GTMaterialIconSet.RUBY)
        .components("1x magnesium", "1x iron", "2x aluminium", "2x chromium", "4x oxygen")
        .formula("(Mg,Fe)(Al,Cr)2O4")
        .addOreByproducts("olivine", "chromite", "ruby")
        .flags(GTMaterialFlags.GENERATE_LENS) // Magenta lens

    event.create('stibiotantalite')
        .gem().ore(1, 1)
        .color(0xd99c2a).secondaryColor(0x946306)
        .iconSet(GTMaterialIconSet.FLINT)
        .components("1x antimony", "1x tantalum", "4x oxygen")
        .addOreByproducts("cassiterite", "niobium", "tantalite")

    event.create('suanite')
        .dust().ore(1, 1)
        .color(0xd6d6d6).secondaryColor(0x798182)
        .iconSet(GTMaterialIconSet.FINE)
        .components("2x magnesium", "2x boron", "5x oxygen")
        .addOreByproducts("magnesite", "malachite", "gold")

    event.create('tarapacaite')
        .dust().ore(1, 1)
        .color(0xccb881).secondaryColor(0xc2a966)
        .iconSet(GTMaterialIconSet.BRIGHT)
        .components("2x potassium", "1x chromium", "4x oxygen")
        .addOreByproducts("chromite", "potassium_chromate", "potassium_chromate")

    event.create('teallite')
        .dust().ore(1, 1)
        .color(0xa9c5cc).secondaryColor(0x7b8385)
        .iconSet(GTMaterialIconSet.SHINY)
        .components("1x lead", "1x tin", "2x sulfur")
        .washedIn("mercury")
        .oreSmeltInto("lead")
        .addOreByproducts("galena", "bismuth", "stibnite", "silver")

    event.create('thortveitite')
        .dust().ore(1, 1)
        .color(0xe8ad2e).secondaryColor(0x1c4d1b)
        .iconSet(GTMaterialIconSet.DULL)
        .components("1x scandium", "1x yttrium", "2x silicon", "7x oxygen")
        .formula("(Sc,Y)Si2O7")
        .washedIn(GTMaterials.get("hexafluorosilicic_acid"))
        .addOreByproducts("scandium", "nether_quartz", "rare_earth", "praseodymium")

    event.create('triphyllite')
        .gem().ore(3, 1)
        .color(0x344034).secondaryColor(0x525952)
        .iconSet(GTMaterialIconSet.LAPIS)
        .components("1x lithium", "1x iron", "1x phosphate")
        .formula("LiFePO4")
        .oreSmeltInto("iron")
        .addOreByproducts("lithium", "goethite", "manganese")

    event.create('tungstite')
        .dust().ore(1, 1)
        .color(0xf7d132).secondaryColor(0xd6aa12)
        .iconSet(GTMaterialIconSet.SAND)
        .components("1x tungsten", "3x oxygen", "1x water")
        .formula("WO3·H2O")
        .addOreByproducts("goethite", "tungstate", "scheelite")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    event.create('tusionite')
        .gem().ore(1, 1)
        .color(0x87794e).secondaryColor(0x756e59)
        .iconSet(GTMaterialIconSet.DULL)
        .components("1x manganese", "1x tin", "2x boron", "6x oxygen")
        .formula("MnSn(BO3)2")
        .addOreByproducts("cassiterite", "borax", "manganese")

    event.create('ulexite')
        .gem().ore(1, 1)
        .color(0xd1ccbd).secondaryColor(0xadaaa0)
        .iconSet(GTMaterialIconSet.CERTUS)
        .components("1x sodium", "1x calcium", "5x boron", "12x oxygen", "6x hydrogen", "5x water")
        .formula("NaCaB5O6(OH)6·5H2O")
        .addOreByproducts("trona", "borax", "borax")
        .flags(GTMaterialFlags.GENERATE_LENS) // LightGray lens

    event.create('ullmannite')
        .dust().ore(1, 1)
        .color(0x292825).secondaryColor(0x1a160c)
        .iconSet(GTMaterialIconSet.METALLIC)
        .components("1x nickel", "1x antimony", "1x sulfur")
        .washedIn("mercury")
        .oreSmeltInto("nickel")
        .addOreByproducts("pyrite", "stibnite", "cobaltite", "arsenic")

    event.create('umangite')
        .dust().ore(1, 1)
        .color(0x57a874).secondaryColor(0x39423c)
        .iconSet(GTMaterialIconSet.SAND)
        .components("3x copper", "2x selenium")
        .washedIn("sodium_persulfate")
        .oreSmeltInto("copper")
        .addOreByproducts("chalcocite", "mohite", "selenium", "tellurium")

    event.create('vanadinite')
        .gem().ore(1, 1)
        .color(0xf7562c).secondaryColor(0xb35114)
        .iconSet(GTMaterialIconSet.LAPIS)
        .components("5x lead", "3x vanadium", "12 oxygen", "1x chlorine")
        .formula("Pb5(VO4)3Cl")
        .washedIn("mercury")
        .oreSmeltInto("lead")
        .addOreByproducts("yellow_limonite", "galena", "wulfenite")

    event.create('wodginite')
        .dust().ore(1, 1)
        .color(0xa6a288).secondaryColor(0x0f0f0f)
        .iconSet(GTMaterialIconSet.SHINY)
        .components("1x manganese", "1x tin", "3x tantalum", "8x oxygen")
        .formula("Mn(Sn,Ta)Ta2O8")
        .addOreByproducts("tantalite", "microcline", "niobium")

    event.create('xilingolite')
        .dust().ore(1, 1)
        .color(0x949994).secondaryColor(0x404f3f)
        .iconSet(GTMaterialIconSet.QUARTZ)
        .components("3x lead", "2x bismuth", "6x sulfur")
        .washedIn("mercury")
        .oreSmeltInto("lead")
        .addOreByproducts("galena", "sphalerite", "molybdenite", "silver")

    event.create('euclase')
        .gem().ore(2, 1)
        .color(0x23cfc6).secondaryColor(0x319dc7)
        .iconSet(GTMaterialIconSet.EMERALD)
        .components("1x beryllium", "1x aluminium", "1x silicon", "5x oxygen", "1x hydrogen")
        .formula("BeAlSiO4(OH)")
        .addOreByproducts("certus_quartz", "fluorite", "anatase")
        .flags(GTMaterialFlags.GENERATE_LENS) // Cyan lens

    event.create('bazzite')
        .gem().ore(3, 1)
        .color(0x8de3df).secondaryColor(0x60dffa)
        .iconSet(GTMaterialIconSet.EMERALD)
        .components("3x beryllium", "2x scandium", "6x silicon", "18x oxygen")
        .addOreByproducts("euclase", "hematite", "fluorite")
        .flags(GTMaterialFlags.GENERATE_LENS) // Cyan lens or LightBlue lens?

    event.create('aquamarine')
        .gem().ore(3, 1)
        .color(0x78d3fc).secondaryColor(0x28c0d1)
        .iconSet(GTMaterialIconSet.EMERALD)
        .components("3x beryllium", '2x aluminium', "6x silicon", "18x oxygen")
        .addOreByproducts("pyrite", "euclase", "rutile")
        .flags(GTMaterialFlags.GENERATE_LENS) // Cyan lens or LightBlue lens?

    event.create('celestine')
        .gem().ore(3, 1)
        .color(0xcdbfe8).secondaryColor(0x8eb5c7)
        .iconSet(GTMaterialIconSet.QUARTZ)
        .components("1x strontium", '1x sulfur', "4x oxygen")
        //.oreSmeltInto("strontium")
        .addOreByproducts("selenite", "sulfur", "barite")

    event.create('strontianite')
        .gem().ore(1, 1)
        .color(0xdec18a).secondaryColor(0xccbea5)
        .iconSet(GTMaterialIconSet.QUARTZ)
        .components("1x strontium", '1x carbon', "3x oxygen")
        //.oreSmeltInto("strontium")
        .addOreByproducts("calcite", "barite", "celestine")

    event.create('aragonite')
        .dust().ore(2, 1)
        .color(0xf79b48).secondaryColor(0x6d6d6d)
        .iconSet(GTMaterialIconSet.LIGNITE)
        .components("1x calcium", "1x carbon", "3x oxygen")
        .addOreByproducts("calcite", "strontianite", "strontium")

    event.create('indite')
        .dust().ore(1, 1)
        .color(0x6e6769).secondaryColor(0x5e4c52)
        .iconSet(GTMaterialIconSet.SHINY)
        .components("1x iron", "2x indium", "4x sulfur")
        .washedIn("hydrobromic_acid")
        .addOreByproducts("spinel", "pyrite", "tellurium", "indium")

    event.create('cadmoindite')
        .dust().ore(1, 1)
        .color(0x05858a).secondaryColor(0x4720b8)
        .iconSet(GTMaterialIconSet.GEM_HORIZONTAL)
        .components("1x cadmium", "2x indium", "4x sulfur")
        .washedIn("hydrobromic_acid")
        .addOreByproducts("spinel", "indite", "hawleyite", "cadmium")

    event.create('calomel')
        .gem().ore(2, 1)
        .color(0xffb52a).secondaryColor(0xa38e6a)
        .iconSet(GTMaterialIconSet.RUBY)
        .components("2x mercury", "2x chlorine")
        .washedIn("hydrobromic_acid")
        .addOreByproducts("cinnabar", "yellow_limonite", "tetrahedrite", "coccinite")
        .flags(GTMaterialFlags.GENERATE_LENS) // Orange lens

    event.create('coccinite')
        .dust().ore(1, 1)
        .color(0xd99109).secondaryColor(0x302308)
        .iconSet(GTMaterialIconSet.SAND)
        .components("1x mercury", "2x iodine")
        .washedIn("hydrobromic_acid")
        .addOreByproducts("pyrite", "calomel", "iodine", "calomel")

    event.create('zircon')
        .gem().ore(2, 1)
        .color(0xa12300).secondaryColor(0x7a1e03)
        .iconSet(GTMaterialIconSet.LIGNITE)
        .components("1x zirconium", "1x silicon", "4x oxygen")
        .oreSmeltInto("zirconium")
        .addOreByproducts("citrine", "anatase", "hafnium")
        .flags(GTMaterialFlags.GENERATE_LENS) // Red lens

    event.create('datolite')
        .gem().ore(1, 1)
        .color(0xe9ffd1).secondaryColor(0xd8e0ce)
        .iconSet(GTMaterialIconSet.DIAMOND)
        .components("1x calcium", "1x boron", "1x silicon", "4x oxygen")
        .addOreByproducts("quartzite", "borax", "zircon")

    event.create('dzhalindite')
        .dust().ore(1, 1)
        .color(0xe8e8e8).secondaryColor(0x777866)
        .iconSet(GTMaterialIconSet.METALLIC)
        .components("1x indium", "3x oxygen", "3x hydrogen")
        .formula("In(OH)3")
        .oreSmeltInto("indium")
        .washedIn("hydrobromic_acid")
        .addOreByproducts("cassiterite", "tin", "indite", "cadmoindite")

    event.create('ferberite')
        .gem().ore(1, 1)
        .color(0x969696).secondaryColor(0x4d4d4d)
        .iconSet(GTMaterialIconSet.SHINY)
        .components("1x iron", "1x tungsten", "4x oxygen")
        .washedIn("mercury")
        .addOreByproducts("magnetite", "anatase", "wolframite", "tungstite")
        .flags(GTMaterialFlags.GENERATE_LENS, GTMaterialFlags.DISABLE_DECOMPOSITION) // Gray lens

    event.create('fluoroapatite')
        .gem().ore(3, 1)
        .color(0xa917bf).secondaryColor(0x524D3B)
        .iconSet(GTMaterialIconSet.LAPIS)
        .components("5x calcium", "3x phosphate", "1x fluorine")
        .formula("Ca5(PO4)3F")
        .addOreByproducts("fluorite", "apatite", "monazite")

    event.create('zincochromite')
        .dust().ore(1, 1)
        .color(0x839171).secondaryColor(0x454a3e)
        .iconSet(GTMaterialIconSet.DULL)
        .components("1x zinc", "2x chromium", "4x oxygen")
        .washedIn("sodium_persulfate")
        .addOreByproducts("spinel", "chromite", "zincite", "uraninite")

    event.create('guyanaite')
        .dust().ore(1, 1)
        .color(0x403d34).secondaryColor(0x211f19)
        .iconSet(GTMaterialIconSet.SHINY)
        .components("1x chromium", "2x oxygen", "1x hydrogen")
        .formula("CrO(OH)")
        .washedIn("sodium_persulfate")
        .addOreByproducts("zincochromite", "graphite", "zircon", "chromite")

    event.create('heptasartorite')
        .dust().ore(1, 1)
        .color(0x72d423).secondaryColor(0x999999)
        .iconSet(GTMaterialIconSet.METALLIC)
        .components("7x thallium", "22x lead", "55x arsenic", "108x sulfur")
        .washedIn("mercury")
        .addOreByproducts("selenium", "tellurium", "lorandite", "cobaltite")

    event.create('herderite')
        .gem().ore(2, 1)
        .color(0xC6E09A).secondaryColor(0x93AF63)
        .iconSet(GTMaterialIconSet.EMERALD)
        .components("1x calcium", "1x beryllium", "1x phosphate", "1x oxygen", "1x hydrogen", "1x fluorine")
        .formula("CaBe(PO4)(F,OH)")
        .addOreByproducts("fluoroapatite", "fluorite", "iodine")
        .flags(GTMaterialFlags.GENERATE_LENS) // Lime lens

    event.create('hubnerite')
        .dust().ore(1, 1)
        .color(0xd40748).secondaryColor(0x1a0008)
        .iconSet(GTMaterialIconSet.RUBY)
        .components("1x manganese", "1x tungsten", "4x oxygen")
        .washedIn("mercury")
        .addOreByproducts("pyrolusite", "brookite", "wolframite", "tungstite")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    event.create('rheniite')
        .dust().ore(1, 1)
        .color(0xc4c1c2).secondaryColor(0x87797E)
        .iconSet(GTMaterialIconSet.METALLIC)
        .components("1x rhenium", "2x sulfur")
        .washedIn("mercury")
        .addOreByproducts("sphalerite", "molybdenite", "laurite", "molybdenum")

    event.create('lindgrenite')
        .gem().ore(1, 1)
        .color(0x4c9408).secondaryColor(0x335e0a)
        .iconSet(GTMaterialIconSet.QUARTZ)
        .components("3x copper", "2x molybdenum", "10x oxygen", "2x hydrogen")
        .formula("Cu3(MoO4)2(OH)2")
        .washedIn("sodium_persulfate")
        .addOreByproducts("powellite", "molybdenite", "malachite", "rheniite")
        .flags(GTMaterialFlags.GENERATE_LENS) // Green lens

    event.create('torbernite')
        .gem().ore(2, 1)
        .color(0x0B620A).secondaryColor(0x053404)
        .iconSet(GTMaterialIconSet.GEM_HORIZONTAL)
        .components("1x copper", "2x uraninite", "2x phosphate", "12x water")
        .formula("Cu[(UO2)(PO4)]2(H2O)12")
        .washedIn("sodium_persulfate")
        .oreSmeltInto("copper")
        .addOreByproducts("uraninite", "lindgrenite", "azurite", "plutonium")
        .flags(GTMaterialFlags.GENERATE_LENS) // Green lens

    event.create('turquoise')
        .gem().ore(3, 1)
        .color(0x1ee0d4).secondaryColor(0x4d3d0f)
        .iconSet(GTMaterialIconSet.LAPIS)
        .components("1x copper", "6x aluminium", "4x phosphate", "8x oxygen", "8x hydrogen", "4x water")
        .formula("CuAl6(PO4)4(OH)8·4H2O")
        .washedIn("sodium_persulfate")
        .addOreByproducts("certus_quartz", "kyanite", "lindgrenite", "torbernite")

    event.create('vivianite')
        .gem().ore(2, 1)
        .color(0x49783f).secondaryColor(0x3f664b)
        .iconSet(GTMaterialIconSet.CERTUS)
        .components("3x iron", "2x phosphate", "8x water")
        .formula("Fe3(PO4)2·8H2O")
        .oreSmeltInto("iron")
        .addOreByproducts("aragonite", "magnesite", "manganese")
        .flags(GTMaterialFlags.GENERATE_LENS) // Green lens

    event.create('phosphosiderite')
        .gem().ore(3, 1)
        .color(0xba89d9).secondaryColor(0x9f8cab)
        .iconSet(GTMaterialIconSet.LAPIS)
        .components("1x iron", "1x phosphate", "2x water")
        .formula("FePO4·2H2O")
        .oreSmeltInto("iron")
        .addOreByproducts("triphyllite", "turquoise", "vivianite")

    event.create('kolbeckite')
        .dust().ore(1, 1)
        .color(0xcaf071).secondaryColor(0x95AA7B)
        .iconSet(GTMaterialIconSet.LAPIS)
        .components("1x scandium", "1x phosphate", "2x water")
        .formula("ScPO4·2H2O")
        .oreSmeltInto("scandium")
        .addOreByproducts("Yttrium", "phosphosiderite", "rare_earth")

    event.create('labyrinthite')
        .dust().ore(2, 1)
        .color(0xe8b3c5).secondaryColor(0x854b5e)
        .iconSet(GTMaterialIconSet.FINE)
        .components("35x sodium", "35x potassium", "35x strontium", "12x calcium", "3x iron", "6x zirconium", "1x titanium", "51x silicon", "162x oxygen", "9x hydrogen", "3x chlorine", "9x water")
        .formula("(Na,K,Sr)35Ca12Fe3Zr6TiSi51O144(O,OH,H2O)9Cl3")
        .washedIn("hexafluorosilicic_acid")
        .addOreByproducts("fluorite", "cerium", "rubidium", "thallium")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION) // TODO: custom decomp

    event.create('manganvesuvianite')
        .gem().ore(2, 1)
        .color(0xD56076).secondaryColor(0x3d0303)
        .iconSet(GTMaterialIconSet.CERTUS)
        .components("19x calcium", "13x manganese", "10x aluminium", "10x iron", "2x magnesium", "18x silicon", "78x oxygen", "9x hydrogen")
        .formula("Ca19Mn(Al,Mn,Fe)10(Mg,Mn)2(Si2O7)4(SiO4)10O(OH)9")
        .washedIn("hexafluorosilicic_acid")
        .addOreByproducts("calcite", "grossular", "manganite", "strontium")

    event.create('temagamite')
        .dust().ore(1, 1)
        .color(0xa288b8).secondaryColor(0x71677a)
        .iconSet(GTMaterialIconSet.BRIGHT)
        .components("3x lead", "1x mercury", "3x tellurium")
        .washedIn("nitric_acid")
        .oreSmeltInto("lead")
        .addOreByproducts("melonite", "chalcopyrite", "galena", "silver")
    
    event.create('merenskyite')
        .dust().ore(1, 1)
        .color(0xa5b39f).secondaryColor(0x7b8f86)
        .iconSet(GTMaterialIconSet.FLINT)
        .components("1x palladium", "1x platinum", "2x tellurium", "2x bismuth")
        .formula("(Pd,Pt)(Te,Bi)2")
        .washedIn("mercury")
        .addOreByproducts("chalcopyrite", "temagamite", "palladium", "platinum")

    event.create('morganite')
        .gem().ore(2, 1)
        .color(0xf7ae8a).secondaryColor(0xD17D84)
        .iconSet(GTMaterialIconSet.EMERALD)
        .components("3x beryllium", "2x aluminium", "6x silicon", "18x oxygen")
        .addOreByproducts("lepidolite", "euclase", "aquamarine")
        .flags(GTMaterialFlags.GENERATE_LENS) // Pink lens (?)

    event.create('pezzottaite')
        .gem().ore(2, 1)
        .color(0xff4f82).secondaryColor(0xAC6393)
        .iconSet(GTMaterialIconSet.EMERALD)
        .components("1x cesium", "2x beryllium", "1x lithium", "2x aluminium", "6x silicon", "18x oxygen")
        .formula("Cs(Be2Li)Al2Si6O18")
        .washedIn("hexafluorosilicic_acid")
        .addOreByproducts("morganite", "manganese", "rubidium", "cesium")
        .flags(GTMaterialFlags.GENERATE_LENS) // Magenta lens (?)

    event.create('milarite')
        .gem().ore(3, 1)
        .color(0xffffe6).secondaryColor(0xe7e89e)
        .iconSet(GTMaterialIconSet.CERTUS)
        .components("3x beryllium", "2x aluminium", "6x silicon", "18x oxygen")
        .formula("Be3Al2(SiO3)6")
        .addOreByproducts("chrysoberyl", "emerald", "pezzottaite")

    event.create('mixite')
        .gem().ore(2, 1)
        .color(0x3efac9).secondaryColor(0x0ba357)
        .iconSet(GTMaterialIconSet.FLINT)
        .components("1x bismuth", "6x copper", "3x arsenic", "18x oxygen", "6x hydrogen", "3x water")
        .formula("BiCu6(AsO4)3(OH)6·3H2O")
        .washedIn("sodium_persulfate")
        .oreSmeltInto("copper")
        .addOreByproducts("malachite", "monazite", "xenotime", "azurite")

    event.create('mottramite')
        .dust().ore(1, 1)
        .color(0xa7b35d).secondaryColor(0x677045)
        .iconSet(GTMaterialIconSet.LIGNITE)
        .components("1x lead", "1x copper", "1x vanadium", "5x oxygen", "1x hydrogen")
        .formula("PbCu(VO4)(OH)")
        .washedIn("sodium_persulfate")
        .addOreByproducts("calcite", "vanadinite", "vanadium_magnetite", "russellite")

    event.create('musgravite')
        .gem().ore(2, 1)
        .color(0x85798a).secondaryColor(0x6a5b70)
        .iconSet(GTMaterialIconSet.EMERALD)
        .components("2x magnesium", "2x iron", "2x manganese", "1x beryllium", "6x aluminium", "12x oxygen")
        .formula("(Mg,Fe,Mn)2BeAl6O12")
        .addOreByproducts("beryllium", "morganite", "thorium")
        .flags(GTMaterialFlags.GENERATE_LENS)

    event.create('witherite')
        .gem().ore(1, 1)
        .color(0xebe6c2).secondaryColor(0xd9d090)
        .iconSet(GTMaterialIconSet.FINE)
        .components("1x barium", "1x carbon", "3x oxygen")
        .addOreByproducts("calcite", "strontianite", "lead")

    event.create('otavite')
        .gem().ore(1, 1)
        .color(0xeffcfc).secondaryColor(0xd6d6d6)
        .iconSet(GTMaterialIconSet.SHINY)
        .components("1x cadmium", "1x carbon", "3x oxygen")
        .washedIn("hydrobromic_acid")
        .addOreByproducts("aragonite", "malachite", "witherite", "strontianite")
        .flags(GTMaterialFlags.GENERATE_LENS)

    event.create('phosphophyllite')
        .gem().ore(3, 1)
        .color(0xa6edcd).secondaryColor(0x5ac293)
        .iconSet(GTMaterialIconSet.CERTUS)
        .components("2x zinc", "1x iron", "2x phosphate", "4x water")
        .formula("Zn2Fe(PO4)2·4H2O")
        .addOreByproducts("triphyllite", "chalcopyrite", "legrandite")

    event.create('purpurite')
        .dust().ore(1, 1)
        .color(0xaf21ba).secondaryColor(0x9c3d97)
        .iconSet(GTMaterialIconSet.LAPIS)
        .components("1x manganese", "1x phosphate")
        .formula("MnPO4")
        .oreSmeltInto("manganese")
        .addOreByproducts("phosphosiderite", "hematite", "amethyst")

    event.create('red_beryl')
        .gem().ore(2, 1)
        .color(0xfc2953).secondaryColor(0xad043a)
        .iconSet(GTMaterialIconSet.EMERALD)
        .components("3x beryllium", "2x aluminium", "6x silicon", "18x oxygen")
        .addOreByproducts("emerald", "manganese", "pezzottaite")
        .flags(GTMaterialFlags.GENERATE_LENS)

    event.create('rhodplumsite')
        .dust().ore(1, 1)
        .color(0xb07942).secondaryColor(0x505659)
        .iconSet(GTMaterialIconSet.DULL)
        .components("3x rhodium", "2x lead", "2x sulfur")
        .washedIn("mercury")
        .addOreByproducts("galena", "platinum", "sperrylite", "ruthenium")

    event.create('taaffeite')
        .gem().ore(2, 1)
        .iconSet(GTMaterialIconSet.EMERALD)
        .color(0x9247C0).secondaryColor(0x8F3997)
        .components("1x beryllium", "1x magnesium", "4x aluminium", "8x oxygen")
        .addOreByproducts("spinel", "chrysoberyl", "musgravite", "beryllium")
        .flags(GTMaterialFlags.GENERATE_LENS, GTMaterialFlags.CRYSTALLIZABLE)

    event.create('triplite')
        .gem().ore(3, 1)
        .color(0xfc621d).secondaryColor(0xad3b1b)
        .iconSet(GTMaterialIconSet.FINE)
        .components("2x manganese", "2x iron", "1x phosphate", "1x fluorine", "1x oxygen", "1x hydrogen")
        .formula("(Mn,Fe)2(PO4)(F,OH)")
        .addOreByproducts("red_garnet", "almandine", "phosphosiderite")
        .flags(GTMaterialFlags.GENERATE_LENS)

    event.create('vayrynenite')
        .gem().ore(2, 1)
        .color(0xff3560).secondaryColor(0xd13704)
        .iconSet(GTMaterialIconSet.EMERALD)
        .components("1x manganese", "1x beryllium", "1x phosphate", "1x fluorine", "1x oxygen", "1x hydrogen")
        .formula("MnBe(PO4)(F,OH)")
        .addOreByproducts("fluoroapatite", "red_beryl", "morganite")
        .flags(GTMaterialFlags.GENERATE_LENS)

    event.create('villiaumite')
        .gem().ore(3, 1)
        .color(0xc20000).secondaryColor(0x850202)
        .iconSet(GTMaterialIconSet.FLINT)
        .components("1x sodium", "1x fluorine")
        .washedIn("hydrobromic_acid")
        .addOreByproducts("sodalite", "lazurite", "fluorite", "lapis")
        .flags(GTMaterialFlags.CRYSTALLIZABLE)

    event.create('wakefieldite')
        .dust().ore(1, 1)
        .color(0xcf61db).secondaryColor(0x302930)
        .iconSet(GTMaterialIconSet.RUBY)
        .components("1x lanthanum", "1x vanadium", "4x oxygen")
        .washedIn("sodium_persulfate")
        .addOreByproducts("xenotime", "monazite", "cerium", "neodymium")

    event.create('xanthoconite')
        .gem().ore(1, 1)
        .color(0xf29639).secondaryColor(0xa15a12)
        .iconSet(GTMaterialIconSet.RUBY)
        .components("3x silver", "1x arsenic", "3x sulfur")
        .washedIn("mercury")
        .oreSmeltInto("silver")
        .addOreByproducts("galena", "teallite", "arsenic", "sperrylite")
        .flags(GTMaterialFlags.GENERATE_LENS)

    event.create('zavaritskite')
        .dust().ore(1, 1)
        .color(0x82d6ab).secondaryColor(0x3f5e4e)
        .iconSet(GTMaterialIconSet.BRIGHT)
        .components("1x bismuth", "1x oxygen", "1x fluorine")
        .formula("(BiO)F")
        .oreSmeltInto("bismuth")
        .addOreByproducts("fluorite", "cassiterite", "gold")

    event.create('zoisite')
        .gem().ore(3, 1)
        .color(0x67a180).secondaryColor(0xb53889)
        .iconSet(GTMaterialIconSet.OPAL)
        .components("2x calcium", "3x aluminium", "3x silicon", "13x oxygen", "1x hydrogen")
        .formula("Ca2Al3(SiO4)(Si2O7)O(OH)")
        .addOreByproducts("gypsum", "hexagonite", "rubellite")

    // TODO: Fictional superheavy ores for gem growing vat
    event.create("nihonyl")
    event.create("thallottaite")
    event.create("rubolawrencite")
    event.create("hassigrite")
    event.create("radiomuscogravite")
    event.create("chrysolutelite")
    event.create("heavy_opal")
    event.create("bromonicium")
    event.create("xanthoroentgenite")

})
